# -*- coding: utf-8 -*-
"""
EKOS EK Inverter Modbus Register Map
Protocol: ekos_offline_test
Function Code: FC03  |  MPPT: 4  |  Strings: 8
IV Scan: No  |  DER-AVM: Yes  |  DEA-AVM Monitor: Yes

Auto-generated by UDP RTU Model Maker v1.3.0 - Stage 3 Pipeline
Date: 2026-03-29 02:37:09

Stage 3 source: ekos_stage2_offline.xlsx
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

class RegisterMap:
    """EKOS EK Modbus Register Map"""

    # ------------------------------------------------------------
    # control
    # ------------------------------------------------------------
    DEA_L1_CURRENT_HIGH                                = 0x03E9   # S16
    DEA_L2_CURRENT_LOW                                 = 0x03EA   # S16

    # ------------------------------------------------------------
    # realtime_data
    # ------------------------------------------------------------
    MODEL_CODE                                         = 0x7531   # S16
    SERIAL_NUMBER                                      = 0x7539   # S16
    INVERTER_ON_OFF                                    = 0x7541   # S16
    INVERTER_STATUS                                    = 0x7542   # S16
    CURRENT_TIME_YEAR                                  = 0x7543   # S16
    CURRENT_TIME_MONTH                                 = 0x7544   # S16
    T_CURRENT                                          = 0x7545   # S16
    DEA_L3_CURRENT_HIGH                                = 0x7546   # S16
    CURRENT_TIME_MINUTE                                = 0x7547   # S16
    CURRENT_TIME_SECOND                                = 0x7548   # S16
    SYSTEM_STATUS                                      = 0x7549   # S16

    # ------------------------------------------------------------
    # fault
    # ------------------------------------------------------------
    ERROR_CODE1                                        = 0x754C   # S16
    ERROR_CODE2                                        = 0x754D   # S16
    TODAY_GENERATION_DURATION_INVERTER_NORMAL_RUNNING_DURATION = 0x754E   # S16
    TOTAL_GENERATION_TIME_HIGH                         = 0x754F   # S16
    TODAY_LATEST_STOP_TIME_HOUR_MIN                    = 0x7550   # S16
    TOTAL_GENERATION_TIME_LOW                          = 0x7551   # U32
    PV_VOLTAGE                                         = 0x7553   # Float32
    INV_R_VOLTAGE                                      = 0x7555   # Float32
    PV_CURRENT                                         = 0x7557   # Float32
    PV_POWER                                           = 0x7559   # Float32
    S_VOLTAGE                                          = 0x755B   # Float32
    ACTIVE_POWER                                       = 0x755F   # Float32
    MPPT3_POWER_LOW                                    = 0x7561   # Float32
    POWER_FACTOR                                       = 0x7563   # Float32
    FREQUENCY                                          = 0x7565   # Float32
    TODAY_ENERGY                                       = 0x7567   # Float32
    TOTAL_ENERGY                                       = 0x7569   # Float32
    L1_VOLTAGE                                         = 0x756B   # Float32
    L2_VOLTAGE                                         = 0x756D   # Float32
    L3_VOLTAGE                                         = 0x003E   # Float32
    L1_CURRENT                                         = 0x7571   # Float32
    L2_CURRENT                                         = 0x7573   # Float32
    L3_CURRENT                                         = 0x7575   # Float32
    REACTIVE_POWER                                     = 0x757D   # Float32
    MPPT3_VOLTAGE                                      = 0x7589   # Float32
    KO_TEMPERATURE_INVERTER_INTERNAL_TEMPERATURE       = 0x758B   # Float32
    S_POWER_LOW                                        = 0x758F   # U32
    PV_STATUS_TOTAL_SUM                                = 0x7593   # S16
    PV1_STATUS_TOTAL                                   = 0x7594   # S16
    PV2_STATUS_TOTAL                                   = 0x7595   # S16
    GRID_STANDARD                                      = 0x7597   # S16
    PV1_VOLTAGE                                        = 0x7599   # Float32
    PV1_CURRENT                                        = 0x759B   # Float32
    PV1_POWER                                          = 0x759D   # Float32
    PV2_VOLTAGE                                        = 0x759F   # Float32
    PV2_CURRENT                                        = 0x75A1   # Float32
    PV2_POWER                                          = 0x7599   # Float32
    AD_CH1_SOLAR_IRRADIANCE_HORIZONTAL                 = 0x75A5   # S16
    AD_CH2_SOLAR_IRRADIANCE_INCLINED                   = 0x75A6   # S16
    AD_CH3_TEMPERATURE_OUTDOOR                         = 0x75A7   # S16
    AD_CH4_TEMPERATURE_KO                              = 0x75A8   # S16
    CH1_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_1_CURRENT = 0x75A9   # S16
    CH2_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_2_CURRENT = 0x75AA   # S16
    CH3_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_3_CURRENT = 0x75AB   # S16
    CH4_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_4_CURRENT = 0x75AC   # S16
    KO                                                 = 0x75AD   # U16

    # ------------------------------------------------------------
    # write_reg
    # ------------------------------------------------------------
    UINT16                                             = 0xA412   # S16

    # ------------------------------------------------------------
    # DER-AVM Control
    # ------------------------------------------------------------
    DER_POWER_FACTOR_SET                               = 0x07D0   # Power factor setpoint [-1000,-800],[800,1000]
    DER_ACTION_MODE                                    = 0x07D1   # Action mode: 0=Self, 2=DER-AVM, 5=Q(V)
    DER_REACTIVE_POWER_PCT                             = 0x07D2   # Reactive power % [-484,484]
    DER_ACTIVE_POWER_PCT                               = 0x07D3   # Active power % [0,1100]
    INVERTER_ON_OFF                                    = 0x0834   # On/Off control: 0=ON, 1=OFF
    CLEAR_PV_INSULATION_WARNING                        = 0x0835   # Clear PV insulation warning: 1=Clear
    INVERTER_CONTROL                                   = 0x6001   # Inverter control: 0=Power on, 1=Shut down
    IV_CURVE_SCAN                                      = 0x600D   # IV curve scan: W 0=Stop,1=Start; R 0=Idle,1=Running,2=Finished
    POWER_FACTOR_DYNAMIC                               = 0x600F   # Dynamic power factor control
    REACTIVE_POWER_DYNAMIC                             = 0x6010   # Dynamic reactive power control (%)
    POWER_DERATING_PCT                                 = 0x3005   # Active power derating [0-110]%

    # ------------------------------------------------------------
    # DEA-AVM Monitor
    # ------------------------------------------------------------
    DEA_L1_CURRENT_LOW                                 = 0x03E8   # DEA L1 current (low word)
    DEA_L2_CURRENT_HIGH                                = 0x03EB   # DEA L2 current (high word)
    DEA_L3_CURRENT_LOW                                 = 0x03EC   # DEA L3 current (low word)
    DEA_L1_VOLTAGE_LOW                                 = 0x03EE   # DEA L1 voltage (low word)
    DEA_L1_VOLTAGE_HIGH                                = 0x03EF   # DEA L1 voltage (high word)
    DEA_L2_VOLTAGE_LOW                                 = 0x03F0   # DEA L2 voltage (low word)
    DEA_L2_VOLTAGE_HIGH                                = 0x03F1   # DEA L2 voltage (high word)
    DEA_L3_VOLTAGE_LOW                                 = 0x03F2   # DEA L3 voltage (low word)
    DEA_L3_VOLTAGE_HIGH                                = 0x03F3   # DEA L3 voltage (high word)
    DEA_TOTAL_ACTIVE_POWER_LOW                         = 0x03F4   # DEA total active power (low word)
    DEA_TOTAL_ACTIVE_POWER_HIGH                        = 0x03F5   # DEA total active power (high word)
    DEA_TOTAL_REACTIVE_POWER_LOW                       = 0x03F6   # DEA total reactive power (low word)
    DEA_TOTAL_REACTIVE_POWER_HIGH                      = 0x03F7   # DEA total reactive power (high word)
    DEA_POWER_FACTOR_LOW                               = 0x03F8   # DEA power factor (low word)
    DEA_POWER_FACTOR_HIGH                              = 0x03F9   # DEA power factor (high word)
    DEA_FREQUENCY_LOW                                  = 0x03FA   # DEA frequency (low word)
    DEA_FREQUENCY_HIGH                                 = 0x03FB   # DEA frequency (high word)
    DEA_STATUS_FLAG_LOW                                = 0x03FC   # DEA status flag (low word)
    DEA_STATUS_FLAG_HIGH                               = 0x03FD   # DEA status flag (high word)

    # DER-AVM aliases (backward compatibility)
    POWER_FACTOR_SET   = DER_POWER_FACTOR_SET
    OPERATION_MODE     = DER_ACTION_MODE
    REACTIVE_POWER_PCT = DER_REACTIVE_POWER_PCT
    ACTIVE_POWER_PCT   = DER_ACTIVE_POWER_PCT
    ON_OFF_CONTROL     = INVERTER_ON_OFF

    # Compatibility aliases (auto-generated)
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    S_PHASE_VOLTAGE                          = L2_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT
    TOTAL_ENERGY_LOW                         = TOTAL_ENERGY
    TODAY_ENERGY_LOW                         = TODAY_ENERGY
    MPPT1_VOLTAGE                            = PV1_VOLTAGE
    MPPT1_CURRENT                            = PV1_CURRENT
    INVERTER_MODE                            = INVERTER_STATUS
    PV_TOTAL_INPUT_POWER_LOW                 = PV_POWER
    GRID_TOTAL_ACTIVE_POWER_LOW              = ACTIVE_POWER


SCALE = {
    'voltage':      0.1,
    'current':      0.01,
    'power':        0.1,
    'frequency':    0.01,
    'power_factor': 0.001,
    'dea_current':          0.1,
    'dea_voltage':          0.1,
    'dea_active_power':     0.1,
    'dea_reactive_power':   1,
    'dea_frequency':        0.1,
}

DATA_TYPES = {
    'DEA_L1_CURRENT_HIGH': 'S16',
    'DEA_L2_CURRENT_LOW': 'S16',
    'MODEL_CODE': 'S16',
    'SERIAL_NUMBER': 'S16',
    'INVERTER_ON_OFF': 'S16',
    'INVERTER_STATUS': 'S16',
    'CURRENT_TIME_YEAR': 'S16',
    'CURRENT_TIME_MONTH': 'S16',
    'T_CURRENT': 'S16',
    'DEA_L3_CURRENT_HIGH': 'S16',
    'CURRENT_TIME_MINUTE': 'S16',
    'CURRENT_TIME_SECOND': 'S16',
    'SYSTEM_STATUS': 'S16',
    'ERROR_CODE1': 'S16',
    'ERROR_CODE2': 'S16',
    'TODAY_GENERATION_DURATION_INVERTER_NORMAL_RUNNING_DURATION': 'S16',
    'TOTAL_GENERATION_TIME_HIGH': 'S16',
    'TODAY_LATEST_STOP_TIME_HOUR_MIN': 'S16',
    'TOTAL_GENERATION_TIME_LOW': 'U32',
    'S_POWER_LOW': 'U32',
    'PV_STATUS_TOTAL_SUM': 'S16',
    'PV1_STATUS_TOTAL': 'S16',
    'PV2_STATUS_TOTAL': 'S16',
    'GRID_STANDARD': 'S16',
    'AD_CH1_SOLAR_IRRADIANCE_HORIZONTAL': 'S16',
    'AD_CH2_SOLAR_IRRADIANCE_INCLINED': 'S16',
    'AD_CH3_TEMPERATURE_OUTDOOR': 'S16',
    'AD_CH4_TEMPERATURE_KO': 'S16',
    'CH1_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_1_CURRENT': 'S16',
    'CH2_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_2_CURRENT': 'S16',
    'CH3_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_3_CURRENT': 'S16',
    'CH4_CURRENT_INTEGRATED_JUNCTION_BOX_CHANNEL_4_CURRENT': 'S16',
    'KO': 'U16',
    'UINT16': 'S16',
    'DER_POWER_FACTOR_SET': 'S16',
    'DER_ACTION_MODE': 'U16',
    'DER_REACTIVE_POWER_PCT': 'S16',
    'DER_ACTIVE_POWER_PCT': 'U16',
    'INVERTER_ON_OFF': 'U16',
    'CLEAR_PV_INSULATION_WARNING': 'U16',
    'INVERTER_CONTROL': 'U16',
    'IV_CURVE_SCAN': 'U16',
    'POWER_FACTOR_DYNAMIC': 'S16',
    'REACTIVE_POWER_DYNAMIC': 'S16',
    'POWER_DERATING_PCT': 'U16',
    'DEA_L1_CURRENT_LOW': 'S32',
    'DEA_L2_CURRENT_HIGH': 'S32',
    'DEA_L3_CURRENT_LOW': 'S32',
    'DEA_L1_VOLTAGE_LOW': 'S32',
    'DEA_L1_VOLTAGE_HIGH': 'S32',
    'DEA_L2_VOLTAGE_LOW': 'S32',
    'DEA_L2_VOLTAGE_HIGH': 'S32',
    'DEA_L3_VOLTAGE_LOW': 'S32',
    'DEA_L3_VOLTAGE_HIGH': 'S32',
    'DEA_TOTAL_ACTIVE_POWER_LOW': 'S32',
    'DEA_TOTAL_ACTIVE_POWER_HIGH': 'S32',
    'DEA_TOTAL_REACTIVE_POWER_LOW': 'S32',
    'DEA_TOTAL_REACTIVE_POWER_HIGH': 'S32',
    'DEA_POWER_FACTOR_LOW': 'S32',
    'DEA_POWER_FACTOR_HIGH': 'S32',
    'DEA_FREQUENCY_LOW': 'S32',
    'DEA_FREQUENCY_HIGH': 'S32',
    'DEA_STATUS_FLAG_LOW': 'S32',
    'DEA_STATUS_FLAG_HIGH': 'S32',
}

class InverterMode:
    """Inverter operating mode codes (register 0x101D)."""
    INITIAL  = 0x00  # Initial mode
    STANDBY  = 0x01  # Standby mode
    ON_GRID  = 0x03  # On-Grid mode (grid-connected)
    OFF_GRID = 0x04  # Off-Grid mode (island)
    FAULT    = 0x05  # Fault mode
    SHUTDOWN = 0x09  # Shutdown mode

    _MAP = {
        0x00: 'Initial',
        0x01: 'Standby',
        0x03: 'On-Grid',
        0x04: 'Off-Grid',
        0x05: 'Fault',
        0x09: 'Shutdown',
    }

    @classmethod
    def to_string(cls, value):
        return cls._MAP.get(int(value) if value is not None else -1,
                            f'Unknown({value})')

class StatusConverter:
    """Convert raw inverter status code to InverterMode."""

    _RAW_TO_MODE = {
        0: 0,  # INITIAL
        1: 1,  # STANDBY
        3: 3,  # ON_GRID
        4: 3,  # ON_GRID
        5: 5,  # FAULT
        9: 9,  # SHUTDOWN
    }

    @classmethod
    def to_inverter_mode(cls, raw_value):
        if raw_value is None:
            return InverterMode.FAULT
        mapped = cls._RAW_TO_MODE.get(int(raw_value), -1)
        if mapped >= 0:
            return mapped
        # Fallback: pass-through for known Solarize mode codes
        v = int(raw_value)
        return v if v in (0x00, 0x01, 0x03, 0x04, 0x05, 0x09) else InverterMode.FAULT

def registers_to_u32(low, high):
    """Combine two U16 registers (low-word, high-word) into U32."""
    return ((int(high) & 0xFFFF) << 16) | (int(low) & 0xFFFF)

def registers_to_s32(low, high):
    """Combine two U16 registers (low-word, high-word) into signed S32."""
    u = registers_to_u32(low, high)
    return u - 0x100000000 if u >= 0x80000000 else u

def get_mppt_registers(mppt_index):
    """Return (voltage_addr, current_addr, power_low_addr, power_high_addr) for MPPT channel."""
    if not (1 <= mppt_index <= 4):
        raise ValueError(f'MPPT index {mppt_index} out of range [1, 4]')
    r = RegisterMap
    v_name  = f'MPPT{mppt_index}_VOLTAGE'
    i_name  = f'MPPT{mppt_index}_CURRENT'
    pl_name = f'MPPT{mppt_index}_POWER_LOW'
    ph_name = f'MPPT{mppt_index}_POWER_HIGH'
    return (
        getattr(r, v_name,  None),
        getattr(r, i_name,  None),
        getattr(r, pl_name, None),
        getattr(r, ph_name, None),
    )

def get_string_registers(string_index):
    """Return (voltage_addr, current_addr) for PV string channel."""
    if not (1 <= string_index <= 8):
        raise ValueError(f'String index {string_index} out of range [1, 8]')
    r = RegisterMap
    v_name = f'STRING{string_index}_VOLTAGE'
    i_name = f'STRING{string_index}_CURRENT'
    return (
        getattr(r, v_name, None),
        getattr(r, i_name, None),
    )

