# -*- coding: utf-8 -*-
"""
Growatt Inverter Modbus Register Map
Based on Growatt Modbus Protocol 
Protocol Name: growatt
MPPT: 8 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-06
"""



class RegisterMap:
    """Growatt Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    POWER_FACTOR                             = 0x0000  # U16
    L1_VOLTAGE                               = 0x000E  # U16, scale V 0.1
    FW_VERSION2L                             = 0x000E  # U16
    VPV4                                     = 0x000F  # U16, scale A 0.1
    PV4CURR                                  = 0x0010  # U16, scale VA 0.1
    PV_POWER                                 = 0x0011  # U16, scale VA 0.1
    VPV_START                                = 0x0011  # U16, scale V 0.1
    L2_VOLTAGE                               = 0x0012  # U16, scale V 0.1
    TIME_START                               = 0x0012  # U16
    L2_CURRENT                               = 0x0013  # U16, scale A 0.1
    V3_00                                    = 0x0013  # U16
    VAC_LOW                                  = 0x0013  # U16, scale V 0.1
    SERIAL_NO_5                              = 0x0017  # U16
    SERIAL_NO_3                              = 0x0019  # U16, scale VA 0.1
    SERIAL_NO_2                              = 0x001A  # U16, scale KWH 0.1
    SERIAL_NO_1                              = 0x001B  # U16, scale KWH 0.1
    VPV8                                     = 0x001F  # U16
    P_BUS_VOLTAGE                            = 0x002A  # U16, scale V 0.1
    DAILY_ENERGY                             = 0x0036  # U16
    MANUFACTURER_INFO_8                      = 0x003B  # U16
    MANUFACTURER_INFO_6                      = 0x003D  # U16
    MANUFACTURER_INFO_5                      = 0x003E  # U16
    MANUFACTURER_INFO3                       = 0x0040  # U16
    WARNING_VALUE1                           = 0x0041  # U16
    MANUFACTURER_INFO_2                      = 0x0041  # U16
    MANUFACTURER_INFO_1                      = 0x0042  # U16
    MODEL_SELECTED                           = 0x004A  # U16, scale V 0.1
    CURR_STRING5                             = 0x004F  # U16, scale A 0.1
    PFMODEL                                  = 0x0063  # U16
    GTSET_MODEL                              = 0x008B  # U16, scale V 0.1
    REAL_VALUE                               = 0x008D  # U16, scale V 0.1
    DCISHIFT                                 = 0x008D  # U16
    BLANECE_MODEL                            = 0x009A  # U16
    TRAKER_MODEL                             = 0x00A3  # U16
    PV1_OR_PV2_BOOST_DRIVER_BROKEN           = 0x0200  # U16
    BUS_VOLTAGE_ERROR                        = 0x400000  # U16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    PPV_H                                    = 0x0001  # U16, scale W 0.1
    V1_00                                    = 0x0001  # U16
    SPIENABLE                                = 0x0001  # U16
    PPV_L                                    = 0x0002  # U16, scale W 0.1
    V1_10                                    = 0x0002  # U16
    PF_CMDMEMORYSTATE                        = 0x0002  # U16
    VPV1                                     = 0x0003  # U16, scale V 0.1
    PV1CURR                                  = 0x0004  # U16, scale A 0.1
    PV1WATT_H                                = 0x0005  # U16, scale W 0.1
    PV1WATT_L                                = 0x0006  # U16, scale W 0.1
    VPV2                                     = 0x0007  # U16, scale V 0.1
    PV2WATT_H                                = 0x0009  # U16, scale W 0.1
    PV2WATT_L                                = 0x000A  # U16, scale W 0.1
    FW_VERSION_L                             = 0x000B  # U16, scale W 0.1
    PV3CURR                                  = 0x000C  # U16, scale W 0.1
    L3_VOLTAGE                               = 0x0016  # U16, scale V 0.1
    CUMULATIVE_ENERGY                        = 0x001C  # U16, scale KWH 0.1
    TEMPERATURE                              = 0x0020  # U16
    V3_13                                    = 0x0020  # U16
    RESET_USER                               = 0x0020  # U16
    DCI_FAULT_VALUE                          = 0x0023  # U16, scale A 0.01
    VAC_LOW_2                                = 0x0023  # U16, scale V 0.1
    VAC_FAULT_VALUE                          = 0x0025  # U16, scale V 0.1
    FAC_LOW_2                                = 0x0025  # U16, scale Hz 0.01
    PV_VOLTAGE                               = 0x0026  # U16, scale Hz 0.01
    L1_CURRENT                               = 0x0027  # U16
    IPM_TEMPERATURE                          = 0x0029  # U16
    N_BUS_VOLTAGE                            = 0x002B  # U16, scale V 0.1
    RESET_CHK                                = 0x002E  # U16
    L3_CURRENT                               = 0x002F  # U16
    VAC_LOW2TIME                             = 0x0035  # U16, scale kWh 0.1
    REACTIVE_POWER                           = 0x0046  # U16, scale V 0.1
    MPPT3_CURRENT                            = 0x0047  # U16, scale A 0.1
    VAC_START_BYPF                           = 0x0055  # U16, scale A 0.1
    GRID_FAULT_RECORD2_MIN_SEC               = 0x0062  # U16
    LCMDTEST                                 = 0x0062  # U16
    GRID_FAULT_RECORD3_DAY_HOUR              = 0x0066  # U16
    GRID_FAULT_RECORD3_MIN_SEC               = 0x0067  # U16
    GRID_FAULT_RECORD5_DAY_HOUR              = 0x0070  # U16
    GRID_FAULT_RECORD5_MIN_SEC               = 0x0071  # U16
    B_INVALL_FAULT_CODE                      = 0x0073  # U16, scale V 0.1
    PID_STATUS                               = 0x0075  # U16
    AC_POWER                                 = 0x0076  # U16, scale V 0.1
    PV3_VOLTAGE                              = 0x0078  # U16
    PV3_CURRENT                              = 0x0079  # U16
    PV3WATT_H                                = 0x007A  # U16
    PV3WATT_L                                = 0x007B  # U16
    PID_PV1_VOLTAGE                          = 0x007D  # U16
    PID_PV1_CURRENT                          = 0x007E  # U16
    PID_PV2_VOLTAGE                          = 0x007F  # U16
    PID_PV3_VOLTAGE                          = 0x0081  # U16
    PID_PV3_CURRENT                          = 0x0082  # U16
    PID_PV4_VOLTAGE                          = 0x0083  # U16, scale % 0.1
    PID_PV4_CURRENT                          = 0x0084  # U16, scale V 0.1
    ISLAND_DISABLE                           = 0x0090  # U16
    PV1VOLT_SET                              = 0x00AC  # U16
    PV2VOLT_SET                              = 0x00AD  # U16
    INVERTER_ERRORRECORD_2_VALUE             = 0x00BD  # U16
    FAC_HIGH_3                               = 0x00BD  # U16
    PV1_OR_PV2_CIRCUIT_SHORT                 = 0x0100  # U16
    DEBUG_RESAVED                            = 0x02A2  # U16
    FAULT_INFO_0                             = 0x02A3  # U16

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    STR_FAULT                                = 0x0056  # U16
    PF_OF_VACLIMIT                           = 0x0056  # U16
    PIDFAULT_CODE                            = 0x0059  # U16
    PID_VOLT_OPTION                          = 0x0059  # U16
    GRID_FAULT_RECORD1_YEAR_MONTH            = 0x005B  # U16
    GRID_FAULT_RECORD1_MIN_SEC               = 0x005D  # U16
    PFLINE_P2_P_F                            = 0x005D  # U16
    GRID_FAULT_RECORD1_VALUE                 = 0x005E  # U16
    PFLINE_P3_L_P                            = 0x005E  # U16
    E_DAY1_H                                 = 0x01F4  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    FREQUENCY                                = 0x000D  # U16, scale Hz 0.01
    V3_14                                    = 0x0021  # U16, scale V 0.1
    VPV_FAULT_VALUE                          = 0x0024  # U16, scale V 0.1
    FAULT_CODE                               = 0x0028  # U16
    VAC_HIGH_C                               = 0x0028  # U16, scale V 0.1
    VAC_LOW1TIME                             = 0x0033  # U16, scale kWh 0.1
    ERROR_CODE1                              = 0x003C  # U16
    ERROR_CODE2                              = 0x003F  # U16
    GRID_FAULT_RECORD1_CODE                  = 0x005A  # U16
    GRID_FAULT_RECORD1_DAY_HOUR              = 0x005C  # U16
    GRID_FAULT_RECORD2_CODE                  = 0x005F  # U16
    GRID_FAULT_RECORD2_DAY_HOUR              = 0x0061  # U16
    GRID_FAULT_RECORD3_CODE                  = 0x0064  # U16
    GRID_FAULT_RECORD5_CODE                  = 0x006E  # U16
    GRID_FAULT_RECORD5_YEAR_MONTH            = 0x006F  # U16
    PID_PV2_CURRENT                          = 0x0080  # U16
    QVRPDELAY_TIME_EE                        = 0x00A5  # U16
    INVERTER_ERRORRECORD_1_DAYHOUR           = 0x00B6  # U16
    INVERTER_ERRORRECORD_1_MIN               = 0x00B7  # U16
    PV_VOLTAGE_HIGH_FAULT                    = 0x00B7  # U16, scale V 0.1
    INVERTER_ERRORRECORD_2_YEARMONTH         = 0x00BA  # U16
    INVERTER_ERRORRECORD_2_DAYHOUR           = 0x00BB  # U16
    INVERTER_ERRORRECORD_2_MINSEC            = 0x00BC  # U16
    INVERTER_ERRORRECORD_2_CODE              = 0x00BE  # U16
    FAULT_INFO_31                            = 0x02C2  # U16
    ALARM_INFO_0                             = 0x02D0  # U16
    ALARM_INFO_1                             = 0x02D1  # U16
    ALARM_INFO_31                            = 0x02EF  # U16
    AFCI_FAULT                               = 0x1000  # U16
    AFCI_MODULE_FAULT                        = 0x4000  # U16
    RELAY_CHECK_FAULT                        = 0x20000  # U16
    COMMUNICATION_ERROR                      = 0x200000  # U16

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # L2 없음 → 대체

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_STRING_COUNT                          = 8

    # --- RTU modbus_handler / simulator 필수 alias ---
    INNER_TEMP                               = TEMPERATURE
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    ERROR_CODE3                              = V3_14
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834



    # IV Scan block layout
    IV_TRACKER_BLOCK_SIZE             = 0x0100  # 256 regs per tracker
    IV_SCAN_DATA_POINTS              = 64      # default data points


class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x000D) — Bit field"""
    BITS = {
        0:  "Inverter over dc-bias current",
        1:  "Inverter relay abnormal",
        2:  "Remote off",
        3:  "Inverter over temperature",
        4:  "GFCI abnormal",
        5:  "PV string reverse",
        6:  "System type error",
        7:  "Fan abnormal",
        8:  "Dc-link unbalance or under voltage",
        9:  "Dc-link over voltage",
        10:  "Internal communication error",
        11:  "Software incompatibility",
        12:  "Internal storage error",
        13:  "Data inconsistency",
        14:  "Inverter abnormal",
        15:  "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x000D) — Bit field"""
    BITS = {
        0:  "Grid over voltage",
        1:  "Grid under voltage",
        2:  "Grid absent",
        3:  "Grid over frequency",
        4:  "Grid under frequency",
        5:  "PV over voltage",
        6:  "PV insulation abnormal",
        7:  "Leakage current abnormal",
        8:  "Inverter in power limit state",
        9:  "Internal power supply abnormal",
        10:  "PV string abnormal",
        11:  "PV under voltage",
        12:  "PV irradiation weak",
        13:  "Grid abnormal",
        14:  "Arc fault detection",
        15:  "AC moving average voltage high",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x0021) — Bit field"""
    BITS = {
        0:  "Reserved",
        1:  "Logger/E-Display EEPROM fail",
        2:  "Reserved",
        3:  "Single tracker detect warning",
        4:  "AFCI lost",
        5:  "Data logger lost",
        6:  "Meter lost",
        7:  "Inverter lost",
        8:  "Grid N abnormal",
        9:  "Surge Protection Devices (SPD) defective",
        10:  "Parallel ID warning",
        11:  "Parallel SYN signal warning",
        12:  "Parallel BAT abnormal",
        13:  "Parallel GRID abnormal",
        14:  "Generator voltage abnormal",
        15:  "Reserved",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x0021) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x0024) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x0028) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x0028) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x0033) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x0033) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode10:
    """Error Code Table10 (0x003C) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode11:
    """Error Code Table11 (0x003F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode12:
    """Error Code Table12 (0x005A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode13:
    """Error Code Table13 (0x005C) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode14:
    """Error Code Table14 (0x005F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode15:
    """Error Code Table15 (0x0061) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode16:
    """Error Code Table16 (0x0064) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode17:
    """Error Code Table17 (0x006E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode18:
    """Error Code Table18 (0x006F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode19:
    """Error Code Table19 (0x0080) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode20:
    """Error Code Table20 (0x00A5) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode21:
    """Error Code Table21 (0x00B6) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode22:
    """Error Code Table22 (0x00B7) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode23:
    """Error Code Table23 (0x00B7) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode24:
    """Error Code Table24 (0x00BA) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode25:
    """Error Code Table25 (0x00BB) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode26:
    """Error Code Table26 (0x00BC) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode27:
    """Error Code Table27 (0x00BE) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode28:
    """Error Code Table28 (0x02C2) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode29:
    """Error Code Table29 (0x02D0) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode30:
    """Error Code Table30 (0x02D1) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode31:
    """Error Code Table31 (0x02EF) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode32:
    """Error Code Table32 (0x1000) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode33:
    """Error Code Table33 (0x4000) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode34:
    """Error Code Table34 (0x20000) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode35:
    """Error Code Table35 (0x200000) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class GrowattStatusConverter:
    """Growatt INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = GrowattStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 8
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-8).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 8:
        raise ValueError(f"MPPT number must be 1-8, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-8)."""
    if tracker_num < 1 or tracker_num > 8:
        raise ValueError(f"Tracker number must be 1-8, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 8:
        raise ValueError(f"MPPT number must be 1-8, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'POWER_FACTOR': 'U16',
    'PPV_H': 'U16',
    'V1_00': 'U16',
    'SPIENABLE': 'U16',
    'PPV_L': 'U16',
    'V1_10': 'U16',
    'PF_CMDMEMORYSTATE': 'U16',
    'VPV1': 'U16',
    'PV1CURR': 'U16',
    'PV1WATT_H': 'U16',
    'PV1WATT_L': 'U16',
    'VPV2': 'U16',
    'PV2WATT_H': 'U16',
    'PV2WATT_L': 'U16',
    'FW_VERSION_L': 'U16',
    'PV3CURR': 'U16',
    'FREQUENCY': 'U16',
    'L1_VOLTAGE': 'U16',
    'FW_VERSION2L': 'U16',
    'VPV4': 'U16',
    'PV4CURR': 'U16',
    'PV_POWER': 'U16',
    'VPV_START': 'U16',
    'L2_VOLTAGE': 'U16',
    'TIME_START': 'U16',
    'L2_CURRENT': 'U16',
    'V3_00': 'U16',
    'VAC_LOW': 'U16',
    'L3_VOLTAGE': 'U16',
    'SERIAL_NO_5': 'U16',
    'SERIAL_NO_3': 'U16',
    'SERIAL_NO_2': 'U16',
    'SERIAL_NO_1': 'U16',
    'CUMULATIVE_ENERGY': 'U16',
    'VPV8': 'U16',
    'TEMPERATURE': 'U16',
    'V3_13': 'U16',
    'RESET_USER': 'U16',
    'V3_14': 'U16',
    'DCI_FAULT_VALUE': 'U16',
    'VAC_LOW_2': 'U16',
    'VPV_FAULT_VALUE': 'U16',
    'VAC_FAULT_VALUE': 'U16',
    'FAC_LOW_2': 'U16',
    'PV_VOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'FAULT_CODE': 'U16',
    'VAC_HIGH_C': 'U16',
    'IPM_TEMPERATURE': 'U16',
    'P_BUS_VOLTAGE': 'U16',
    'N_BUS_VOLTAGE': 'U16',
    'RESET_CHK': 'U16',
    'L3_CURRENT': 'U16',
    'VAC_LOW1TIME': 'U16',
    'VAC_LOW2TIME': 'U16',
    'DAILY_ENERGY': 'U16',
    'MANUFACTURER_INFO_8': 'U16',
    'ERROR_CODE1': 'U16',
    'MANUFACTURER_INFO_6': 'U16',
    'MANUFACTURER_INFO_5': 'U16',
    'ERROR_CODE2': 'U16',
    'MANUFACTURER_INFO3': 'U16',
    'WARNING_VALUE1': 'U16',
    'MANUFACTURER_INFO_2': 'U16',
    'MANUFACTURER_INFO_1': 'U16',
    'REACTIVE_POWER': 'U16',
    'MPPT3_CURRENT': 'U16',
    'MODEL_SELECTED': 'U16',
    'CURR_STRING5': 'U16',
    'VAC_START_BYPF': 'U16',
    'STR_FAULT': 'U16',
    'PF_OF_VACLIMIT': 'U16',
    'PIDFAULT_CODE': 'U16',
    'PID_VOLT_OPTION': 'U16',
    'GRID_FAULT_RECORD1_CODE': 'U16',
    'GRID_FAULT_RECORD1_YEAR_MONTH': 'U16',
    'GRID_FAULT_RECORD1_DAY_HOUR': 'U16',
    'GRID_FAULT_RECORD1_MIN_SEC': 'U16',
    'PFLINE_P2_P_F': 'U16',
    'GRID_FAULT_RECORD1_VALUE': 'U16',
    'PFLINE_P3_L_P': 'U16',
    'GRID_FAULT_RECORD2_CODE': 'U16',
    'GRID_FAULT_RECORD2_DAY_HOUR': 'U16',
    'GRID_FAULT_RECORD2_MIN_SEC': 'U16',
    'LCMDTEST': 'U16',
    'PFMODEL': 'U16',
    'GRID_FAULT_RECORD3_CODE': 'U16',
    'GRID_FAULT_RECORD3_DAY_HOUR': 'U16',
    'GRID_FAULT_RECORD3_MIN_SEC': 'U16',
    'GRID_FAULT_RECORD5_CODE': 'U16',
    'GRID_FAULT_RECORD5_YEAR_MONTH': 'U16',
    'GRID_FAULT_RECORD5_DAY_HOUR': 'U16',
    'GRID_FAULT_RECORD5_MIN_SEC': 'U16',
    'B_INVALL_FAULT_CODE': 'U16',
    'PID_STATUS': 'U16',
    'AC_POWER': 'U16',
    'PV3_VOLTAGE': 'U16',
    'PV3_CURRENT': 'U16',
    'PV3WATT_H': 'U16',
    'PV3WATT_L': 'U16',
    'PID_PV1_VOLTAGE': 'U16',
    'PID_PV1_CURRENT': 'U16',
    'PID_PV2_VOLTAGE': 'U16',
    'PID_PV2_CURRENT': 'U16',
    'PID_PV3_VOLTAGE': 'U16',
    'PID_PV3_CURRENT': 'U16',
    'PID_PV4_VOLTAGE': 'U16',
    'PID_PV4_CURRENT': 'U16',
    'GTSET_MODEL': 'U16',
    'REAL_VALUE': 'U16',
    'DCISHIFT': 'U16',
    'ISLAND_DISABLE': 'U16',
    'BLANECE_MODEL': 'U16',
    'TRAKER_MODEL': 'U16',
    'QVRPDELAY_TIME_EE': 'U16',
    'PV1VOLT_SET': 'U16',
    'PV2VOLT_SET': 'U16',
    'INVERTER_ERRORRECORD_1_DAYHOUR': 'U16',
    'INVERTER_ERRORRECORD_1_MIN': 'U16',
    'PV_VOLTAGE_HIGH_FAULT': 'U16',
    'INVERTER_ERRORRECORD_2_YEARMONTH': 'U16',
    'INVERTER_ERRORRECORD_2_DAYHOUR': 'U16',
    'INVERTER_ERRORRECORD_2_MINSEC': 'U16',
    'INVERTER_ERRORRECORD_2_VALUE': 'U16',
    'FAC_HIGH_3': 'U16',
    'INVERTER_ERRORRECORD_2_CODE': 'U16',
    'PV1_OR_PV2_CIRCUIT_SHORT': 'U16',
    'E_DAY1_H': 'U16',
    'PV1_OR_PV2_BOOST_DRIVER_BROKEN': 'U16',
    'DEBUG_RESAVED': 'U16',
    'FAULT_INFO_0': 'U16',
    'FAULT_INFO_31': 'U16',
    'ALARM_INFO_0': 'U16',
    'ALARM_INFO_1': 'U16',
    'ALARM_INFO_31': 'U16',
    'AFCI_FAULT': 'U16',
    'AFCI_MODULE_FAULT': 'U16',
    'RELAY_CHECK_FAULT': 'U16',
    'COMMUNICATION_ERROR': 'U16',
    'BUS_VOLTAGE_ERROR': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0001, 'count': 125, 'fc': 3},
    {'start': 0x007E, 'count':  65, 'fc': 3},
    {'start': 0x0100, 'count':   1, 'fc': 3},
    {'start': 0x01F4, 'count':   1, 'fc': 3},
    {'start': 0x02A2, 'count':  78, 'fc': 3},
    {'start': 0x1000, 'count':   1, 'fc': 3},
    {'start': 0x2710, 'count':   1, 'fc': 3},
    {'start': 0x4000, 'count':   1, 'fc': 3},
    {'start': 0x20000, 'count':   1, 'fc': 3},
    {'start': 0x200000, 'count':   1, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'DEA_L1_VOLTAGE (0x03EE~0x03EF); L1_VOLTAGE (0x0043); GRID_FAULT_RECORD3_DAY_HOUR (0x0066); GRID_FAULT_RECORD5_DAY_HOUR (0x0070)',
    's_voltage           ': 'DEA_L2_VOLTAGE (0x03F0~0x03F1); GRID_FAULT_RECORD3_MIN_SEC (0x0067); GRID_FAULT_RECORD5_MIN_SEC (0x0071)',
    't_voltage           ': 'DEA_L3_VOLTAGE (0x03F2~0x03F3); L3_VOLTAGE (0x0016)',
    'r_current           ': 'DEA_L1_CURRENT (0x03E8~0x03E9); L1_CURRENT (0x0027); B_INVALL_FAULT_CODE (0x0073)',
    's_current           ': 'DEA_L2_CURRENT (0x03EA~0x03EB); IPM_TEMPERATURE (0x0029); N_BUS_VOLTAGE (0x002B); L2_CURRENT (0x002D)',
    't_current           ': 'DEA_L3_CURRENT (0x03EC~0x03ED); L3_CURRENT (0x002F); PID_STATUS (0x0075)',
    'frequency           ': 'DEA_FREQUENCY (0x03FA~0x03FB); PPV_L (0x0002); V1_10 (0x0002); PF_CMDMEMORYSTATE (0x0002); VAC_FAULT_VALUE (0x0025); FAC_LOW_2 (0x0025); FREQUENCY (0x000D)',
    'ac_power            ': 'DEA_TOTAL_ACTIVE_POWER (0x03F4~0x03F5); AC_POWER (0x0076)',
    'cumulative_energy   ': 'CUMULATIVE_ENERGY (0x001C); DCI_FAULT_VALUE (0x0023); VAC_LOW_2 (0x0023); RESET_CHK (0x002E); VAC_LOW2TIME (0x0035); VAC_START_BYPF (0x0055)',
    'alarm1              ': 'FAULT_CODE (0x0028)',
    'mppt1_voltage'        : 'VPV1',
    'mppt1_current'        : 'PV1CURR',
    'mppt2_voltage'        : 'VPV2',
    'mppt2_current'        : 'PID_PV2_CURRENT',
    'mppt3_voltage'        : 'PV3_VOLTAGE',
    'mppt3_current'        : 'PV3CURR',
    'mppt4_voltage'        : 'PID_PV4_VOLTAGE',
    'mppt4_current'        : 'PID_PV4_CURRENT',
    'mppt5_voltage'        : 'MPPT5_VOLTAGE',
    'mppt5_current'        : 'MPPT5_CURRENT',
    'mppt6_voltage'        : 'MPPT6_VOLTAGE',
    'mppt6_current'        : 'MPPT6_CURRENT',
    'mppt7_voltage'        : 'MPPT7_VOLTAGE',
    'mppt7_current'        : 'MPPT7_CURRENT',
    'mppt8_voltage'        : 'MPPT8_VOLTAGE',
    'mppt8_current'        : 'MPPT8_CURRENT',
}
