# -*- coding: utf-8 -*-
"""
Goodwe Inverter Modbus Register Map
Based on Goodwe Modbus Protocol 
Protocol Name: goodwe_test
MPPT: 4 | Strings: 8 (2/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-08
"""



class RegisterMap:
    """Goodwe Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    INNER_TEMP                               = 0x0020  # U16
    DEVICE_SERIAL_NUMBER                     = 0x0200  # STRING, scale 1
    DEVICE_TYPE                              = 0x0210  # STRING, scale 1
    VAC2_L2_PHASEVOLTAGE                     = 0x022B  # U16, scale V 10
    IAC2_L2_PHASECURRENT                     = 0x022E  # U16, scale A 10
    IAC3_L3_PHASECURRENT                     = 0x022F  # U16, scale A 10
    FAC1_L1_PHASEFREQUENCY                   = 0x0230  # U16, scale Hz 100
    FAC2_L2_PHASEFREQUENCY                   = 0x0231  # U16, scale Hz 100
    FAC3_L3_PHASEFREQUENCY                   = 0x0232  # U16, scale Hz 100
    INVERTER_INTERNALTEMPERATURE             = 0x0235  # U16, scale 10
    VAC3_L3_PHASEVOLTAGE                     = 0x0306  # U16, scale V 10
    IAC1_L1_PHASECURRENT                     = 0x0307  # U16, scale A 10
    FIRMWARE_VERSION                         = 0x0316  # U16, scale 1
    BUS_VOLTAGE                              = 0x031C  # U16, scale V 10
    NBUS_VOLTAGE                             = 0x031D  # U16, scale V 10
    MANUFACTURER_IDENTIFIER_FOR_HANNENG      = 0x033E  # U16
    FIRMWARE_VERSION_OF_ARM                  = 0x0354  # U16
    REG_1_INTERNAL_FAN_IS_BLOCKED_BY_SOMETHING_2_FAN_CABLE_ISNOT_CONNECTED_WELL_IN_THE_INVERTER = 0x1000  # U16
    REG_1_INVERTER_STAYS_IN_A_HIGH_TEMPERATURE_ENVIRONMENT_FORLONG_TIME_2_INSTALLING_PLACE_IS_NOT_GOOD_FOR_COOLINGSYSTEM_WORKING = 0x2000  # U16
    REG_1_EXTERNAL_FAN_IS_BLOCKED_BY_SOMETHING_2_FAN_CABLE_ISNOT_CONNECTED_WELL_IN_THE_INVERTER = 0x10000  # U16
    REG_1_SAFETY_COUNTRY_OF_INVERTER_IS_SET_WRONG_2_GRID_VOLTAGEIS_NOT_STABLE_3_AC_TO_GRID_CABLE_TOO_SMALL_OR_TOO_LONG = 0x20000  # U16
    REG_1_THE_GROUND_CABLE_OF_PANELS_IS_NOT_CONNECTED_OR_NOTCONNECTED_WELL_2_DC_CABLE_IS_BROKEN_3_NEUTRAL_GROUND_CABLE_ARE_NOT_CONNECTED_WELL_ON_AC_SIDE_4_THE_ISO_FAILURE_HAPPENS_ON_RAINY_DAYS_OR_EARLY_MORNING_ORSUNSET_WHEN_THE_HUMIDITY_IS_COMPARATIVELY_HEAVY = 0x40000  # U16
    REG_1_CABLE_BETWEEN_CONTROL_BOARD_AND_POWER_BOARD_FOR_DT_IS_NOT_TIGHT_2_NEUTRAL_GROUND_CABLE_ARE_NOTCONNECTED_WELL_ON_AC_SIDE_3_CONTROL_BOARD_PROBLEM = 0x2000000  # U16
    REG_1_SAFETY_COUNTRY_OF_INVERTER_IS_SET_WRONG_2_GRIDFREQUENCY_IS_NOT_STABLE = 0x20000000  # U16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    L2_VOLTAGE                               = 0x0002  # U16, scale V 10
    PV_STRING_COUNT                          = 0x0008  # U16
    AC_POWER                                 = 0x0010  # U16, scale 1
    REG_0_OFF1_ON_INDIA_BOSH_SPECIAL_ARM_SUPPORT = 0x0123  # U16
    HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWERGENERATION = 0x0222  # U16, scale KWH 10
    LOW_BYTE_OF_TOTAL_FEED_POWER_TOGRID_TOTAL_POWERGENERATION = 0x0223  # U16, scale KWH 10
    HIGH_BYTE_OF_TOTAL_FEEDINGHOURS_HOURLYPOWERGENERATION = 0x0224  # U16, scale 1
    LOW_BYTE_OF_TOTAL_FEEDINGHOURS_HOURLYPOWERGENERATION = 0x0225  # U16, scale 1
    VPV1_PPV1INPUT_VOLTAGE                   = 0x0226  # U16, scale V 10
    VPV2_PV2_INPUTVOLTAGE                    = 0x0227  # U16, scale V 10
    IPV1_PV1_INPUTCURRENT                    = 0x0228  # U16, scale A 10
    IPV2_PV2_INPUTCURRENT                    = 0x0229  # U16, scale A 10
    MPPT1_VOLTAGE                            = 0x022A  # U16, scale V 10
    L3_VOLTAGE                               = 0x022C  # U16, scale V 10
    L1_CURRENT                               = 0x022D  # U16, scale A 10
    PV_POWER                                 = 0x0233  # U16, scale W 1
    VPV1_PV1_INPUTVOLTAGE                    = 0x0300  # U16, scale V 10
    L1_VOLTAGE                               = 0x0304  # U16, scale V 10
    L2_CURRENT                               = 0x0308  # U16, scale A 10
    L3_CURRENT                               = 0x0309  # U16, scale A 10
    FREQUENCY                                = 0x030A  # U16, scale Hz 100
    PAC_L_INVERTERCURRENT_OUTPUTPOWER        = 0x030D  # U16, scale W 1
    WORK_MODE                                = 0x030E  # U16, scale 1
    HIGH_BYTE_OF_TOTAL_FEED_POWER_TOGRID_TOTAL_POWERGENERATION = 0x0312  # U16, scale KWH 10
    REG_0X00_NORMAL_MODE                     = 0x0355  # U16
    PAC_H_HIGH_BYTEOF_POWER                  = 0x0356  # U16
    VPV3_PV3_INPUTVOLTAGE                    = 0x0357  # U16
    VPV4_PV4_INPUTVOLTAGE                    = 0x0358  # U16
    IPV3_PV3_INPUTCURRENT                    = 0x0359  # U16
    IPV4_PV4_INPUTCURRENT                    = 0x035A  # U16
    ISTR1_PV_STRING1CURRENT                  = 0x035B  # U16
    ISTR2_PV_STRING2CURRENT                  = 0x035C  # U16
    ISTR3_PV_STRING3CURRENT                  = 0x035D  # U16
    ISTR4_PV_STRING4CURRENT                  = 0x035E  # U16, scale A 10
    ISTR5_PV_STRING5CURRENT                  = 0x035F  # U16, scale A 10
    ISTR6_PV_STRING6CURRENT                  = 0x0360  # U16, scale A 10
    ISTR7_PV_STRING7CURRENT                  = 0x0361  # U16, scale A 10
    ISTR8_PV_STRING8CURRENT                  = 0x0362  # U16, scale A 10
    POWER_FACTOR                             = 0x0376  # U16, scale 1000
    REG_1_PV_STRING_REVERSE_CONNECTION       = 0x400000  # STRINGING

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    SHADOW_MODESWITCH                        = 0x0138  # U16, scale 1
    INVERTER_MODE                            = 0x0234  # U16, scale 1
    FUNCTION_STATUS_BITS                     = 0x0319  # U16, scale A 1
    PIDSPD_STATUS                            = 0x036F  # U16, scale 1

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    WARNING_CODE                             = 0x0317  # U16, scale 1
    REG_1_THE_DEVICE_IS_ABNORMAL             = 0x8000000  # U16

    # =========================================================================
    # DEA-AVM Real-time Data
    # =========================================================================
    DEA_L1_CURRENT_LOW                       = 0x03E8  # S32, scale 0.1, A
    DEA_L1_CURRENT_HIGH                      = 0x03E9
    DEA_L2_CURRENT_LOW                       = 0x03EA  # S32, scale 0.1, A
    DEA_L2_CURRENT_HIGH                      = 0x03EB
    DEA_L3_CURRENT_LOW                       = 0x03EC  # S32, scale 0.1, A
    DEA_L3_CURRENT_HIGH                      = 0x03ED
    DEA_L1_VOLTAGE_LOW                       = 0x03EE  # S32, scale 0.1, V
    DEA_L1_VOLTAGE_HIGH                      = 0x03EF
    DEA_L2_VOLTAGE_LOW                       = 0x03F0  # S32, scale 0.1, V
    DEA_L2_VOLTAGE_HIGH                      = 0x03F1
    DEA_L3_VOLTAGE_LOW                       = 0x03F2  # S32, scale 0.1, V
    DEA_L3_VOLTAGE_HIGH                      = 0x03F3
    DEA_TOTAL_ACTIVE_POWER_LOW               = 0x03F4  # S32, scale 0.1, kW
    DEA_TOTAL_ACTIVE_POWER_HIGH              = 0x03F5
    DEA_TOTAL_REACTIVE_POWER_LOW             = 0x03F6  # S32, scale 1, Var
    DEA_TOTAL_REACTIVE_POWER_HIGH            = 0x03F7
    DEA_POWER_FACTOR_LOW                     = 0x03F8  # S32, scale 0.001
    DEA_POWER_FACTOR_HIGH                    = 0x03F9
    DEA_FREQUENCY_LOW                        = 0x03FA  # S32, scale 0.1, Hz
    DEA_FREQUENCY_HIGH                       = 0x03FB
    DEA_STATUS_FLAG_LOW                      = 0x03FC  # S32, scale 1
    DEA_STATUS_FLAG_HIGH                     = 0x03FD

    # --- H01 표준 alias (h01_field 매칭 결과 직접 사용) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE  # h01_field=r_voltage
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # h01_field=s_voltage
    T_PHASE_VOLTAGE                          = L3_VOLTAGE  # h01_field=t_voltage
    R_PHASE_CURRENT                          = L1_CURRENT  # h01_field=r_current
    S_PHASE_CURRENT                          = L2_CURRENT  # h01_field=s_current
    T_PHASE_CURRENT                          = L3_CURRENT  # h01_field=t_current
    TOTAL_ENERGY                             = HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWERGENERATION  # h01_field=cumulative_energy
    ERROR_CODE1                              = WARNING_CODE  # h01_field=alarm1
    ERROR_CODE2                              = WARNING_CODE  # h01_field=alarm2
    ERROR_CODE3                              = WARNING_CODE  # h01_field=alarm3

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_VOLTAGE                               = MPPT1_VOLTAGE

    # --- RTU modbus_handler / simulator 필수 alias ---
    STRING1_VOLTAGE                          = MPPT1_VOLTAGE  # fallback: STRING1 전압 = MPPT1 전압
    STRING2_VOLTAGE                          = MPPT1_VOLTAGE  # fallback: STRING2 전압 = MPPT1 전압
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834
    MPPT_NUMBER                              = 0x1A4A  # default MPPT count register
    DER_AVM_DIGITAL_METERCONNECT_STATUS      = 0x1210



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x0317) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x8000000) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class GoodweStatusConverter:
    """Goodwe INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw

    @classmethod
    def to_solarize(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)

    @classmethod
    def to_h01(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = GoodweStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 4
STRING_CHANNELS = 8


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-8).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 8:
        raise ValueError(f"String number must be 1-8, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-4).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-4)."""
    if tracker_num < 1 or tracker_num > 4:
        raise ValueError(f"Tracker number must be 1-4, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-2)."""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if string_num < 1 or string_num > 2:
        raise ValueError(f"String number must be 1-2 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=8, strings_per_mppt=2):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'L2_VOLTAGE': 'U16',
    'PV_STRING_COUNT': 'U16',
    'AC_POWER': 'U16',
    'INNER_TEMP': 'U16',
    'REG_0_OFF1_ON_INDIA_BOSH_SPECIAL_ARM_SUPPORT': 'U16',
    'SHADOW_MODESWITCH': 'U16',
    'DEVICE_SERIAL_NUMBER': 'STRING',
    'DEVICE_TYPE': 'STRING',
    'HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWERGENERATION': 'U16',
    'LOW_BYTE_OF_TOTAL_FEED_POWER_TOGRID_TOTAL_POWERGENERATION': 'U16',
    'HIGH_BYTE_OF_TOTAL_FEEDINGHOURS_HOURLYPOWERGENERATION': 'U16',
    'LOW_BYTE_OF_TOTAL_FEEDINGHOURS_HOURLYPOWERGENERATION': 'U16',
    'VPV1_PPV1INPUT_VOLTAGE': 'U16',
    'VPV2_PV2_INPUTVOLTAGE': 'U16',
    'IPV1_PV1_INPUTCURRENT': 'U16',
    'IPV2_PV2_INPUTCURRENT': 'U16',
    'MPPT1_VOLTAGE': 'U16',
    'VAC2_L2_PHASEVOLTAGE': 'U16',
    'L3_VOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'IAC2_L2_PHASECURRENT': 'U16',
    'IAC3_L3_PHASECURRENT': 'U16',
    'FAC1_L1_PHASEFREQUENCY': 'U16',
    'FAC2_L2_PHASEFREQUENCY': 'U16',
    'FAC3_L3_PHASEFREQUENCY': 'U16',
    'PV_POWER': 'U16',
    'INVERTER_MODE': 'U16',
    'INVERTER_INTERNALTEMPERATURE': 'U16',
    'VPV1_PV1_INPUTVOLTAGE': 'U16',
    'L1_VOLTAGE': 'U16',
    'VAC3_L3_PHASEVOLTAGE': 'U16',
    'IAC1_L1_PHASECURRENT': 'U16',
    'L2_CURRENT': 'U16',
    'L3_CURRENT': 'U16',
    'FREQUENCY': 'U16',
    'PAC_L_INVERTERCURRENT_OUTPUTPOWER': 'U16',
    'WORK_MODE': 'U16',
    'HIGH_BYTE_OF_TOTAL_FEED_POWER_TOGRID_TOTAL_POWERGENERATION': 'U16',
    'FIRMWARE_VERSION': 'U16',
    'WARNING_CODE': 'U16',
    'FUNCTION_STATUS_BITS': 'U16',
    'BUS_VOLTAGE': 'U16',
    'NBUS_VOLTAGE': 'U16',
    'MANUFACTURER_IDENTIFIER_FOR_HANNENG': 'U16',
    'FIRMWARE_VERSION_OF_ARM': 'U16',
    'REG_0X00_NORMAL_MODE': 'U16',
    'PAC_H_HIGH_BYTEOF_POWER': 'U16',
    'VPV3_PV3_INPUTVOLTAGE': 'U16',
    'VPV4_PV4_INPUTVOLTAGE': 'U16',
    'IPV3_PV3_INPUTCURRENT': 'U16',
    'IPV4_PV4_INPUTCURRENT': 'U16',
    'ISTR1_PV_STRING1CURRENT': 'U16',
    'ISTR2_PV_STRING2CURRENT': 'U16',
    'ISTR3_PV_STRING3CURRENT': 'U16',
    'ISTR4_PV_STRING4CURRENT': 'U16',
    'ISTR5_PV_STRING5CURRENT': 'U16',
    'ISTR6_PV_STRING6CURRENT': 'U16',
    'ISTR7_PV_STRING7CURRENT': 'U16',
    'ISTR8_PV_STRING8CURRENT': 'U16',
    'PIDSPD_STATUS': 'U16',
    'POWER_FACTOR': 'U16',
    'DEA_L1_CURRENT_LOW': 'S32',
    'DEA_L2_CURRENT_LOW': 'S32',
    'DEA_L3_CURRENT_LOW': 'S32',
    'DEA_L1_VOLTAGE_LOW': 'S32',
    'DEA_L2_VOLTAGE_LOW': 'S32',
    'DEA_L3_VOLTAGE_LOW': 'S32',
    'DEA_TOTAL_ACTIVE_POWER_LOW': 'S32',
    'DEA_TOTAL_REACTIVE_POWER_LOW': 'S32',
    'DEA_POWER_FACTOR_LOW': 'S32',
    'DEA_FREQUENCY_LOW': 'S32',
    'DEA_STATUS_FLAG_LOW': 'S32',
    'REG_1_INTERNAL_FAN_IS_BLOCKED_BY_SOMETHING_2_FAN_CABLE_ISNOT_CONNECTED_WELL_IN_THE_INVERTER': 'U16',
    'REG_1_INVERTER_STAYS_IN_A_HIGH_TEMPERATURE_ENVIRONMENT_FORLONG_TIME_2_INSTALLING_PLACE_IS_NOT_GOOD_FOR_COOLINGSYSTEM_WORKING': 'U16',
    'REG_1_EXTERNAL_FAN_IS_BLOCKED_BY_SOMETHING_2_FAN_CABLE_ISNOT_CONNECTED_WELL_IN_THE_INVERTER': 'U16',
    'REG_1_SAFETY_COUNTRY_OF_INVERTER_IS_SET_WRONG_2_GRID_VOLTAGEIS_NOT_STABLE_3_AC_TO_GRID_CABLE_TOO_SMALL_OR_TOO_LONG': 'U16',
    'REG_1_THE_GROUND_CABLE_OF_PANELS_IS_NOT_CONNECTED_OR_NOTCONNECTED_WELL_2_DC_CABLE_IS_BROKEN_3_NEUTRAL_GROUND_CABLE_ARE_NOT_CONNECTED_WELL_ON_AC_SIDE_4_THE_ISO_FAILURE_HAPPENS_ON_RAINY_DAYS_OR_EARLY_MORNING_ORSUNSET_WHEN_THE_HUMIDITY_IS_COMPARATIVELY_HEAVY': 'U16',
    'REG_1_PV_STRING_REVERSE_CONNECTION': 'STRINGING',
    'REG_1_CABLE_BETWEEN_CONTROL_BOARD_AND_POWER_BOARD_FOR_DT_IS_NOT_TIGHT_2_NEUTRAL_GROUND_CABLE_ARE_NOTCONNECTED_WELL_ON_AC_SIDE_3_CONTROL_BOARD_PROBLEM': 'U16',
    'REG_1_THE_DEVICE_IS_ABNORMAL': 'U16',
    'REG_1_SAFETY_COUNTRY_OF_INVERTER_IS_SET_WRONG_2_GRIDFREQUENCY_IS_NOT_STABLE': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = True



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0002, 'count':  15, 'fc': 3},
    {'start': 0x0123, 'count':  22, 'fc': 3},
    {'start': 0x0222, 'count':  19, 'fc': 3},
    {'start': 0x0300, 'count':  26, 'fc': 3},
    {'start': 0x0355, 'count':  34, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'L1_VOLTAGE',
    's_voltage           ': 'L2_VOLTAGE',
    't_voltage           ': 'L3_VOLTAGE',
    'r_current           ': 'L1_CURRENT',
    's_current           ': 'L2_CURRENT',
    't_current           ': 'L3_CURRENT',
    'frequency           ': 'DEA_FREQUENCY',
    'ac_power            ': 'DEA_TOTAL_ACTIVE_POWER',
    'cumulative_energy   ': 'HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWERGENERATION',
    'alarm1              ': 'WARNING_CODE',
    'mppt1_voltage'        : 'VPV1_PPV1INPUT_VOLTAGE',
    'mppt1_current'        : 'IPV1_PV1_INPUTCURRENT',
    'mppt2_voltage'        : 'VPV2_PV2_INPUTVOLTAGE',
    'mppt2_current'        : 'IPV2_PV2_INPUTCURRENT',
    'mppt3_voltage'        : 'VPV3_PV3_INPUTVOLTAGE',
    'mppt3_current'        : 'IPV3_PV3_INPUTCURRENT',
    'mppt4_voltage'        : 'VPV4_PV4_INPUTVOLTAGE',
    'mppt4_current'        : 'IPV4_PV4_INPUTCURRENT',
    'string1_voltage'      : 'STRING1_VOLTAGE',
    'string1_current'      : 'ISTR1_PV_STRING1CURRENT',
    'string2_voltage'      : 'STRING2_VOLTAGE',
    'string2_current'      : 'ISTR2_PV_STRING2CURRENT',
    'string3_voltage'      : 'STRING3_VOLTAGE',
    'string3_current'      : 'ISTR3_PV_STRING3CURRENT',
    'string4_voltage'      : 'STRING4_VOLTAGE',
    'string4_current'      : 'ISTR4_PV_STRING4CURRENT',
    'string5_voltage'      : 'STRING5_VOLTAGE',
    'string5_current'      : 'ISTR5_PV_STRING5CURRENT',
    'string6_voltage'      : 'STRING6_VOLTAGE',
    'string6_current'      : 'ISTR6_PV_STRING6CURRENT',
    'string7_voltage'      : 'STRING7_VOLTAGE',
    'string7_current'      : 'ISTR7_PV_STRING7CURRENT',
    'string8_voltage'      : 'STRING8_VOLTAGE',
    'string8_current'      : 'ISTR8_PV_STRING8CURRENT',
}



# H01 스칼라 필드 → (RegisterMap 속성명, 변환기 키)
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
H01_FIELD_MAP = {
    'mode                ': ('INVERTER_MODE', 'raw'),
    'r_voltage           ': ('L1_VOLTAGE', 'voltage_to_V'),  # user
    's_voltage           ': ('L2_VOLTAGE', 'voltage_to_V'),  # user
    't_voltage           ': ('L3_VOLTAGE', 'voltage_to_V'),  # user
    'r_current           ': ('L1_CURRENT', 'current_to_01A'),  # user
    's_current           ': ('L2_CURRENT', 'current_to_01A'),  # user
    't_current           ': ('L3_CURRENT', 'current_to_01A'),  # user
    'frequency           ': ('FREQUENCY', 'frequency_to_01Hz'),
    'ac_power            ': ('AC_POWER', 'power_to_W'),
    'pv_power            ': ('PV_POWER', 'power_to_W'),  # user
    'inner_temp          ': ('INNER_TEMP', 'raw'),
    'power_factor        ': ('POWER_FACTOR', 'pf_raw'),
    'cumulative_energy   ': ('TOTAL_ENERGY', 'energy_kwh_to_Wh'),
    'alarm1              ': ('WARNING_CODE', 'raw'),  # user
    'alarm2              ': ('WARNING_CODE', 'raw'),  # user
    'alarm3              ': ('WARNING_CODE', 'raw'),  # user
}
