# -*- coding: utf-8 -*-
"""
SMA Inverter Modbus Register Map
Based on SMA Modbus Protocol 
Protocol Name: sma
MPPT: 1 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04
"""



class RegisterMap:
    """SMA Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    DEVICE_MODEL_PDF                         = 0x0000  # TEXT
    MN                                       = 0x9C44  # STRING
    MD                                       = 0x9C54  # STRING
    OPT                                      = 0x9C64  # STRING
    VR                                       = 0x9C6C  # STRING
    SERIAL_NUMBER                            = 0x9C74  # STRING
    DA                                       = 0x9C84  # UINT16
    TMP_SNK                                  = 0x9D1B  # INT16
    TIME_PERIOD_FOR_CHANGE_OF_THE_APPARENT_POWER_LIMITATION = 0x9DA9  # UINT16
    PERMITTED_REACTION_TIME_FOR_CHANGE_OF_THE_APPARENT_POWER_LIMITA = 0x9DAA  # UINT16
    SNW                                      = 0x9FB3  # INT16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    CUMULATIVE_ENERGY                        = 0x9C9D  # 
    POWER_FACTOR                             = 0x9D0F  # INT16
    PV_POWER                                 = 0x9D94  # 

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    DNS1_NA_N                                = 0x9CB8  # STRING
    ST                                       = 0x9D1F  # ENUM16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    ST_VND                                   = 0x9D20  # 

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_STRING_COUNT                          = 1

    # --- RTU modbus_handler / simulator 필수 alias ---
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    ERROR_CODE1                              = ST_VND
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x9D20) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class SmaStatusConverter:
    """SMA INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = SmaStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 1
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-1).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 1:
        raise ValueError(f"MPPT number must be 1-1, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-1)."""
    if tracker_num < 1 or tracker_num > 1:
        raise ValueError(f"Tracker number must be 1-1, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 1:
        raise ValueError(f"MPPT number must be 1-1, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'DEVICE_MODEL_PDF': 'TEXT',
    'MN': 'STRING',
    'MD': 'STRING',
    'OPT': 'STRING',
    'VR': 'STRING',
    'SERIAL_NUMBER': 'STRING',
    'DA': 'UINT16',
    'CUMULATIVE_ENERGY': 'U16',
    'DNS1_NA_N': 'STRING',
    'POWER_FACTOR': 'INT16',
    'TMP_SNK': 'INT16',
    'ST': 'ENUM16',
    'ST_VND': 'U16',
    'PV_POWER': 'U16',
    'TIME_PERIOD_FOR_CHANGE_OF_THE_APPARENT_POWER_LIMITATION': 'UINT16',
    'PERMITTED_REACTION_TIME_FOR_CHANGE_OF_THE_APPARENT_POWER_LIMITA': 'UINT16',
    'SNW': 'INT16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x9C9D, 'count':  28, 'fc': 3},
    {'start': 0x9D0F, 'count':  18, 'fc': 3},
    {'start': 0x9D94, 'count':   1, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'R_PHASE_VOLTAGE',
    's_voltage           ': 'S_PHASE_VOLTAGE',
    't_voltage           ': 'T_PHASE_VOLTAGE',
    'r_current           ': 'R_PHASE_CURRENT',
    's_current           ': 'S_PHASE_CURRENT',
    't_current           ': 'T_PHASE_CURRENT',
    'frequency           ': 'FREQUENCY',
    'ac_power            ': 'AC_POWER',
    'temperature         ': 'INNER_TEMP',
    'cumulative_energy   ': 'CUMULATIVE_ENERGY',
    'alarm1              ': 'ERROR_CODE1',
    'mppt1_voltage'        : 'MPPT1_VOLTAGE',
    'mppt1_current'        : 'MPPT1_CURRENT',
}
