# -*- coding: utf-8 -*-
"""
SolarEdge Inverter Modbus Register Map
Based on SolarEdge Modbus Protocol 
Protocol Name: solaredge
MPPT: 1 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04
"""



class RegisterMap:
    """SolarEdge Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    C_MANUFACTURER                           = 0x9C44  # STRINGING
    DEVICE_MODEL                             = 0x9C54  # STRINGING
    FIRMWARE_VERSION                         = 0x9C6C  # STRINGING
    SERIAL_NUMBER                            = 0x9C74  # STRINGING
    C_DEVICE_ADDRESS                         = 0x9C84  # U16
    POWER_FACTOR                             = 0x9D0E  # S16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    L2_VOLTAGE                               = 0x0001  # U16
    REACTIVE_POWER                           = 0x0003  # U16
    TEMPERATURE                              = 0x0020  # U16
    SENSOR_NOT_CONNECTED                     = 0x0080  # U16
    CUMULATIVE_ENERGY                        = 0x9C9D  # U16
    I_DC_CURRENT                             = 0x9CA0  # U16
    I_DC_VOLTAGE                             = 0x9CA2  # U16
    PV_POWER                                 = 0x9CA4  # S16
    M_AC_CURRENT                             = 0x9CFE  # S16
    M_AC_CURRENT_B                           = 0x9D00  # S16
    M_AC_CURRENT_C                           = 0x9D01  # S16
    M_AC_VA                                  = 0x9D13  # S16
    M_AC_VA_B                                = 0x9D15  # S16
    M_AC_VA_C                                = 0x9D16  # S16
    M_AC_VAR                                 = 0x9D18  # S16
    M_AC_VAR_B                               = 0x9D1A  # S16
    M_AC_VAR_C                               = 0x9D1B  # S16
    M_AC_PF                                  = 0x9D1D  # S16
    M_AC_PF_B                                = 0x9D1F  # S16
    M_AC_PF_C                                = 0x9D20  # S16
    M_EXPORTED_VA_A                          = 0x9D35  # U32, scale VA
    M_EXPORTED_VA_A_HIGH                     = 0x9D36
    M_IMPORTED_VA_A                          = 0x9D3D  # U32, scale VA
    M_IMPORTED_VA_A_HIGH                     = 0x9D3E

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    I_STATUS                                 = 0x9CAB  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    I_STATUS_VENDOR                          = 0x9CAD  # U16
    I_STATUS_VENDOR4                         = 0x9CB7  # U32
    I_STATUS_VENDOR4_HIGH                    = 0x9CB8
    M_EVENTS                                 = 0x9D65  # U32
    M_EVENTS_HIGH                            = 0x9D66

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # L2 없음 → 대체

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_STRING_COUNT                          = 1

    # --- RTU modbus_handler / simulator 필수 alias ---
    INNER_TEMP                               = TEMPERATURE
    R_PHASE_VOLTAGE                          = S_PHASE_VOLTAGE  # L1 없음 → 단상 대체
    T_PHASE_VOLTAGE                          = S_PHASE_VOLTAGE  # L3 없음 → 단상 대체
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    ERROR_CODE1                              = I_STATUS_VENDOR
    ERROR_CODE2                              = I_STATUS_VENDOR4
    ERROR_CODE3                              = M_EVENTS
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x9CAD) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x9CB7) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x9D65) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x9E13) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x9EC3) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class SolaredgeStatusConverter:
    """SolarEdge INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = SolaredgeStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 1
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-1).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 1:
        raise ValueError(f"MPPT number must be 1-1, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-1)."""
    if tracker_num < 1 or tracker_num > 1:
        raise ValueError(f"Tracker number must be 1-1, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 1:
        raise ValueError(f"MPPT number must be 1-1, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'POWER_FACTOR': 'U16',
    'L2_VOLTAGE': 'U16',
    'REACTIVE_POWER': 'U16',
    'TEMPERATURE': 'U16',
    'SENSOR_NOT_CONNECTED': 'U16',
    'C_MANUFACTURER': 'STRINGING',
    'DEVICE_MODEL': 'STRINGING',
    'FIRMWARE_VERSION': 'STRINGING',
    'SERIAL_NUMBER': 'STRINGING',
    'C_DEVICE_ADDRESS': 'U16',
    'CUMULATIVE_ENERGY': 'U16',
    'I_DC_CURRENT': 'U16',
    'I_DC_VOLTAGE': 'U16',
    'PV_POWER': 'S16',
    'I_STATUS': 'U16',
    'I_STATUS_VENDOR': 'U16',
    'I_STATUS_VENDOR4': 'U32',
    'M_AC_CURRENT': 'S16',
    'M_AC_CURRENT_B': 'S16',
    'M_AC_CURRENT_C': 'S16',
    'M_AC_VA': 'S16',
    'M_AC_VA_B': 'S16',
    'M_AC_VA_C': 'S16',
    'M_AC_VAR': 'S16',
    'M_AC_VAR_B': 'S16',
    'M_AC_VAR_C': 'S16',
    'M_AC_PF': 'S16',
    'M_AC_PF_B': 'S16',
    'M_AC_PF_C': 'S16',
    'M_EXPORTED_VA_A': 'U32',
    'M_IMPORTED_VA_A': 'U32',
    'M_EVENTS': 'U32',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0000, 'count':  33, 'fc': 3},
    {'start': 0x0080, 'count':   1, 'fc': 3},
    {'start': 0x9C9D, 'count':  28, 'fc': 3},
    {'start': 0x9CFE, 'count':  65, 'fc': 3},
    {'start': 0x9D65, 'count':   2, 'fc': 3},
    {'start': 0x9DAC, 'count':  35, 'fc': 3},
    {'start': 0x9E13, 'count':   2, 'fc': 3},
    {'start': 0x9E5B, 'count':  65, 'fc': 3},
    {'start': 0x9EC3, 'count':   2, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'R_PHASE_VOLTAGE',
    's_voltage           ': 'L2_VOLTAGE',
    't_voltage           ': 'T_PHASE_VOLTAGE',
    'r_current           ': 'R_PHASE_CURRENT',
    's_current           ': 'S_PHASE_CURRENT',
    't_current           ': 'T_PHASE_CURRENT',
    'frequency           ': 'FREQUENCY',
    'ac_power            ': 'AC_POWER',
    'temperature         ': 'TEMPERATURE',
    'cumulative_energy   ': 'CUMULATIVE_ENERGY',
    'alarm1              ': 'ERROR_CODE1',
    'mppt1_voltage'        : 'I_DC_VOLTAGE',
    'mppt1_current'        : 'I_DC_CURRENT',
}
