# -*- coding: utf-8 -*-
"""
CL-Series-Modbus-Interface-Guide Inverter Modbus Register Map
Based on CL-Series-Modbus-Interface-Guide Modbus Protocol 
Protocol Name: cl-series-modbus-interface-guide
MPPT: 4 | Strings: 8 (2/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-03
"""



class RegisterMap:
    """CL-Series-Modbus-Interface-Guide Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    HIGH_TRANSIENT_DC_BUS_VOLTAGE            = 0x0013  # U16
    HIGH_DC_BUS_VOLTAGE                      = 0x0014  # U16
    MODULE_TEMPERATURE_IS_TOOHIGH            = 0x0024  # U16
    INVERTER_INSULATION_RESISTANCEEVENT_ISO_FLT = 0x0027  # U16
    PV_CONFIGURATION_MODE_SET_ONTHE_HMI_DOES_NOT_MATCH_THEDESIGN = 0x002F  # U16
    PHASE_S_CURRENT_SAMPLINGCHANNEL_EVENT    = 0x0031  # U16
    INVERTER_INSULATION_RESISTANCEREDUNDANCY_EVENT_IS_DETECTED = 0x0037  # U16
    SOLAR_IRRADIATION_IS_NOTSUFFICIENT_FOR_INVERTER_OPERATION = 0x004B  # U16
    SERIAL_NUMBER                            = 0x137D  # U16
    DEVICE_MODEL                             = 0x1387  # U16
    NOMINAL_ACTIVEPOWER                      = 0x1388  # U16, scale kW 0.1
    OUTPUT_TYPE                              = 0x1389  # U16
    DAILY_POWERYIELDS                        = 0x138A  # U16, scale kWh 0.1
    TOTAL_RUNNINGTIME                        = 0x138D  # U32
    TOTAL_RUNNINGTIME_HIGH                   = 0x138E
    POWER_LIMITATION_SWITCH                  = 0x138E  # U16
    INTERNALTEMPERATURE                      = 0x138F  # S16, scale ℃ 0.1
    TOTAL_APPARENTPOWER                      = 0x1390  # U32, scale VA
    TOTAL_APPARENTPOWER_HIGH                 = 0x1391
    EVENT_ALARMCODE                          = 0x13B4  # U16
    NOMINAL_REACTIVEPOWER                    = 0x13B8  # U16
    ARRAY_INSULATIONRESISTANCE               = 0x13CE  # U16
    DAILY_RUNNINGTIME                        = 0x13F8  # U16
    MPPT_4_VOLTAGE                           = 0x13FA  # U16, scale V 0.1
    MONTHLY_POWER_YIELDS                     = 0x1407  # U32, scale kWh 0.1
    MONTHLY_POWER_YIELDS_HIGH                = 0x1408
    BUS_VOLTAGE                              = 0x141A  # U16, scale V 0.1
    FREQUENCY                                = 0x141B  # U16, scale Hz 0.01

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    ILLEGAL_FUNCTION                         = 0x0001  # U16
    ILLEGAL_ADDRESS                          = 0x0002  # U16
    ILLEGAL_DATA_VALUE                       = 0x0003  # U16
    SLAVE_DEVICE_ERROR                       = 0x0004  # U16
    THE_AC_OUTPUT_CURRENTEXCEEDS_THE_INVERTERSPROTECTION_LIMIT = 0x0006  # U16
    TRANSIENT_AC_OVER_CURRENT                = 0x0007  # U16
    GR_L                                     = 0x000A  # U16
    THE_DC_COMPONENT_OF_THE_ACCURRENT_EXCEEDS_THE_INVERTERSLIMIT = 0x000B  # U16
    RESIDUAL_CURRENT_LEAKAGEDETECTED_IS_HIGH = 0x000C  # U16
    GRID_OVERVOLTAGE                         = 0x000F  # U16
    GRID_VOLTAGE_IMBALANCE                   = 0x0011  # U16
    PV_INPUT_OVER_CURRENT                    = 0x0015  # U16
    PV_CONFIGURATION_MODE_HASCHANGED_DURING_NORMALOPERATION = 0x0017  # U16
    VOLTAGE_IMBALANCE_AT_NEUTRALPOINT        = 0x0018  # U16
    TRANSIENT_UNBALANCE_OFVOLTAGE_NEUTRAL_POINT = 0x0019  # U16
    CLAMP_CAPACITANCE_OVER_VOLTAGE_EVENT_IS_DETECTED = 0x001E  # U16
    CLAMP_CAPACITANCE_UNDER_VOLTAGE_EVENT_IS_DETECTED = 0x001F  # U16
    CLAMP_CAPACITANCE_IMBALANCEEVENT_IS_DETECTED = 0x0020  # U16
    CLAMP_CAPACITANCE_PRE_CHARGE_GROUND_FAULT_ISDETECTED = 0x0021  # U16
    INTERNAL_AMBIENT_TEMPERATUREIS_TOO_HIGH  = 0x0025  # U16
    LINE_TIE_RELAY_CONTACTS_HAVEWELDED_OR_ARE_OPEN = 0x0026  # U16
    AC_OR_DC_OVER_CURRENT_OR_DCOVER_VOLTAGE_EVENT_ISDETECTED = 0x0028  # U16
    CURRENT_LEAKAGE_SAMPLINGCHANNEL_EVENT    = 0x0029  # U16
    AC_CURRENT_IMBALANCE                     = 0x002A  # U16
    THE_AMBIENT_TEMPERATURE_FALLSBELOW_25_C_13_F = 0x002B  # U16
    DC_AC_INVERSION_CIRCUIT_EVENT            = 0x002C  # U16
    GRID_VOLTAGE_REDUNDANCYEVENT_IS_DETECTED = 0x0035  # U16
    GRID_FREQUENCY_REDUNDANCYEVENT_IS_DETECTED = 0x0036  # U16
    INVERTER_LEAKAGE_CURRENTREDUNDANCY_EVENT_IS_DETECTED = 0x0038  # STRINGING
    MAIN_DSP_COMMUNICATIONREDUNDANCY_EVENT_IS_DETECTED = 0x003B  # U16
    JP_50HZ                                  = 0x0046  # U16
    JP_60HZ                                  = 0x0047  # U16
    DC_SIDE_SPD_EVENT                        = 0x0048  # U16
    COMMUNICATION_EVENT                      = 0x004A  # U16
    PV_OVERLOAD_CONDITION                    = 0x004C  # U16
    PV_1_POWER_EVENT_WARNING                 = 0x004E  # U16
    PV_3_POWER_EVENT_WARNING                 = 0x0050  # U16
    PV_4_POWER_EVENT_WARNING                 = 0x0051  # U16
    SELF_TEST_DID_NOT_PASS                   = 0x0069  # U16
    GROUNDING_CABLE_EVENT                    = 0x006A  # U16
    ELECTRIC_ARC_EVENT                       = 0x0088  # U16
    PV5_ABNORMAL                             = 0x00DC  # U16
    DEVICE_ANOMALY                           = 0x0130  # U16
    STRING_1_ABNORMAL_ALARM                  = 0x0224  # STRINGING
    STRING_2_ABNORMAL_ALARM                  = 0x0225  # STRINGING
    STRING_3_ABNORMAL_ALARM                  = 0x0226  # STRINGING
    STRING_4_ABNORMAL_ALARM                  = 0x0227  # STRINGING
    STRING_5_ABNORMAL_ALARM                  = 0x0228  # STRINGING
    STRING_6_ABNORMAL_ALARM                  = 0x0229  # STRINGING
    STRING_7_ABNORMAL_ALARM                  = 0x022A  # STRINGING
    STRING_10_ABNORMAL_ALARM                 = 0x022D  # STRINGING
    STRING_X_REVERSE_CONNECTION_ALARM        = 0x0235  # STRINGING
    CUMULATIVE_ENERGY                        = 0x138B  # U32, scale kWh
    CUMULATIVE_ENERGY_HIGH                   = 0x138C
    MPPT_1_VOLTAGE                           = 0x1392  # U16, scale V 0.1
    MPPT_1_CURRENT                           = 0x1393  # U16, scale A 0.1
    MPPT_2_VOLTAGE                           = 0x1394  # U16, scale V 0.1
    MPPT_2_CURRENT                           = 0x1395  # U16, scale A 0.1
    MPPT_3_VOLTAGE                           = 0x1396  # U16, scale V 0.1
    MPPT_3_CURRENT                           = 0x1397  # U16, scale A 0.1
    PV_POWER                                 = 0x1398  # U32, scale W
    PV_POWER_HIGH                            = 0x1399
    A_B_LINEVOLTAGE_PHASE_AVOLTAGE           = 0x139A  # U16, scale V 0.1
    B_C_LINE_VOLTAGE_PHASE_BVOLTAGE          = 0x139B  # U16, scale V 0.1
    C_A_LINE_VOLTAGE_PHASE_CVOLTAGE          = 0x139C  # U16, scale V 0.1
    L1_CURRENT                               = 0x139D  # U16, scale A 0.1
    L2_CURRENT                               = 0x139E  # U16, scale A 0.1
    L3_CURRENT                               = 0x139F  # U16, scale A 0.1
    TOTAL_ACTIVEPOWER                        = 0x13A6  # U32, scale W
    TOTAL_ACTIVEPOWER_HIGH                   = 0x13A7
    TOTAL_REACTIVEPOWER                      = 0x13A8  # S32
    TOTAL_REACTIVEPOWER_HIGH                 = 0x13A9
    POWER_FACTOR                             = 0x13AA  # S16
    REACTIVE_POWERPERCENTAGE_SETTING         = 0x13AC  # S16
    OPERATING_STATE                          = 0x13AD  # U16
    MPPT_4_CURRENT                           = 0x13FB  # U16, scale A 0.1
    NEGATIVE_VOLTAGETO_THE_GROUND            = 0x1419  # S16, scale V 0.1
    PID_ALARM_CODE                           = 0x141E  # U16
    EMERGENCY_STOP                           = 0x1500  # U16
    STRING_1_CURRENT                         = 0x1B64  # U16, scale A 0.01
    STRING_2_CURRENT                         = 0x1B65  # U16, scale A 0.01
    STRING_3_CURRENT                         = 0x1B66  # U16, scale A 0.01
    STRING_4_CURRENT                         = 0x1B67  # U16, scale A 0.01
    STRING_5_CURRENT                         = 0x1B68  # U16, scale A 0.01
    STRING_6_CURRENT                         = 0x1B69  # U16, scale A 0.01
    STRING_7_CURRENT                         = 0x1B6A  # U16, scale A 0.01
    STRING_8_CURRENT                         = 0x1B6B  # U16, scale A 0.01
    EVENT                                    = 0x5500  # U16

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    PHASE_R_CURRENT_SAMPLINGCHANNEL_EVENT    = 0x0030  # U16
    AFD_MODULE_ABNORMAL                      = 0x0057  # U16
    AFD_MODULE_DISABLED                      = 0x0059  # U16
    EVENT_ALARMTIME_YEAR                     = 0x13AE  # U16
    PID_WORK_STATE                           = 0x141D  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    AVERAGE_GRID_OVER_VOLTAGE_10MINUTES      = 0x000E  # U16
    PHASE_T_CURRENT_SAMPLINGCHANNEL_EVENT    = 0x0032  # U16
    MAIN_DSP_DATA_COMPARISONEVENT_IS_DETECTED = 0x003C  # U16
    PV_2_POWER_EVENT_WARNING                 = 0x004F  # U16
    STRING_1_REVERSE_CONNECTIONEVENT         = 0x01C0  # STRINGING
    STRING_2_REVERSE_CONNECTIONEVENT         = 0x01C1  # STRINGING
    STRING_3_REVERSE_CONNECTIONEVENT         = 0x01C2  # STRINGING
    STRING_4_REVERSE_CONNECTIONEVENT         = 0x01C3  # STRINGING
    STRING_5_REVERSE_CONNECTIONEVENT         = 0x01C4  # STRINGING
    STRING_6_REVERSE_CONNECTIONEVENT         = 0x01C5  # STRINGING
    STRING_7_REVERSE_CONNECTIONEVENT         = 0x01C6  # STRINGING
    STRING_8_REVERSE_CONNECTIONEVENT         = 0x01C7  # STRINGING
    STRING_9_REVERSE_CONNECTIONEVENT         = 0x01C8  # STRINGING
    STRING_10_REVERSE_CONNECTIONEVENT        = 0x01C9  # STRINGING
    STRING_1_REVERSE_CONNECTIONALARM         = 0x0214  # STRINGING
    STRING_2_REVERSE_CONNECTIONALARM         = 0x0215  # STRINGING
    STRING_3_REVERSE_CONNECTIONALARM         = 0x0216  # STRINGING
    STRING_4_REVERSE_CONNECTIONALARM         = 0x0217  # STRINGING
    STRING_5_REVERSE_CONNECTIONALARM         = 0x0218  # STRINGING
    STRING_6_REVERSE_CONNECTIONALARM         = 0x0219  # STRINGING
    STRING_7_REVERSE_CONNECTIONALARM         = 0x021A  # STRINGING
    STRING_8_REVERSE_CONNECTIONALARM         = 0x021B  # STRINGING
    STRING_9_REVERSE_CONNECTIONALARM         = 0x021C  # STRINGING
    STRING_10_REVERSE_CONNECTIONALARM        = 0x021D  # STRINGING
    STRING_8_ABNORMAL_ALARM                  = 0x022B  # STRINGING
    STRING_9_ABNORMAL_ALARM                  = 0x022C  # STRINGING
    STRING_X_OUTPUT_CURRENT_ANOMALY          = 0x0244  # STRINGING
    EVENT_ALARMTIME_MONTH                    = 0x13AF  # U16
    EVENT_ALARMTIME_DAY                      = 0x13B0  # U16
    EVENT_ALARMTIME_HOUR                     = 0x13B1  # U16
    EVENT_ALARMTIME_MINUTE                   = 0x13B2  # U16
    EVENT_ALARMTIME_SECOND                   = 0x13B3  # U16
    ALARM_RUN                                = 0x9100  # U16

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x000E) — Bit field"""
    BITS = {
        0:  "Inverter over dc-bias current",
        1:  "Inverter relay abnormal",
        2:  "Remote off",
        3:  "Inverter over temperature",
        4:  "GFCI abnormal",
        5:  "PV string reverse",
        6:  "System type error",
        7:  "Fan abnormal",
        8:  "Dc-link unbalance or under voltage",
        9:  "Dc-link over voltage",
        10:  "Internal communication error",
        11:  "Software incompatibility",
        12:  "Internal storage error",
        13:  "Data inconsistency",
        14:  "Inverter abnormal",
        15:  "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x0032) — Bit field"""
    BITS = {
        0:  "Grid over voltage",
        1:  "Grid under voltage",
        2:  "Grid absent",
        3:  "Grid over frequency",
        4:  "Grid under frequency",
        5:  "PV over voltage",
        6:  "PV insulation abnormal",
        7:  "Leakage current abnormal",
        8:  "Inverter in power limit state",
        9:  "Internal power supply abnormal",
        10:  "PV string abnormal",
        11:  "PV under voltage",
        12:  "PV irradiation weak",
        13:  "Grid abnormal",
        14:  "Arc fault detection",
        15:  "AC moving average voltage high",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x003C) — Bit field"""
    BITS = {
        0:  "Reserved",
        1:  "Logger/E-Display EEPROM fail",
        2:  "Reserved",
        3:  "Single tracker detect warning",
        4:  "AFCI lost",
        5:  "Data logger lost",
        6:  "Meter lost",
        7:  "Inverter lost",
        8:  "Grid N abnormal",
        9:  "Surge Protection Devices (SPD) defective",
        10:  "Parallel ID warning",
        11:  "Parallel SYN signal warning",
        12:  "Parallel BAT abnormal",
        13:  "Parallel GRID abnormal",
        14:  "Generator voltage abnormal",
        15:  "Reserved",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x004F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x01C0) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x01C1) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x01C2) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x01C3) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x01C4) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode10:
    """Error Code Table10 (0x01C5) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode11:
    """Error Code Table11 (0x01C6) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode12:
    """Error Code Table12 (0x01C7) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode13:
    """Error Code Table13 (0x01C8) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode14:
    """Error Code Table14 (0x01C9) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode15:
    """Error Code Table15 (0x0214) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode16:
    """Error Code Table16 (0x0215) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode17:
    """Error Code Table17 (0x0216) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode18:
    """Error Code Table18 (0x0217) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode19:
    """Error Code Table19 (0x0218) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode20:
    """Error Code Table20 (0x0219) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode21:
    """Error Code Table21 (0x021A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode22:
    """Error Code Table22 (0x021B) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode23:
    """Error Code Table23 (0x021C) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode24:
    """Error Code Table24 (0x021D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode25:
    """Error Code Table25 (0x022B) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode26:
    """Error Code Table26 (0x022C) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode27:
    """Error Code Table27 (0x0244) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode28:
    """Error Code Table28 (0x13AF) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode29:
    """Error Code Table29 (0x13B0) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode30:
    """Error Code Table30 (0x13B1) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode31:
    """Error Code Table31 (0x13B2) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode32:
    """Error Code Table32 (0x13B3) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode33:
    """Error Code Table33 (0x9100) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class Cl-Series-Modbus-Interface-GuideStatusConverter:
    """CL-Series-Modbus-Interface-Guide INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = Cl-Series-Modbus-Interface-GuideStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 4
STRING_CHANNELS = 8


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-8)."""
    if string_num < 1 or string_num > 8:
        raise ValueError(f"String number must be 1-8, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-4)."""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=0):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-4)."""
    if tracker_num < 1 or tracker_num > 4:
        raise ValueError(f"Tracker number must be 1-4, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=0):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-2)."""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if string_num < 1 or string_num > 2:
        raise ValueError(f"String number must be 1-2 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=8, strings_per_mppt=2):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=0):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=0):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'ILLEGAL_FUNCTION': 'U16',
    'ILLEGAL_ADDRESS': 'U16',
    'ILLEGAL_DATA_VALUE': 'U16',
    'SLAVE_DEVICE_ERROR': 'U16',
    'THE_AC_OUTPUT_CURRENTEXCEEDS_THE_INVERTERSPROTECTION_LIMIT': 'U16',
    'TRANSIENT_AC_OVER_CURRENT': 'U16',
    'GR_L': 'U16',
    'THE_DC_COMPONENT_OF_THE_ACCURRENT_EXCEEDS_THE_INVERTERSLIMIT': 'U16',
    'RESIDUAL_CURRENT_LEAKAGEDETECTED_IS_HIGH': 'U16',
    'AVERAGE_GRID_OVER_VOLTAGE_10MINUTES': 'U16',
    'GRID_OVERVOLTAGE': 'U16',
    'GRID_VOLTAGE_IMBALANCE': 'U16',
    'HIGH_TRANSIENT_DC_BUS_VOLTAGE': 'U16',
    'HIGH_DC_BUS_VOLTAGE': 'U16',
    'PV_INPUT_OVER_CURRENT': 'U16',
    'PV_CONFIGURATION_MODE_HASCHANGED_DURING_NORMALOPERATION': 'U16',
    'VOLTAGE_IMBALANCE_AT_NEUTRALPOINT': 'U16',
    'TRANSIENT_UNBALANCE_OFVOLTAGE_NEUTRAL_POINT': 'U16',
    'CLAMP_CAPACITANCE_OVER_VOLTAGE_EVENT_IS_DETECTED': 'U16',
    'CLAMP_CAPACITANCE_UNDER_VOLTAGE_EVENT_IS_DETECTED': 'U16',
    'CLAMP_CAPACITANCE_IMBALANCEEVENT_IS_DETECTED': 'U16',
    'CLAMP_CAPACITANCE_PRE_CHARGE_GROUND_FAULT_ISDETECTED': 'U16',
    'MODULE_TEMPERATURE_IS_TOOHIGH': 'U16',
    'INTERNAL_AMBIENT_TEMPERATUREIS_TOO_HIGH': 'U16',
    'LINE_TIE_RELAY_CONTACTS_HAVEWELDED_OR_ARE_OPEN': 'U16',
    'INVERTER_INSULATION_RESISTANCEEVENT_ISO_FLT': 'U16',
    'AC_OR_DC_OVER_CURRENT_OR_DCOVER_VOLTAGE_EVENT_ISDETECTED': 'U16',
    'CURRENT_LEAKAGE_SAMPLINGCHANNEL_EVENT': 'U16',
    'AC_CURRENT_IMBALANCE': 'U16',
    'THE_AMBIENT_TEMPERATURE_FALLSBELOW_25_C_13_F': 'U16',
    'DC_AC_INVERSION_CIRCUIT_EVENT': 'U16',
    'PV_CONFIGURATION_MODE_SET_ONTHE_HMI_DOES_NOT_MATCH_THEDESIGN': 'U16',
    'PHASE_R_CURRENT_SAMPLINGCHANNEL_EVENT': 'U16',
    'PHASE_S_CURRENT_SAMPLINGCHANNEL_EVENT': 'U16',
    'PHASE_T_CURRENT_SAMPLINGCHANNEL_EVENT': 'U16',
    'GRID_VOLTAGE_REDUNDANCYEVENT_IS_DETECTED': 'U16',
    'GRID_FREQUENCY_REDUNDANCYEVENT_IS_DETECTED': 'U16',
    'INVERTER_INSULATION_RESISTANCEREDUNDANCY_EVENT_IS_DETECTED': 'U16',
    'INVERTER_LEAKAGE_CURRENTREDUNDANCY_EVENT_IS_DETECTED': 'STRINGING',
    'MAIN_DSP_COMMUNICATIONREDUNDANCY_EVENT_IS_DETECTED': 'U16',
    'MAIN_DSP_DATA_COMPARISONEVENT_IS_DETECTED': 'U16',
    'JP_50HZ': 'U16',
    'JP_60HZ': 'U16',
    'DC_SIDE_SPD_EVENT': 'U16',
    'COMMUNICATION_EVENT': 'U16',
    'SOLAR_IRRADIATION_IS_NOTSUFFICIENT_FOR_INVERTER_OPERATION': 'U16',
    'PV_OVERLOAD_CONDITION': 'U16',
    'PV_1_POWER_EVENT_WARNING': 'U16',
    'PV_2_POWER_EVENT_WARNING': 'U16',
    'PV_3_POWER_EVENT_WARNING': 'U16',
    'PV_4_POWER_EVENT_WARNING': 'U16',
    'AFD_MODULE_ABNORMAL': 'U16',
    'AFD_MODULE_DISABLED': 'U16',
    'SELF_TEST_DID_NOT_PASS': 'U16',
    'GROUNDING_CABLE_EVENT': 'U16',
    'ELECTRIC_ARC_EVENT': 'U16',
    'PV5_ABNORMAL': 'U16',
    'DEVICE_ANOMALY': 'U16',
    'STRING_1_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_2_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_3_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_4_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_5_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_6_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_7_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_8_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_9_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_10_REVERSE_CONNECTIONEVENT': 'STRINGING',
    'STRING_1_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_2_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_3_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_4_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_5_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_6_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_7_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_8_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_9_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_10_REVERSE_CONNECTIONALARM': 'STRINGING',
    'STRING_1_ABNORMAL_ALARM': 'STRINGING',
    'STRING_2_ABNORMAL_ALARM': 'STRINGING',
    'STRING_3_ABNORMAL_ALARM': 'STRINGING',
    'STRING_4_ABNORMAL_ALARM': 'STRINGING',
    'STRING_5_ABNORMAL_ALARM': 'STRINGING',
    'STRING_6_ABNORMAL_ALARM': 'STRINGING',
    'STRING_7_ABNORMAL_ALARM': 'STRINGING',
    'STRING_8_ABNORMAL_ALARM': 'STRINGING',
    'STRING_9_ABNORMAL_ALARM': 'STRINGING',
    'STRING_10_ABNORMAL_ALARM': 'STRINGING',
    'STRING_X_REVERSE_CONNECTION_ALARM': 'STRINGING',
    'STRING_X_OUTPUT_CURRENT_ANOMALY': 'STRINGING',
    'SERIAL_NUMBER': 'U16',
    'DEVICE_MODEL': 'U16',
    'NOMINAL_ACTIVEPOWER': 'U16',
    'OUTPUT_TYPE': 'U16',
    'DAILY_POWERYIELDS': 'U16',
    'CUMULATIVE_ENERGY': 'U32',
    'TOTAL_RUNNINGTIME': 'U32',
    'POWER_LIMITATION_SWITCH': 'U16',
    'INTERNALTEMPERATURE': 'S16',
    'TOTAL_APPARENTPOWER': 'U32',
    'MPPT_1_VOLTAGE': 'U16',
    'MPPT_1_CURRENT': 'U16',
    'MPPT_2_VOLTAGE': 'U16',
    'MPPT_2_CURRENT': 'U16',
    'MPPT_3_VOLTAGE': 'U16',
    'MPPT_3_CURRENT': 'U16',
    'PV_POWER': 'U32',
    'A_B_LINEVOLTAGE_PHASE_AVOLTAGE': 'U16',
    'B_C_LINE_VOLTAGE_PHASE_BVOLTAGE': 'U16',
    'C_A_LINE_VOLTAGE_PHASE_CVOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'L2_CURRENT': 'U16',
    'L3_CURRENT': 'U16',
    'TOTAL_ACTIVEPOWER': 'U32',
    'TOTAL_REACTIVEPOWER': 'S32',
    'POWER_FACTOR': 'S16',
    'FREQUENCY': 'U16',
    'REACTIVE_POWERPERCENTAGE_SETTING': 'S16',
    'OPERATING_STATE': 'U16',
    'EVENT_ALARMTIME_YEAR': 'U16',
    'EVENT_ALARMTIME_MONTH': 'U16',
    'EVENT_ALARMTIME_DAY': 'U16',
    'EVENT_ALARMTIME_HOUR': 'U16',
    'EVENT_ALARMTIME_MINUTE': 'U16',
    'EVENT_ALARMTIME_SECOND': 'U16',
    'EVENT_ALARMCODE': 'U16',
    'NOMINAL_REACTIVEPOWER': 'U16',
    'ARRAY_INSULATIONRESISTANCE': 'U16',
    'DAILY_RUNNINGTIME': 'U16',
    'MPPT_4_VOLTAGE': 'U16',
    'MPPT_4_CURRENT': 'U16',
    'MONTHLY_POWER_YIELDS': 'U32',
    'NEGATIVE_VOLTAGETO_THE_GROUND': 'S16',
    'BUS_VOLTAGE': 'U16',
    'PID_WORK_STATE': 'U16',
    'PID_ALARM_CODE': 'U16',
    'EMERGENCY_STOP': 'U16',
    'STRING_1_CURRENT': 'U16',
    'STRING_2_CURRENT': 'U16',
    'STRING_3_CURRENT': 'U16',
    'STRING_4_CURRENT': 'U16',
    'STRING_5_CURRENT': 'U16',
    'STRING_6_CURRENT': 'U16',
    'STRING_7_CURRENT': 'U16',
    'STRING_8_CURRENT': 'U16',
    'EVENT': 'U16',
    'ALARM_RUN': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = True
