# -*- coding: utf-8 -*-
"""
ABB Inverter Modbus Register Map
Based on ABB Modbus Protocol 
Protocol Name: abb
MPPT: 2 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04
"""



class RegisterMap:
    """ABB Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    INTERNAL_ERROR_E029                      = 0x0014  # U16
    UTH_FAULT                                = 0x0018  # U16
    L2_VOLTAGE                               = 0x0019  # U16
    L3_VOLTAGE                               = 0x001E  # U16
    TEMPERATURE_FAULT                        = 0x001F  # U16
    DAILY_ENERGY                             = 0x0036  # U16
    INVERTER_SERIAL_NUMBER_SN0               = 0x0068  # ASCII
    INVERTER_SERIAL_NUMBER_SN1               = 0x0069  # ASCII
    INVERTER_SERIAL_NUMBER_SN2               = 0x006A  # ASCII
    INVERTER_SERIAL_NUMBER_SN3               = 0x006B  # ASCII
    INVERTER_SERIAL_NUMBER_SN4               = 0x006C  # ASCII
    INVERTER_SERIAL_NUMBER_SN5               = 0x006D  # ASCII
    INVERTER_MODEL_IDENTIFIER                = 0x0074  # U16
    INVERTER_INPUT_1_VOLTAGE                 = 0x009A  # U16
    COMMUNICATION_BOARD_SERIAL_NUMBER_SN0    = 0x0114  # ASCII
    COMMUNICATION_BOARD_SERIAL_NUMBER_SN1    = 0x0115  # ASCII
    COMMUNICATION_BOARD_SERIAL_NUMBER_SN2    = 0x0116  # ASCII
    COMMUNICATION_BOARD_SERIAL_NUMBER_SN3    = 0x0117  # ASCII
    COMMUNICATION_BOARD_SERIAL_NUMBER_SN4    = 0x0118  # ASCII
    COMMUNICATION_BOARD_SERIAL_NUMBER_SN5    = 0x0119  # ASCII
    FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN0     = 0x0124  # U16
    FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN1     = 0x0125  # U16
    FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN2     = 0x0126  # U16
    FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN3     = 0x0127  # U16
    FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN4     = 0x0128  # U16
    FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN5     = 0x0129  # U16
    DYNAMIC_MODE_REACTIVE_POWERMANAGEMENT_SET_FIXED_Q_BYPERCENTAGE_OF_NOMINAL_POWER_P_IN_1_STEPS_NOM = 0x01FB  # U16
    DYNAMIC_MODE_ACTIVE_POWERMANAGEMENT_SET_ACTIVE_POWEREXPRESSED_AS_PERCENTAGE_OF_NOMINAL_POWER_P_IN_1_STEPS_NOM = 0x01FC  # U16
    PERMANENT_MODE_ACTIVE_POWERMANAGEMENT_SET_ACTIVE_POWEREXPRESSED_AS_PERCENTAGE_OF_NOMINAL_POWER_P_IN_1_STEPS_NOM = 0x0200  # U16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    POWER_FACTOR                             = 0x0000  # U16
    TEMPERATURE                              = 0x0001  # U16
    REACTIVE_POWER                           = 0x0003  # U16
    DC_DC_START                              = 0x0004  # U16
    GROUND_FAULT                             = 0x0009  # U16
    OTH_FAULT                                = 0x000A  # U16
    L1_VOLTAGE                               = 0x000C  # U16
    LEAK_FAULT                               = 0x000F  # U16
    PV_POWER                                 = 0x0010  # U16
    INTERNAL_ERROR_E026                      = 0x0011  # U16
    INTERNAL_ERROR_E027                      = 0x0012  # U16
    INTERNAL_ERROR_E028                      = 0x0013  # U16
    INTERNAL_ERROR_E030                      = 0x0015  # U16
    INT_COM_FAULT                            = 0x0021  # U16
    CUMULATIVE_ENERGY                        = 0x0023  # U16
    FREQUENCY                                = 0x0025  # U16
    PV_VOLTAGE                               = 0x0026  # U16
    VREF_ERROR                               = 0x0027  # U16
    L2_CURRENT                               = 0x002B  # U16
    L3_CURRENT                               = 0x002F  # U16
    ERROR_CODE1                              = 0x0033  # U16
    BATTERY_LOW                              = 0x0034  # U16
    ARC_FAULT_SELF_TEST_FAIL                 = 0x0035  # U16
    ERROR_CODE2                              = 0x003C  # U16
    ERROR_CODE3                              = 0x003F  # U16
    COMMUNICATION_LOSS_WITH_COMMUNICATION_BOARD = 0x0053  # U16
    ARC_FAULT_WRONG_CONFIGURATION            = 0x0055  # U16
    L1_CURRENT                               = 0x0073  # ASCII
    AC_POWER                                 = 0x0076  # U16
    INVERTER_STATES_BYTE_0_GLOBAL_STATE      = 0x007C  # U16
    INVERTER_STATES_BYTE_2_DC_DC_CHANNEL_1_STATE = 0x007E  # U16
    INVERTER_STATES_BYTE_3_DC_DC_CHANNEL_2_STATE = 0x007F  # U16
    INVERTER_STATES_BYTE_4_ALARM_STATE       = 0x0080  # U16
    DISPLAY_BOARD_PRESENCE_INDICATES_STATUS_OF_BOARD_TOINVERTER = 0x0081  # U16
    INVERTER_PARTIAL_ENERGY                  = 0x0088  # U16
    INVERTER_WEEK_ENERGY                     = 0x008A  # U16
    INVERTER_FREQUENCY                       = 0x0096  # U16
    INVERTER_INPUT_1_CURRENT                 = 0x009C  # U16
    INVERTER_INPUT_2_POWER                   = 0x009E  # U16
    INVERTER_INPUT_2_VOLTAGE                 = 0x00A0  # U16
    INVERTER_PRESENCE_INDICATES_STATUS_OF_BOARD_TO_INVERTER = 0x00AE  # U16
    REMOTE_ON_OFF                            = 0x00B4  # U16
    RESET_BY_HAND                            = 0x00B5  # U16
    DYNAMIC_MODE_REACTIVE_POWERMANAGEMENT_BY_FIXED_PF = 0x00C8  # U16
    PERMANENT_MODE_REACTIVE_POWER_MANAGEMENT_BY_FIXED_PF = 0x00CA  # U16
    PERMANENT_MODE_RESET_PF_TO_1             = 0x00CD  # U16
    PERMANENT_MODE_REACTIVE                  = 0x00E3  # U16
    AUXILIARY_BOARDS_START_REGISTER          = 0x00FA  # U16
    AUXILIARY_BOARD_MAP_SIZE                 = 0x00FB  # U16

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    FUSE_CONTROL_BOARD_STATES_BYTE_2         = 0x0138  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    FORBIDDEN_STATE                          = 0x0028  # U16
    INVERTER_START_REGISTER                  = 0x0064  # U16
    INVERTER_MAP_SIZE                        = 0x0065  # U16

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # L2 없음 → 대체

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_STRING_COUNT                          = 2

    # --- RTU modbus_handler / simulator 필수 alias ---
    INNER_TEMP                               = TEMPERATURE
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x000D) — Bit field"""
    BITS = {
        0:  "Inverter over dc-bias current",
        1:  "Inverter relay abnormal",
        2:  "Remote off",
        3:  "Inverter over temperature",
        4:  "GFCI abnormal",
        5:  "PV string reverse",
        6:  "System type error",
        7:  "Fan abnormal",
        8:  "Dc-link unbalance or under voltage",
        9:  "Dc-link over voltage",
        10:  "Internal communication error",
        11:  "Software incompatibility",
        12:  "Internal storage error",
        13:  "Data inconsistency",
        14:  "Inverter abnormal",
        15:  "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x001D) — Bit field"""
    BITS = {
        0:  "Grid over voltage",
        1:  "Grid under voltage",
        2:  "Grid absent",
        3:  "Grid over frequency",
        4:  "Grid under frequency",
        5:  "PV over voltage",
        6:  "PV insulation abnormal",
        7:  "Leakage current abnormal",
        8:  "Inverter in power limit state",
        9:  "Internal power supply abnormal",
        10:  "PV string abnormal",
        11:  "PV under voltage",
        12:  "PV irradiation weak",
        13:  "Grid abnormal",
        14:  "Arc fault detection",
        15:  "AC moving average voltage high",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x0024) — Bit field"""
    BITS = {
        0:  "Reserved",
        1:  "Logger/E-Display EEPROM fail",
        2:  "Reserved",
        3:  "Single tracker detect warning",
        4:  "AFCI lost",
        5:  "Data logger lost",
        6:  "Meter lost",
        7:  "Inverter lost",
        8:  "Grid N abnormal",
        9:  "Surge Protection Devices (SPD) defective",
        10:  "Parallel ID warning",
        11:  "Parallel SYN signal warning",
        12:  "Parallel BAT abnormal",
        13:  "Parallel GRID abnormal",
        14:  "Generator voltage abnormal",
        15:  "Reserved",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x0028) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x0052) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x0064) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x0065) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x0067) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x006E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode10:
    """Error Code Table10 (0x0070) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode11:
    """Error Code Table11 (0x0071) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class AbbStatusConverter:
    """ABB INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = AbbStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 2
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-2).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 2:
        raise ValueError(f"MPPT number must be 1-2, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-2)."""
    if tracker_num < 1 or tracker_num > 2:
        raise ValueError(f"Tracker number must be 1-2, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 2:
        raise ValueError(f"MPPT number must be 1-2, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'POWER_FACTOR': 'U16',
    'TEMPERATURE': 'U16',
    'L2_VOLTAGE': 'U16',
    'REACTIVE_POWER': 'U16',
    'DC_DC_START': 'U16',
    'GROUND_FAULT': 'U16',
    'OTH_FAULT': 'U16',
    'L1_VOLTAGE': 'U16',
    'L3_VOLTAGE': 'U16',
    'LEAK_FAULT': 'U16',
    'PV_POWER': 'U16',
    'INTERNAL_ERROR_E026': 'U16',
    'INTERNAL_ERROR_E027': 'U16',
    'INTERNAL_ERROR_E028': 'U16',
    'INTERNAL_ERROR_E029': 'U16',
    'INTERNAL_ERROR_E030': 'U16',
    'UTH_FAULT': 'U16',
    'TEMPERATURE_FAULT': 'U16',
    'INT_COM_FAULT': 'U16',
    'CUMULATIVE_ENERGY': 'U16',
    'FREQUENCY': 'U16',
    'PV_VOLTAGE': 'U16',
    'VREF_ERROR': 'U16',
    'FORBIDDEN_STATE': 'U16',
    'DAILY_ENERGY': 'U16',
    'L2_CURRENT': 'U16',
    'L3_CURRENT': 'U16',
    'ERROR_CODE1': 'U16',
    'BATTERY_LOW': 'U16',
    'ARC_FAULT_SELF_TEST_FAIL': 'U16',
    'ERROR_CODE2': 'U16',
    'ERROR_CODE3': 'U16',
    'COMMUNICATION_LOSS_WITH_COMMUNICATION_BOARD': 'U16',
    'ARC_FAULT_WRONG_CONFIGURATION': 'U16',
    'INVERTER_START_REGISTER': 'U16',
    'INVERTER_MAP_SIZE': 'U16',
    'INVERTER_SERIAL_NUMBER_SN0': 'ASCII',
    'INVERTER_SERIAL_NUMBER_SN1': 'ASCII',
    'INVERTER_SERIAL_NUMBER_SN2': 'ASCII',
    'INVERTER_SERIAL_NUMBER_SN3': 'ASCII',
    'INVERTER_SERIAL_NUMBER_SN4': 'ASCII',
    'INVERTER_SERIAL_NUMBER_SN5': 'ASCII',
    'L1_CURRENT': 'ASCII',
    'INVERTER_MODEL_IDENTIFIER': 'U16',
    'AC_POWER': 'U16',
    'INVERTER_STATES_BYTE_0_GLOBAL_STATE': 'U16',
    'INVERTER_STATES_BYTE_2_DC_DC_CHANNEL_1_STATE': 'U16',
    'INVERTER_STATES_BYTE_3_DC_DC_CHANNEL_2_STATE': 'U16',
    'INVERTER_STATES_BYTE_4_ALARM_STATE': 'U16',
    'DISPLAY_BOARD_PRESENCE_INDICATES_STATUS_OF_BOARD_TOINVERTER': 'U16',
    'INVERTER_PARTIAL_ENERGY': 'U16',
    'INVERTER_WEEK_ENERGY': 'U16',
    'INVERTER_FREQUENCY': 'U16',
    'INVERTER_INPUT_1_VOLTAGE': 'U16',
    'INVERTER_INPUT_1_CURRENT': 'U16',
    'INVERTER_INPUT_2_POWER': 'U16',
    'INVERTER_INPUT_2_VOLTAGE': 'U16',
    'INVERTER_PRESENCE_INDICATES_STATUS_OF_BOARD_TO_INVERTER': 'U16',
    'REMOTE_ON_OFF': 'U16',
    'RESET_BY_HAND': 'U16',
    'DYNAMIC_MODE_REACTIVE_POWERMANAGEMENT_BY_FIXED_PF': 'U16',
    'PERMANENT_MODE_REACTIVE_POWER_MANAGEMENT_BY_FIXED_PF': 'U16',
    'PERMANENT_MODE_RESET_PF_TO_1': 'U16',
    'PERMANENT_MODE_REACTIVE': 'U16',
    'AUXILIARY_BOARDS_START_REGISTER': 'U16',
    'AUXILIARY_BOARD_MAP_SIZE': 'U16',
    'COMMUNICATION_BOARD_SERIAL_NUMBER_SN0': 'ASCII',
    'COMMUNICATION_BOARD_SERIAL_NUMBER_SN1': 'ASCII',
    'COMMUNICATION_BOARD_SERIAL_NUMBER_SN2': 'ASCII',
    'COMMUNICATION_BOARD_SERIAL_NUMBER_SN3': 'ASCII',
    'COMMUNICATION_BOARD_SERIAL_NUMBER_SN4': 'ASCII',
    'COMMUNICATION_BOARD_SERIAL_NUMBER_SN5': 'ASCII',
    'FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN0': 'U16',
    'FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN1': 'U16',
    'FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN2': 'U16',
    'FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN3': 'U16',
    'FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN4': 'U16',
    'FUSE_CONTROL_BOARD_SERIAL_NUMBER_SN5': 'U16',
    'FUSE_CONTROL_BOARD_STATES_BYTE_2': 'U16',
    'DYNAMIC_MODE_REACTIVE_POWERMANAGEMENT_SET_FIXED_Q_BYPERCENTAGE_OF_NOMINAL_POWER_P_IN_1_STEPS_NOM': 'U16',
    'DYNAMIC_MODE_ACTIVE_POWERMANAGEMENT_SET_ACTIVE_POWEREXPRESSED_AS_PERCENTAGE_OF_NOMINAL_POWER_P_IN_1_STEPS_NOM': 'U16',
    'PERMANENT_MODE_ACTIVE_POWERMANAGEMENT_SET_ACTIVE_POWEREXPRESSED_AS_PERCENTAGE_OF_NOMINAL_POWER_P_IN_1_STEPS_NOM': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0000, 'count': 125, 'fc': 3},
    {'start': 0x007D, 'count': 125, 'fc': 3},
    {'start': 0x00FA, 'count':   2, 'fc': 3},
    {'start': 0x012D, 'count':  12, 'fc': 3},
    {'start': 0x01FF, 'count':   3, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'DC_DC_START',
    's_voltage           ': 'L2_VOLTAGE',
    't_voltage           ': 'L3_VOLTAGE',
    'r_current           ': 'VREF_ERROR',
    's_current           ': 'L2_CURRENT',
    't_current           ': 'L3_CURRENT',
    'frequency           ': 'LEAK_FAULT',
    'ac_power            ': 'AC_POWER',
    'temperature         ': 'TEMPERATURE',
    'cumulative_energy   ': 'CUMULATIVE_ENERGY',
    'alarm1              ': 'ERROR_CODE1',
    'mppt1_voltage'        : 'PV_VOLTAGE',
    'mppt1_current'        : 'MPPT1_CURRENT',
    'mppt2_voltage'        : 'MPPT2_VOLTAGE',
    'mppt2_current'        : 'MPPT2_CURRENT',
}
