# -*- coding: utf-8 -*-
"""
CPS Inverter Modbus Register Map
Based on CPS Modbus Protocol 
Protocol Name: cps_sca_m
MPPT: 4 | Strings: 8 (2/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-09
"""



class RegisterMap:
    """CPS Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    PHASE_A_POWER                            = 0x1003  # U32, scale W 0.1
    PHASE_A_POWER_HIGH                       = 0x1004
    PHASE_B_POWER                            = 0x1008  # U32, scale W 0.1
    PHASE_B_POWER_HIGH                       = 0x1009
    PHASE_B_FREQUENCY                        = 0x100A  # U16, scale Hz 0.01
    PHASE_C_POWER                            = 0x100D  # U32, scale W 0.1
    PHASE_C_POWER_HIGH                       = 0x100E
    PHASE_C_FREQUENCY                        = 0x100F  # U16, scale Hz 0.01
    INNER_TEMP                               = 0x101C  # S16, scale °C 1
    DAILY_ENERGY                             = 0x1027  # U32, scale Wh 1
    DAILY_ENERGY_HIGH                        = 0x1028
    DEVICE_MODEL                             = 0x1A00  # STRING, scale 1
    DEVICE_SERIAL_NUMBER                     = 0x1A10  # STRING, scale 1
    FIRMWARE_VERSION                         = 0x1A1C  # STRING, scale 1
    NOMINAL_POWER                            = 0x1A46  # U16, scale W 1
    GRID_PHASE_NUMBER                        = 0x1A48  # U16, scale 1

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    L1_VOLTAGE                               = 0x1001  # U16, scale V 0.1
    L1_CURRENT                               = 0x1002  # U16, scale A 0.01
    FREQUENCY                                = 0x1005  # U16, scale Hz 0.01
    L2_VOLTAGE                               = 0x1006  # U16, scale V 0.1
    L2_CURRENT                               = 0x1007  # U16, scale A 0.01
    L3_VOLTAGE                               = 0x100B  # U16, scale V 0.1
    L3_CURRENT                               = 0x100C  # U16, scale A 0.01
    PV1_VOLTAGE                              = 0x1010  # U16, scale V 0.1
    PV1_CURRENT                              = 0x1011  # U16, scale A 0.01
    MPPT1_POWER                              = 0x1012  # U32, scale W 0.1
    MPPT1_POWER_HIGH                         = 0x1013
    PV2_VOLTAGE                              = 0x1014  # U16, scale V 0.1
    PV2_CURRENT                              = 0x1015  # U16, scale A 0.01
    MPPT2_POWER                              = 0x1016  # U32, scale W 0.1
    MPPT2_POWER_HIGH                         = 0x1017
    PV3_VOLTAGE                              = 0x1018  # U16, scale V 0.1
    PV3_CURRENT                              = 0x1019  # U16, scale A 0.01
    MPPT3_POWER                              = 0x101A  # U32, scale W 0.1
    MPPT3_POWER_HIGH                         = 0x101B
    CUMULATIVE_ENERGY                        = 0x1021  # U32, scale kWh 1
    CUMULATIVE_ENERGY_HIGH                   = 0x1022
    TOTAL_GENERATION_TIME                    = 0x1023  # U32, scale Hour 1
    TOTAL_GENERATION_TIME_HIGH               = 0x1024
    AC_POWER                                 = 0x1037  # U32, scale W 0.1
    AC_POWER_HIGH                            = 0x1038
    REACTIVE_POWER                           = 0x1039  # S32, scale Var 0.1
    REACTIVE_POWER_HIGH                      = 0x103A
    TODAY_PEAK_POWER                         = 0x103B  # U32, scale W 0.1
    TODAY_PEAK_POWER_HIGH                    = 0x103C
    POWER_FACTOR                             = 0x103D  # U16, scale 0.001
    PV4_VOLTAGE                              = 0x103E  # U16, scale V 0.1
    PV4_CURRENT                              = 0x103F  # U16, scale A 0.01
    MPPT4_POWER                              = 0x1040  # U32, scale W 0.1
    MPPT4_POWER_HIGH                         = 0x1041
    MODBUS_PROTOCOL_VERSION                  = 0x1A18  # U16, scale 1
    SOFTWARE_BUILD_DATE                      = 0x1A23  # STRING, scale 1
    MPPT_NUMBER                              = 0x1A3B  # U16, scale 1
    RATED_VOLTAGE                            = 0x1A44  # U16, scale V 0.1
    RATED_FREQUENCY                          = 0x1A45  # U16, scale Hz 0.01

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    INVERTER_MODE                            = 0x101D  # U16, scale 1

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    ERROR_CODE2                              = 0x101E  # U32, scale 1
    ERROR_CODE2_HIGH                         = 0x101F

    # =========================================================================
    # DEA-AVM Real-time Data
    # =========================================================================
    DEA_L1_CURRENT_LOW                       = 0x03E8  # S32, scale 0.1, A
    DEA_L1_CURRENT_HIGH                      = 0x03E9
    DEA_L2_CURRENT_LOW                       = 0x03EA  # S32, scale 0.1, A
    DEA_L2_CURRENT_HIGH                      = 0x03EB
    DEA_L3_CURRENT_LOW                       = 0x03EC  # S32, scale 0.1, A
    DEA_L3_CURRENT_HIGH                      = 0x03ED
    DEA_L1_VOLTAGE_LOW                       = 0x03EE  # S32, scale 0.1, V
    DEA_L1_VOLTAGE_HIGH                      = 0x03EF
    DEA_L2_VOLTAGE_LOW                       = 0x03F0  # S32, scale 0.1, V
    DEA_L2_VOLTAGE_HIGH                      = 0x03F1
    DEA_L3_VOLTAGE_LOW                       = 0x03F2  # S32, scale 0.1, V
    DEA_L3_VOLTAGE_HIGH                      = 0x03F3
    DEA_TOTAL_ACTIVE_POWER_LOW               = 0x03F4  # S32, scale 0.1, kW
    DEA_TOTAL_ACTIVE_POWER_HIGH              = 0x03F5
    DEA_TOTAL_REACTIVE_POWER_LOW             = 0x03F6  # S32, scale 1, Var
    DEA_TOTAL_REACTIVE_POWER_HIGH            = 0x03F7
    DEA_POWER_FACTOR_LOW                     = 0x03F8  # S32, scale 0.001
    DEA_POWER_FACTOR_HIGH                    = 0x03F9
    DEA_FREQUENCY_LOW                        = 0x03FA  # S32, scale 0.1, Hz
    DEA_FREQUENCY_HIGH                       = 0x03FB
    DEA_STATUS_FLAG_LOW                      = 0x03FC  # S32, scale 1
    DEA_STATUS_FLAG_HIGH                     = 0x03FD

    # --- H01 표준 alias (h01_field 매칭 결과 직접 사용) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE  # h01_field=r_voltage
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # h01_field=s_voltage
    T_PHASE_VOLTAGE                          = L3_VOLTAGE  # h01_field=t_voltage
    R_PHASE_CURRENT                          = L1_CURRENT  # h01_field=r_current
    S_PHASE_CURRENT                          = L2_CURRENT  # h01_field=s_current
    T_PHASE_CURRENT                          = L3_CURRENT  # h01_field=t_current
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY  # h01_field=cumulative_energy
    ERROR_CODE1                              = ERROR_CODE2  # h01_field=alarm1
    ERROR_CODE3                              = ERROR_CODE2  # h01_field=alarm3

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    MPPT1_VOLTAGE                            = PV1_VOLTAGE
    MPPT1_CURRENT                            = PV1_CURRENT
    MPPT2_VOLTAGE                            = PV2_VOLTAGE
    MPPT2_CURRENT                            = PV2_CURRENT
    MPPT3_VOLTAGE                            = PV3_VOLTAGE
    MPPT3_CURRENT                            = PV3_CURRENT
    MPPT4_VOLTAGE                            = PV4_VOLTAGE
    MPPT4_CURRENT                            = PV4_CURRENT
    PV_VOLTAGE                               = MPPT1_VOLTAGE
    PV_STRING_COUNT                          = 8
    SERIAL_NUMBER                            = DEVICE_SERIAL_NUMBER
    MPPT_COUNT                               = 4
    NOMINAL_POWER_LOW                        = 0x0017
    NOMINAL_POWER_HIGH                       = 0x0018

    # --- RTU modbus_handler / simulator 필수 alias ---
    PV_POWER                                 = AC_POWER  # fallback: PV 전용 측정 없음 → AC_POWER
    STRING1_VOLTAGE                          = MPPT1_VOLTAGE  # fallback: STRING1 전압 = MPPT1 전압
    STRING2_VOLTAGE                          = MPPT1_VOLTAGE  # fallback: STRING2 전압 = MPPT1 전압
    STRING3_VOLTAGE                          = MPPT2_VOLTAGE  # fallback: STRING3 전압 = MPPT2 전압
    STRING4_VOLTAGE                          = MPPT2_VOLTAGE  # fallback: STRING4 전압 = MPPT2 전압
    STRING5_VOLTAGE                          = MPPT3_VOLTAGE  # fallback: STRING5 전압 = MPPT3 전압
    STRING6_VOLTAGE                          = MPPT3_VOLTAGE  # fallback: STRING6 전압 = MPPT3 전압
    STRING7_VOLTAGE                          = MPPT4_VOLTAGE  # fallback: STRING7 전압 = MPPT4 전압
    STRING8_VOLTAGE                          = MPPT4_VOLTAGE  # fallback: STRING8 전압 = MPPT4 전압
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834
    CUMULATIVE_ENERGY_LOW                    = CUMULATIVE_ENERGY
    DER_AVM_DIGITAL_METERCONNECT_STATUS      = 0x1210



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x101E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class CpsStatusConverter:
    """CPS INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw

    @classmethod
    def to_solarize(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)

    @classmethod
    def to_h01(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = CpsStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 4
STRING_CHANNELS = 8


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-8).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 8:
        raise ValueError(f"String number must be 1-8, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-4).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-4)."""
    if tracker_num < 1 or tracker_num > 4:
        raise ValueError(f"Tracker number must be 1-4, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-2)."""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if string_num < 1 or string_num > 2:
        raise ValueError(f"String number must be 1-2 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=8, strings_per_mppt=2):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'DEA_L1_CURRENT_LOW': 'S32',
    'DEA_L2_CURRENT_LOW': 'S32',
    'DEA_L3_CURRENT_LOW': 'S32',
    'DEA_L1_VOLTAGE_LOW': 'S32',
    'DEA_L2_VOLTAGE_LOW': 'S32',
    'DEA_L3_VOLTAGE_LOW': 'S32',
    'DEA_TOTAL_ACTIVE_POWER_LOW': 'S32',
    'DEA_TOTAL_REACTIVE_POWER_LOW': 'S32',
    'DEA_POWER_FACTOR_LOW': 'S32',
    'DEA_FREQUENCY_LOW': 'S32',
    'DEA_STATUS_FLAG_LOW': 'S32',
    'L1_VOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'PHASE_A_POWER': 'U32',
    'FREQUENCY': 'U16',
    'L2_VOLTAGE': 'U16',
    'L2_CURRENT': 'U16',
    'PHASE_B_POWER': 'U32',
    'PHASE_B_FREQUENCY': 'U16',
    'L3_VOLTAGE': 'U16',
    'L3_CURRENT': 'U16',
    'PHASE_C_POWER': 'U32',
    'PHASE_C_FREQUENCY': 'U16',
    'PV1_VOLTAGE': 'U16',
    'PV1_CURRENT': 'U16',
    'MPPT1_POWER': 'U32',
    'PV2_VOLTAGE': 'U16',
    'PV2_CURRENT': 'U16',
    'MPPT2_POWER': 'U32',
    'PV3_VOLTAGE': 'U16',
    'PV3_CURRENT': 'U16',
    'MPPT3_POWER': 'U32',
    'INNER_TEMP': 'S16',
    'INVERTER_MODE': 'U16',
    'ERROR_CODE2': 'U32',
    'CUMULATIVE_ENERGY': 'U32',
    'TOTAL_GENERATION_TIME': 'U32',
    'DAILY_ENERGY': 'U32',
    'AC_POWER': 'U32',
    'REACTIVE_POWER': 'S32',
    'TODAY_PEAK_POWER': 'U32',
    'POWER_FACTOR': 'U16',
    'PV4_VOLTAGE': 'U16',
    'PV4_CURRENT': 'U16',
    'MPPT4_POWER': 'U32',
    'DEVICE_MODEL': 'STRING',
    'DEVICE_SERIAL_NUMBER': 'STRING',
    'MODBUS_PROTOCOL_VERSION': 'U16',
    'FIRMWARE_VERSION': 'STRING',
    'SOFTWARE_BUILD_DATE': 'STRING',
    'MPPT_NUMBER': 'U16',
    'RATED_VOLTAGE': 'U16',
    'RATED_FREQUENCY': 'U16',
    'NOMINAL_POWER': 'U16',
    'GRID_PHASE_NUMBER': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x1001, 'count':  65, 'fc': 3},
    {'start': 0x1A18, 'count':  46, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'L1_VOLTAGE',
    's_voltage           ': 'L2_VOLTAGE',
    't_voltage           ': 'L3_VOLTAGE',
    'r_current           ': 'L1_CURRENT',
    's_current           ': 'L2_CURRENT',
    't_current           ': 'L3_CURRENT',
    'frequency           ': 'DEA_FREQUENCY',
    'ac_power            ': 'DEA_TOTAL_ACTIVE_POWER',
    'cumulative_energy   ': 'CUMULATIVE_ENERGY',
    'alarm1              ': 'ERROR_CODE2',
    'mppt1_voltage'        : 'PV1_VOLTAGE',
    'mppt1_current'        : 'PV1_CURRENT',
    'mppt2_voltage'        : 'PV2_VOLTAGE',
    'mppt2_current'        : 'PV2_CURRENT',
    'mppt3_voltage'        : 'PV3_VOLTAGE',
    'mppt3_current'        : 'PV3_CURRENT',
    'mppt4_voltage'        : 'PV4_VOLTAGE',
    'mppt4_current'        : 'PV4_CURRENT',
    'string1_voltage'      : 'STRING1_VOLTAGE',
    'string1_current'      : 'STRING1_CURRENT',
    'string2_voltage'      : 'STRING2_VOLTAGE',
    'string2_current'      : 'STRING2_CURRENT',
    'string3_voltage'      : 'STRING3_VOLTAGE',
    'string3_current'      : 'STRING3_CURRENT',
    'string4_voltage'      : 'STRING4_VOLTAGE',
    'string4_current'      : 'STRING4_CURRENT',
    'string5_voltage'      : 'STRING5_VOLTAGE',
    'string5_current'      : 'STRING5_CURRENT',
    'string6_voltage'      : 'STRING6_VOLTAGE',
    'string6_current'      : 'STRING6_CURRENT',
    'string7_voltage'      : 'STRING7_VOLTAGE',
    'string7_current'      : 'STRING7_CURRENT',
    'string8_voltage'      : 'STRING8_VOLTAGE',
    'string8_current'      : 'STRING8_CURRENT',
}



# H01 스칼라 필드 → (RegisterMap 속성명, 변환기 키)
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
H01_FIELD_MAP = {
    'mode                ': ('INVERTER_MODE', 'raw'),
    'r_voltage           ': ('L1_VOLTAGE', 'voltage_to_V'),  # user
    's_voltage           ': ('L2_VOLTAGE', 'voltage_to_V'),  # user
    't_voltage           ': ('L3_VOLTAGE', 'voltage_to_V'),  # user
    'r_current           ': ('L1_CURRENT', 'current_to_01A'),  # user
    's_current           ': ('L2_CURRENT', 'current_to_01A'),  # user
    't_current           ': ('L3_CURRENT', 'current_to_01A'),  # user
    'frequency           ': ('FREQUENCY', 'frequency_to_01Hz'),
    'ac_power            ': ('AC_POWER', 'power_to_W'),
    'pv_power            ': ('PV_POWER', 'power_to_W'),
    'inner_temp          ': ('INNER_TEMP', 'raw'),
    'power_factor        ': ('POWER_FACTOR', 'pf_raw'),
    'cumulative_energy   ': ('CUMULATIVE_ENERGY', 'energy_kwh_to_Wh'),  # user
    'alarm1              ': ('ERROR_CODE2', 'raw'),  # user
    'alarm2              ': ('ERROR_CODE2', 'raw'),  # user
    'alarm3              ': ('ERROR_CODE2', 'raw'),  # user
}
