# -*- coding: utf-8 -*-
"""
EG4 Inverter Modbus Register Map
Based on EG4 Modbus Protocol 
Protocol Name: eg4
MPPT: 3 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04
"""



class RegisterMap:
    """EG4 Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    DEVICE_MODEL_PDF                         = 0x0000  # TEXT
    SN6_PRODUCT_CODE                         = 0x0005  # U16
    BUS_VOLTAGE_HIGH                         = 0x0013  # U16
    VEPS_R                                   = 0x0014  # U16, scale V 0.1
    PEPS                                     = 0x0018  # U16
    L2_VOLTAGE                               = 0x0019  # U16
    L3_VOLTAGE                               = 0x001E  # U16, scale kWh 0.1
    DAILY_ENERGY                             = 0x001F  # U16, scale kWh 0.1
    RUNNING_TIME_H                           = 0x0046  # U16
    DISCHG_POWER_PERCENT_CMD                 = 0x008B  # U16, scale % 0.1

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    STATE                                    = 0x0000  # U16
    VPV1                                     = 0x0001  # U16, scale V 0.1
    VPV2                                     = 0x0002  # U16, scale V 0.1
    VPV3                                     = 0x0003  # U16, scale V 0.1
    REACTIVE_POWER                           = 0x0003  # U16
    SLAVE_READ_ANDWRITE_FAILURE              = 0x0004  # U16
    PPV1                                     = 0x0007  # U16
    PPV2                                     = 0x0008  # U16
    PPV3                                     = 0x0009  # U16
    L1_VOLTAGE                               = 0x000C  # U16, scale V 0.1
    FREQUENCY                                = 0x000F  # U16, scale Hz 0.01
    PV_POWER                                 = 0x0010  # U16
    TEMPERATURE                              = 0x0020  # U16, scale kWh 0.1
    L1_CURRENT                               = 0x0027  # U16
    L2_CURRENT                               = 0x0029  # U16, scale kWh 0.1
    CUMULATIVE_ENERGY                        = 0x002E  # U16, scale kWh 0.1
    EDISCHG_ALL_L                            = 0x0034  # U16, scale kWh 0.1
    EDISCHG_ALL_H                            = 0x0035  # U16, scale kWh 0.1
    ETOUSER_ALL_L                            = 0x003A  # U16, scale kWh 0.1
    MPPT3_CURRENT                            = 0x0047  # U16
    W_AUTO_TEST_LIMIT                        = 0x0048  # U16
    UW_AUTO_TEST_TRIP_VALUE                  = 0x004A  # U16
    UW_AUTO_TEST_TRIP_TIME                   = 0x004B  # U16
    ACINPUT_TYPE                             = 0x004D  # U16
    CHG_FIRST_START_HOUR2                    = 0x0050  # U16
    CHARGE_VOLT_REF                          = 0x0053  # U16, scale V 0.1
    BAT_STATUS1_BMS                          = 0x0056  # U16
    BAT_STATUS8_BMS                          = 0x005D  # U16
    BAT_STATUS9_BMS                          = 0x005E  # U16
    MIN_CELL_TEMP_BMS                        = 0x0068  # U16, scale ℃ 0.1
    AC_POWER                                 = 0x0076  # U16, scale V 0.1
    VBUS_P                                   = 0x0078  # U16, scale V 0.1
    GEN_POWER                                = 0x007B  # U16
    EGEN_DAY                                 = 0x007C  # U16, scale kWh 0.1
    EGEN_ALL_H                               = 0x007E  # U16, scale kWh 0.1
    EPSVOLT_L1N                              = 0x007F  # U16, scale V 0.1
    PEPS_L1N                                 = 0x0081  # U16
    EEPS_L1N_ALL_H                           = 0x0088  # U16, scale kWh 0.1
    EEPS_L2N_ALL_L                           = 0x0089  # U16, scale kWh 0.1
    EEPS_L2N_ALL_H                           = 0x008A  # U16, scale kWh 0.1
    AFCI_CURR_CH4                            = 0x008F  # U16
    AFCI_MAX_ARC_CH1                         = 0x0095  # U16
    AFCI_MAX_ARC_CH2                         = 0x0096  # U16
    AFCI_MAX_ARC_CH3                         = 0x0097  # U16
    ACCHG_END_VOLT                           = 0x009F  # U16, scale V 0.1
    BAT_LOWTO_UTILITY_SOC                    = 0x00A7  # U16
    ONGRID_EOD_VOLTAGE                       = 0x00A9  # U16, scale V 0.1
    SOCCURVE_BAT_VOLT1                       = 0x00AB  # U16, scale V 0.1
    SOCCURVE_SOC1                            = 0x00AD  # U16, scale % 1
    SOCCURVE_SOC2                            = 0x00AE  # U16, scale % 1
    SOCCURVE_INNER_RESISTANCE                = 0x00AF  # U16
    MAX_GRID_INPUT_POWER                     = 0x00B0  # U16, scale W
    GEN_RATE_POWER                           = 0x00B1  # U16, scale W
    U_FUNCTION_EN2_ACCTDIRECTION             = 0x00B3  # U16
    AFCIARC_THRESHOLD                        = 0x00B4  # U16
    VOLT_WATT_V1                             = 0x00B5  # U16, scale V 0.1
    VOLT_WATT_P2                             = 0x00B8  # U16
    VREF_QV                                  = 0x00B9  # U16, scale V 0.1
    POWER_FACTOR                             = 0x00BD  # U16

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    BAT_STATUS2_BMS                          = 0x0057  # U16
    BAT_STATUS3_BMS                          = 0x0058  # U16
    BAT_STATUS4_BMS                          = 0x0059  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    ACCHG_END_HOUR                           = 0x0045  # U16
    BAT_STATUS6_BMS                          = 0x005B  # U16
    WARNING_CODE_BMS                         = 0x0064  # U16
    CHARGE_CURR                              = 0x0065  # U16
    BMSFWUPDATE_STATE                        = 0x0069  # U16
    CYCLE_CNT_BMS                            = 0x006A  # U16
    CLEAR_FUNCTION                           = 0x0072  # U16

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # L2 없음 → 대체

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_VOLTAGE                               = L1_VOLTAGE
    PV_STRING_COUNT                          = 3

    # --- RTU modbus_handler / simulator 필수 alias ---
    INNER_TEMP                               = TEMPERATURE
    T_PHASE_CURRENT                          = S_PHASE_CURRENT  # L3 없음 → 단상 대체
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    ERROR_CODE1                              = L2_VOLTAGE
    ERROR_CODE2                              = L2_VOLTAGE
    ERROR_CODE3                              = FREQUENCY
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x000D) — Bit field"""
    BITS = {
        0:  "Inverter over dc-bias current",
        1:  "Inverter relay abnormal",
        2:  "Remote off",
        3:  "Inverter over temperature",
        4:  "GFCI abnormal",
        5:  "PV string reverse",
        6:  "System type error",
        7:  "Fan abnormal",
        8:  "Dc-link unbalance or under voltage",
        9:  "Dc-link over voltage",
        10:  "Internal communication error",
        11:  "Software incompatibility",
        12:  "Internal storage error",
        13:  "Data inconsistency",
        14:  "Inverter abnormal",
        15:  "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x001D) — Bit field"""
    BITS = {
        0:  "Grid over voltage",
        1:  "Grid under voltage",
        2:  "Grid absent",
        3:  "Grid over frequency",
        4:  "Grid under frequency",
        5:  "PV over voltage",
        6:  "PV insulation abnormal",
        7:  "Leakage current abnormal",
        8:  "Inverter in power limit state",
        9:  "Internal power supply abnormal",
        10:  "PV string abnormal",
        11:  "PV under voltage",
        12:  "PV irradiation weak",
        13:  "Grid abnormal",
        14:  "Arc fault detection",
        15:  "AC moving average voltage high",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x0025) — Bit field"""
    BITS = {
        0:  "Reserved",
        1:  "Logger/E-Display EEPROM fail",
        2:  "Reserved",
        3:  "Single tracker detect warning",
        4:  "AFCI lost",
        5:  "Data logger lost",
        6:  "Meter lost",
        7:  "Inverter lost",
        8:  "Grid N abnormal",
        9:  "Surge Protection Devices (SPD) defective",
        10:  "Parallel ID warning",
        11:  "Parallel SYN signal warning",
        12:  "Parallel BAT abnormal",
        13:  "Parallel GRID abnormal",
        14:  "Generator voltage abnormal",
        15:  "Reserved",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x0028) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x0045) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x005B) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x0064) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x0065) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x0066) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode10:
    """Error Code Table10 (0x0067) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode11:
    """Error Code Table11 (0x0069) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode12:
    """Error Code Table12 (0x006A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode13:
    """Error Code Table13 (0x006D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode14:
    """Error Code Table14 (0x006E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode15:
    """Error Code Table15 (0x0070) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode16:
    """Error Code Table16 (0x0071) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode17:
    """Error Code Table17 (0x0072) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode18:
    """Error Code Table18 (0x0084) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class Eg4StatusConverter:
    """EG4 INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = Eg4StatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 3
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-3).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 3:
        raise ValueError(f"MPPT number must be 1-3, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-3)."""
    if tracker_num < 1 or tracker_num > 3:
        raise ValueError(f"Tracker number must be 1-3, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 3:
        raise ValueError(f"MPPT number must be 1-3, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'DEVICE_MODEL_PDF': 'TEXT',
    'STATE': 'U16',
    'VPV1': 'U16',
    'L2_VOLTAGE': 'U16',
    'VPV2': 'U16',
    'VPV3': 'U16',
    'REACTIVE_POWER': 'U16',
    'SLAVE_READ_ANDWRITE_FAILURE': 'U16',
    'SN6_PRODUCT_CODE': 'U16',
    'PPV1': 'U16',
    'PPV2': 'U16',
    'PPV3': 'U16',
    'L1_VOLTAGE': 'U16',
    'L3_VOLTAGE': 'U16',
    'FREQUENCY': 'U16',
    'PV_POWER': 'U16',
    'BUS_VOLTAGE_HIGH': 'U16',
    'VEPS_R': 'U16',
    'PEPS': 'U16',
    'DAILY_ENERGY': 'U16',
    'TEMPERATURE': 'U16',
    'L1_CURRENT': 'U16',
    'L2_CURRENT': 'U16',
    'CUMULATIVE_ENERGY': 'U16',
    'EDISCHG_ALL_L': 'U16',
    'EDISCHG_ALL_H': 'U16',
    'ETOUSER_ALL_L': 'U16',
    'ACCHG_END_HOUR': 'U16',
    'RUNNING_TIME_H': 'U16',
    'MPPT3_CURRENT': 'U16',
    'W_AUTO_TEST_LIMIT': 'U16',
    'UW_AUTO_TEST_TRIP_VALUE': 'U16',
    'UW_AUTO_TEST_TRIP_TIME': 'U16',
    'ACINPUT_TYPE': 'U16',
    'CHG_FIRST_START_HOUR2': 'U16',
    'CHARGE_VOLT_REF': 'U16',
    'BAT_STATUS1_BMS': 'U16',
    'BAT_STATUS2_BMS': 'U16',
    'BAT_STATUS3_BMS': 'U16',
    'BAT_STATUS4_BMS': 'U16',
    'BAT_STATUS6_BMS': 'U16',
    'BAT_STATUS8_BMS': 'U16',
    'BAT_STATUS9_BMS': 'U16',
    'WARNING_CODE_BMS': 'U16',
    'CHARGE_CURR': 'U16',
    'MIN_CELL_TEMP_BMS': 'U16',
    'BMSFWUPDATE_STATE': 'U16',
    'CYCLE_CNT_BMS': 'U16',
    'CLEAR_FUNCTION': 'U16',
    'AC_POWER': 'U16',
    'VBUS_P': 'U16',
    'GEN_POWER': 'U16',
    'EGEN_DAY': 'U16',
    'EGEN_ALL_H': 'U16',
    'EPSVOLT_L1N': 'U16',
    'PEPS_L1N': 'U16',
    'EEPS_L1N_ALL_H': 'U16',
    'EEPS_L2N_ALL_L': 'U16',
    'EEPS_L2N_ALL_H': 'U16',
    'DISCHG_POWER_PERCENT_CMD': 'U16',
    'AFCI_CURR_CH4': 'U16',
    'AFCI_MAX_ARC_CH1': 'U16',
    'AFCI_MAX_ARC_CH2': 'U16',
    'AFCI_MAX_ARC_CH3': 'U16',
    'ACCHG_END_VOLT': 'U16',
    'BAT_LOWTO_UTILITY_SOC': 'U16',
    'ONGRID_EOD_VOLTAGE': 'U16',
    'SOCCURVE_BAT_VOLT1': 'U16',
    'SOCCURVE_SOC1': 'U16',
    'SOCCURVE_SOC2': 'U16',
    'SOCCURVE_INNER_RESISTANCE': 'U16',
    'MAX_GRID_INPUT_POWER': 'U16',
    'GEN_RATE_POWER': 'U16',
    'U_FUNCTION_EN2_ACCTDIRECTION': 'U16',
    'AFCIARC_THRESHOLD': 'U16',
    'VOLT_WATT_V1': 'U16',
    'VOLT_WATT_P2': 'U16',
    'VREF_QV': 'U16',
    'POWER_FACTOR': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0000, 'count': 125, 'fc': 3},
    {'start': 0x007D, 'count':  69, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'SLAVE_READ_ANDWRITE_FAILURE',
    's_voltage           ': 'L2_VOLTAGE',
    't_voltage           ': 'L3_VOLTAGE',
    'r_current           ': 'L1_CURRENT',
    's_current           ': 'L2_CURRENT',
    't_current           ': 'T_PHASE_CURRENT',
    'frequency           ': 'FREQUENCY',
    'ac_power            ': 'AC_POWER',
    'temperature         ': 'TEMPERATURE',
    'cumulative_energy   ': 'CUMULATIVE_ENERGY',
    'alarm1              ': 'ERROR_CODE1',
    'mppt1_voltage'        : 'VPV1',
    'mppt1_current'        : 'MPPT1_CURRENT',
    'mppt2_voltage'        : 'VPV2',
    'mppt2_current'        : 'MPPT2_CURRENT',
    'mppt3_voltage'        : 'VPV3',
    'mppt3_current'        : 'MPPT3_CURRENT',
}
