# -*- coding: utf-8 -*-
"""
GoodWe Inverter Modbus Register Map
Based on GoodWe Modbus Protocol (Grid-tied MTG2/SMT/SDTG2/MS/DNS/XS series)
Protocol Name: goodwe
MPPT: 2 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04
"""


class RegisterMap:
    """GoodWe inverter register addresses (decimal addresses converted to hex)."""

    # ── Device Information ───────────────────────────────────────────────────
    SERIAL_NUMBER       = 0x0200   # addr 512, 8 words ASCII

    # ── Error / Warning ──────────────────────────────────────────────────────
    ERROR_CODE1         = 0x0220   # addr 544, Error message Hi (U32 part 1 of 2)
    ERROR_CODE2         = 0x0221   # addr 545, Error message Lo (U32 part 2 of 2)

    # ── Total Energy (U32, Hi then Lo) ───────────────────────────────────────
    TOTAL_ENERGY_HI     = 0x0222   # addr 546, scale 0.1 kWh (Hi byte)
    TOTAL_ENERGY_LO     = 0x0223   # addr 547, scale 0.1 kWh (Lo byte)

    # ── PV (DC) Input ────────────────────────────────────────────────────────
    PV1_VOLTAGE         = 0x0226   # addr 550, scale 0.1 V
    PV2_VOLTAGE         = 0x0227   # addr 551, scale 0.1 V
    PV1_CURRENT         = 0x0228   # addr 552, scale 0.1 A
    PV2_CURRENT         = 0x0229   # addr 553, scale 0.1 A

    # ── AC Output ────────────────────────────────────────────────────────────
    L1_VOLTAGE          = 0x022A   # addr 554, scale 0.1 V
    L2_VOLTAGE          = 0x022B   # addr 555, scale 0.1 V
    L3_VOLTAGE          = 0x022C   # addr 556, scale 0.1 V
    L1_CURRENT          = 0x022D   # addr 557, scale 0.1 A
    L2_CURRENT          = 0x022E   # addr 558, scale 0.1 A
    L3_CURRENT          = 0x022F   # addr 559, scale 0.1 A
    FREQUENCY           = 0x0230   # addr 560, scale 0.01 Hz

    # ── Power ────────────────────────────────────────────────────────────────
    AC_POWER_LO         = 0x0233   # addr 563, scale 1 W (Lo word of S32)
    WORK_MODE           = 0x0234   # addr 564, WorkMode register
    TEMPERATURE         = 0x0235   # addr 565, scale 0.1 °C
    DAILY_ENERGY        = 0x0236   # addr 566, scale 0.1 kWh

    # ── Extended registers (MT/SMT range: 768–890) ───────────────────────────
    FIRMWARE_VERSION    = 0x0316   # addr 790
    WARNING_CODE        = 0x0317   # addr 791
    AC_POWER_HI         = 0x0356   # addr 854, scale 1 W (Hi word of S32)
    PV3_VOLTAGE         = 0x0357   # addr 855, scale 0.1 V
    PV4_VOLTAGE         = 0x0358   # addr 856, scale 0.1 V
    PV3_CURRENT         = 0x0359   # addr 857, scale 0.1 A
    PV4_CURRENT         = 0x035A   # addr 858, scale 0.1 A
    POWER_FACTOR        = 0x0376   # addr 886, scale 0.001
    AC_REACTIVE_HI      = 0x037D   # addr 893, reactive power Hi
    AC_REACTIVE_LO      = 0x037E   # addr 894, reactive power Lo

    # ── DER Control Registers (FC10H Write) ──────────────────────────────────
    DER_ACTIVE_POWER_PCT    = 0x0100   # addr 256, Active power limit %
    INVERTER_ON_OFF         = 0x0121   # addr 289, PowerOff (288=0x0120 PowerOn)
    DER_POWER_FACTOR_SET    = 0x07D0   # addr 2000, Power factor setting scale 0.001
    DER_ACTION_MODE         = 0x07D1   # addr 2001, Work mode: 0=separate, 2=power rate, 5=Q(V)
    DER_REACTIVE_POWER_PCT  = 0x07D2   # addr 2002, Constant reactive power
    DER_ACTIVE_POWER_CONST  = 0x07D3   # addr 2003, Constant active power

    # ── R/S/T Phase Aliases ───────────────────────────────────────────────────
    R_VOLTAGE = L1_VOLTAGE
    R_CURRENT = L1_CURRENT
    S_VOLTAGE = L2_VOLTAGE
    S_CURRENT = L2_CURRENT
    T_VOLTAGE = L3_VOLTAGE
    T_CURRENT = L3_CURRENT

    # ── Standard handler compatibility aliases (H01 Body Type 4 required) ────
    R_PHASE_VOLTAGE = L1_VOLTAGE
    S_PHASE_VOLTAGE = L2_VOLTAGE
    T_PHASE_VOLTAGE = L3_VOLTAGE
    R_PHASE_CURRENT = L1_CURRENT
    S_PHASE_CURRENT = L2_CURRENT
    T_PHASE_CURRENT = L3_CURRENT

    # ── RTU modbus_handler / simulator mandatory aliases ──────────────────────
    INVERTER_MODE   = WORK_MODE       # status register → WorkMode
    AC_POWER        = AC_POWER_LO     # main power register (Lo word; combine with AC_POWER_HI for S32)
    TOTAL_ENERGY    = TOTAL_ENERGY_HI  # total energy high register
    INNER_TEMP      = TEMPERATURE

    MPPT1_VOLTAGE   = PV1_VOLTAGE
    MPPT1_CURRENT   = PV1_CURRENT
    MPPT2_VOLTAGE   = PV2_VOLTAGE
    MPPT2_CURRENT   = PV2_CURRENT


class InverterMode:
    INITIAL  = 0x00
    STANDBY  = 0x01
    ON_GRID  = 0x03
    FAULT    = 0x05
    SHUTDOWN = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")


class DeviceType:
    RTU = 0
    INVERTER = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU",
            1: "Inverter",
            2: "Environment Sensor",
            3: "Power Meter",
            4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    NONE    = "NONE"
    DER_AVM = "DER_AVM"


class GoodweStatusConverter:
    """Maps raw GoodWe WorkMode register value → InverterMode value."""
    STATUS_MAP = {
        0: InverterMode.STANDBY,   # cWaitMode  → Standby
        1: InverterMode.ON_GRID,   # cNormalMode → On-Grid
        2: InverterMode.FAULT,     # cFaultMode  → Fault
    }

    @classmethod
    def to_inverter_mode(cls, raw):
        return cls.STATUS_MAP.get(raw, InverterMode.INITIAL)


StatusConverter = GoodweStatusConverter


SCALE = {
    'voltage':            0.1,
    'current':            0.1,    # GoodWe PV/AC current scale is 0.1 A
    'power':              1.0,    # AC_POWER_LO is in W (scale 1)
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}

MPPT_CHANNELS = 2
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    return (high << 16) | low


def registers_to_s32(low, high):
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


STRING_CURRENT_MONITOR = False

# ── Read Blocks ───────────────────────────────────────────────────────────────
# Block 1: 0x0220–0x0251 — covers error, total energy, PV voltages/currents,
#          AC voltages/currents, frequency, power, mode, temperature, daily energy
READ_BLOCKS = [
    {'start': 0x0220, 'count': 50, 'fc': 3},
]

# ── Data Parser ───────────────────────────────────────────────────────────────
DATA_PARSER = {
    'mode'              : 'INVERTER_MODE',
    'r_voltage'         : 'R_PHASE_VOLTAGE',
    's_voltage'         : 'S_PHASE_VOLTAGE',
    't_voltage'         : 'T_PHASE_VOLTAGE',
    'r_current'         : 'R_PHASE_CURRENT',
    's_current'         : 'S_PHASE_CURRENT',
    't_current'         : 'T_PHASE_CURRENT',
    'frequency'         : 'FREQUENCY',
    'ac_power'          : 'AC_POWER',
    'temperature'       : 'INNER_TEMP',
    'cumulative_energy' : 'TOTAL_ENERGY',
    'alarm1'            : 'ERROR_CODE1',
    'mppt1_voltage'     : 'MPPT1_VOLTAGE',
    'mppt1_current'     : 'MPPT1_CURRENT',
    'mppt2_voltage'     : 'MPPT2_VOLTAGE',
    'mppt2_current'     : 'MPPT2_CURRENT',
}
