# -*- coding: utf-8 -*-
"""
Huawei Inverter Modbus Register Map
Based on Huawei Modbus Protocol 
Protocol Name: huawei
MPPT: 4 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-07
"""



class RegisterMap:
    """Huawei Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    SERIAL_NUMBER                            = 0x0014  # U16
    FIRMWARE_VERSION                         = 0x001E  # U16
    LOW_INSULATION_RESISTANCE                = 0x080E  # U16
    MODEL                                    = 0x7530  # STRING
    SOFTWAREVERSION                          = 0x7562  # STRING
    PROTOCOLVERSION_MODBUS                   = 0x7574  # U32
    PROTOCOLVERSION_MODBUS_HIGH              = 0x7575
    MODEL_ID                                 = 0x7576  # U16
    NUMBEROF_MPPTS                           = 0x7578  # U16, scale 1
    RATEDPOWER                               = 0x7579  # U32, scale kW 1000
    RATEDPOWER_HIGH                          = 0x757A
    PRODUCT_SOFTWARE_VERSION_NUMBER          = 0x759C  # U16
    POWER_GRID_STANDARD_CODE_PROTOCOL_VERSION = 0x759D  # U16
    THIRD_PARTYLABELING_SN                   = 0x75EF  # STRING
    THIRD_PARTYLABEL_MANUFACTURERMODEL       = 0x75F9  # U16
    MONITORING_BOARD_SN                      = 0x7927  # STRING
    MONITORINGSOFTWAREVERSION                = 0x7931  # STRING
    DEVICE_SNFEATURECODE                     = 0x7D0F  # U16
    INTERNALTEMPERATURE                      = 0x7D57  # S16, scale 10
    ALARMCLEARANCE_SN                        = 0x7D9B  # U16
    SERIALNUMBEROFTHELATESTACTIVEALARM       = 0x7DAC  # U32
    SERIALNUMBEROFTHELATESTACTIVEALARM_HIGH  = 0x7DAD
    LATEST_HISTORICAL_ALARM_SERIAL_NUMBER    = 0x7DAE  # U32
    LATEST_HISTORICAL_ALARM_SERIAL_NUMBER_HIGH = 0x7DAF
    TOTALBUSVOLTAGE                          = 0x7DB0  # S16, scale V 10
    MPPT3DCTOTAL_ENERGY_YIELD                = 0x7DD8  # U32, scale kWh 100
    MPPT3DCTOTAL_ENERGY_YIELD_HIGH           = 0x7DD9
    RUNNINGTIMEOFCAPACITORBANK               = 0x88B8  # U32, scale 10
    RUNNINGTIMEOFCAPACITORBANK_HIGH          = 0x88B9
    INTERNALFAN1RUNNINGTIME                  = 0x88BA  # U32, scale 10
    INTERNALFAN1RUNNINGTIME_HIGH             = 0x88BB
    INTERNAL_TEMPERATURE1                    = 0x88CD  # S16, scale 10
    INTERNAL_TEMPERATURE2                    = 0x88CE  # S16, scale 10
    INTERNAL_TEMPERATURE3                    = 0x88CF  # S16, scale 10
    INTERNAL_TEMPERATURE4                    = 0x88D0  # S16, scale 10
    INTERNAL_TEMPERATURE5                    = 0x88D1  # S16, scale 10
    INTERNAL_TEMPERATURE6                    = 0x88D2  # S16, scale 10
    INTERNALTEMPERATURE7                     = 0x88D3  # S16, scale 10
    INTERNALTEMPERATURE8                     = 0x88D4  # S16, scale 10
    INTERNALTEMPERATURE9                     = 0x88D5  # S16, scale 10
    INTERNALTEMPERATURE10                    = 0x88D6  # S16, scale 10
    INTERNALTEMPERATURE11                    = 0x88D7  # S16, scale 10
    INTERNALTEMPERATURE12                    = 0x88D8  # S16, scale 10
    POSITIVEBUSVOLTAGE                       = 0x88E2  # S16, scale V 10
    NEGATIVEBUSVOLTAGE                       = 0x88E3  # S16, scale V 10
    BUSNEGATIVEVOLTAGETOGROUND               = 0x88E4  # S16, scale V 10
    LICENSE_SN                               = 0x8949  # STRING, scale 1
    METER_MODEL_CHECK_RESULT                 = 0x9112  # U16
    LAYOUT_FILE_CHANGE_SN                    = 0x915A  # U16, scale 1
    REPLACETHETARGETMODEL                    = 0xA41C  # U16, scale 1
    MAXIMUMAPPARENTPOWER                     = 0xA425  # U32, scale kVA 1000
    MAXIMUMAPPARENTPOWER_HIGH                = 0xA426
    APPARENTPOWERREFERENCE                   = 0xA429  # U32, scale 1000
    APPARENTPOWERREFERENCE_HIGH              = 0xA42A
    SCIENCEAND_TECHNOLOGY_JINGKE_PROTOCOL_VERSION = 0xAC47  # U16
    CLEAR_THERUNNINGTIMEINFORMATION          = 0xAFD3  # U16
    ESNVALIDATIONCOMMAND                     = 0xAFD7  # U16, scale 1
    METERMODEL                               = 0xB8C7  # U16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    POWER_FACTOR                             = 0x0000  # U16
    G83_SCOTLAND                             = 0x000C  # U16
    CEI0_21                                  = 0x000D  # U16
    REG_0X0E                                 = 0x000E  # U16
    RD1699_661                               = 0x000F  # U16
    CUSTOM_MV480_50_HZ                       = 0x001D  # U16, scale Hz
    ELECTRIC_RULE_NO_21_MV480                = 0x0036  # U16
    PV_POWER                                 = 0x0050  # U16
    L1_VOLTAGE                               = 0x0070  # U16
    L2_VOLTAGE                               = 0x0071  # U16
    L3_VOLTAGE                               = 0x0072  # U16
    L1_CURRENT                               = 0x0073  # U16
    L2_CURRENT                               = 0x0074  # U16
    L3_CURRENT                               = 0x0075  # U16
    DUBAI_MV800                              = 0x008A  # U16
    NORTHERN_IRELAND_MV800                   = 0x008E  # U16
    CAMEROON_MV800                           = 0x009B  # U16
    VDE_AR_N4120_HV                          = 0x00B4  # U16
    VDE_AR_N4120_HV480                       = 0x00B5  # U16
    VDE_AR_N4120_HV800                       = 0x00B6  # U16
    ELECTRIC_RULE_NO_21_MV800                = 0x00BA  # U16
    CUSTOM_MV800_50HZ                        = 0x00C0  # U16
    ELECTRIC_RULE_NO_21_LV208                = 0x00D2  # U16
    ELECTRIC_RULE_NO_21_LV240                = 0x00D3  # U16
    VDE_AR_N4110                             = 0x010C  # U16
    VDE_AR_N4110_MV480                       = 0x010D  # U16
    VDE_AR_N4110_MV800                       = 0x010E  # U16
    FREQUENCY                                = 0x07F2  # U16
    PV1VOLTAGE                               = 0x7D10  # S16, scale V 10
    PV1CURRENT                               = 0x7D11  # S16, scale A 100
    PV2VOLTAGE                               = 0x7D12  # S16, scale V 10
    PV2CURRENT                               = 0x7D13  # S16, scale A 100
    PV3VOLTAGE                               = 0x7D14  # S16, scale V 10
    PV3CURRENT                               = 0x7D15  # S16, scale A 100
    PV4VOLTAGE                               = 0x7D16  # S16, scale V 10
    PV4CURRENT                               = 0x7D17  # S16, scale A 100
    REACTIVE_POWER                           = 0x7D52  # S32, scale 1000
    REACTIVE_POWER_HIGH                      = 0x7D53
    ACCUMULATEDPOWERGENERATION               = 0x7D6A  # U32, scale kWh 100
    ACCUMULATEDPOWERGENERATION_HIGH          = 0x7D6B
    TOTAL_DCINPUT_POWER                      = 0x7D6C  # U32, scale kWh 100
    TOTAL_DCINPUT_POWER_HIGH                 = 0x7D6D
    CUMULATIVE_ENERGY                        = 0x7DDA  # U32, scale kWh 100
    CUMULATIVE_ENERGY_HIGH                   = 0x7DDB
    FREQUENCY_ACTIVE_POWER_DERATING_RECOVERY_DELAY_TIME = 0xA438  # U16, scale 1
    FREQUENCY_ACTIVE_POWER_DERATING_EFFECTIVE_DELAY_TIME = 0xA439  # U16, scale 1
    FREQUENCYMODULATIONCONTROLRESPONSEDEADBAND = 0xA43B  # U16, scale Hz 1000
    FREQUENCYMODULATIONCONTROLPOWERCHANGEGRADIENT = 0xA443  # U16, scale 1
    FREQUENCYMODULATIONCONTROLPOWERCHANGELIMITINGAMPLITUDE = 0xA444  # U16, scale 10
    FREQUENCYRATEPROTECTION                  = 0xA460  # U16
    FREQUENCYCHANGERATEPROTECTIONPOINT       = 0xA461  # U16, scale Hz 10
    FREQUENCYCHANGERATEPROTECTIONTIME        = 0xA462  # U16, scale 10
    FREQUENCYMODULATIONCONTROL               = 0xA49D  # U16
    FREQUENCYMODULATIONCONTROLDIFFERENTIALMODULATIONRATE = 0xA49E  # U16, scale 1
    TEMPERATURE                              = 0xAD78  # S16, scale 10

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    REMOTESIGNAL_RUNNINGSTATUSMONITORING     = 0x7D02  # U16
    REMOTESIGNAL_RUNNINGSTATUSPOWERPROCESSING = 0x7D03  # U32, scale 1
    REMOTESIGNAL_RUNNINGSTATUSPOWERPROCESSING_HIGH = 0x7D04
    DEVICE_STATUS                            = 0x7D59  # U16
    BUILT_IN_PIDRUNNINGSTATUS                = 0x7DBE  # U16
    STRING_1ACCESSSTATUS                     = 0x7E2C  # STRINGING
    STRING_2ACCESSSTATUS                     = 0x7E2D  # STRINGING
    STRING_3ACCESSSTATUS                     = 0x7E2E  # STRINGING
    STRING_4ACCESSSTATUS                     = 0x7E2F  # STRINGING
    STRING_5ACCESSSTATUS                     = 0x7E30  # STRINGING
    CONNECTIONSTATUS_OFSTRING_6              = 0x7E31  # U16
    STRING_7ACCESSSTATUS                     = 0x7E32  # STRINGING
    STRING_8ACCESSSTATUS                     = 0x7E33  # STRINGING
    STENT_SYSTEM_STATUS                      = 0x84D0  # U32
    STENT_SYSTEM_STATUS_HIGH                 = 0x84D1
    OPERATINGMODE                            = 0x84F4  # U16
    SUPPORTACCESSSTATUS                      = 0x84F6  # U32, scale 1
    SUPPORTACCESSSTATUS_HIGH                 = 0x84F7
    WORKINGMODEMASK                          = 0x84F8  # U32, scale 1
    WORKINGMODEMASK_HIGH                     = 0x84F9
    SUPPORT_1GENERAL_FAULT_STATUS            = 0x851B  # U16
    SUPPORT_1USER_DEFINEDFAULTSTATUS         = 0x851C  # U16, scale 1
    SUPPORT_2GENERAL_FAULT_STATUS            = 0x851D  # U16, scale 1
    SUPPORT_2CUSTOM_FAULT_STATUS             = 0x851E  # U16, scale 1
    SUPPORT_3GENERAL_FAULT_STATUS            = 0x851F  # U16, scale 1
    SUPPORT_3USER_DEFINEDFAULTSTATUS         = 0x8520  # U16, scale 1
    SUPPORT_4GENERAL_FAULT_STATUS            = 0x8521  # U16, scale 1
    SUPPORT_4CUSTOM_FAULT_STATUS             = 0x8522  # U16, scale 1
    SUPPORT_5GENERAL_FAULT_STATUS            = 0x8523  # U16, scale 1
    SUPPORT_5CUSTOM_FAULT_STATUS             = 0x8524  # U16, scale 1
    SUPPORT_6GENERAL_FAULT_STATUS            = 0x8525  # U16, scale 1
    SUPPORT_6CUSTOM_FAULT_STATUS             = 0x8526  # U16, scale 1
    SUPPORT_7GENERAL_FAULT_STATUS            = 0x8527  # U16, scale 1
    SUPPORT_7CUSTOM_FAULT_STATUS             = 0x8528  # U16, scale 1
    SUPPORT_8GENERAL_FAULT_STATUS            = 0x8529  # U16, scale 1
    SUPPORT_8CUSTOM_FAULT_STATUS             = 0x852A  # U16, scale 1
    SUPPORT_9GENERAL_FAULT_STATUS            = 0x852B  # U16, scale 1
    SUPPORT_9CUSTOM_FAULT_STATUS             = 0x852C  # U16, scale 1
    SUPPORT10GENERAL_FAULT_STATUS            = 0x852D  # U16, scale 1
    SUPPORT10CUSTOM_FAULT_STATUS             = 0x852E  # U16, scale 1
    SUPPORT11GENERAL_FAULT_STATUS            = 0x852F  # U16, scale 1
    SUPPORT11CUSTOM_FAULT_STATUS             = 0x8530  # U16, scale 1
    SUPPORT12GENERAL_FAULT_STATUS            = 0x8531  # U16, scale 1
    SUPPORT12CUSTOM_FAULT_STATUS             = 0x8532  # U16, scale 1
    SUPPORT13GENERAL_FAULT_STATUS            = 0x8533  # U16, scale 1
    SUPPORT13CUSTOM_FAULT_STATUS             = 0x8534  # U16, scale 1
    SUPPORT14GENERAL_FAULT_STATUS            = 0x8535  # U16, scale 1
    SUPPORT14CUSTOM_FAULT_STATUS             = 0x8536  # U16, scale 1
    SUPPORT15GENERAL_FAULT_STATUS            = 0x8537  # U16, scale 1
    SUPPORT15CUSTOM_FAULT_STATUS             = 0x8538  # U16, scale 1
    SUPPORT16GENERAL_FAULT_STATUS            = 0x8539  # U16, scale 1
    SUPPORT16CUSTOM_FAULT_STATUS             = 0x853A  # U16, scale 1
    I_VSCANSTATUS                            = 0x8916  # U16
    STAWLANLISTSCANNINGSTATUS                = 0x8921  # U16
    NTPLAST_NTPSYNCHRONIZATIONSTATUS         = 0x8928  # U16, scale 1
    DEFERREDACTIVATIONSTATE                  = 0x892B  # U16
    REG_4GTRAFFICSTATUS                      = 0x8932  # U16
    STAROUTERCONNECTIONSTATUS                = 0x8935  # U16
    FECONNECTIONSTATUS                       = 0x8936  # U16, scale 1
    SMART_I_V_V_DIAGNOSIS_LICENSE_STATUS     = 0x8942  # U16, scale V
    STRINGMONITORING_LICENSESTATUS           = 0x8995  # U16
    REG_4GMODULESTATUS                       = 0x89B1  # U16
    REG_4GPINCHECKSTATUS                     = 0x89C2  # U16
    ACTIVEPOWERADJUSTMENTSTATUS              = 0x89E4  # U16
    REACTIVEPOWERADJUSTMENTSTATUS            = 0x89E8  # U16
    UPGRADESTATUS_ID                         = 0x8CC1  # U16
    MODULE1RUNNINGSTATUS_OFTHEBATTERY        = 0x9088  # U16
    METER_STATUS                             = 0x90EC  # U16
    CURRENTSTATUS_OFTHEPHYSICALLOCATION      = 0x9156  # U16
    RELATIVE_POSITIONING_STATUS              = 0x9158  # U16
    DISCONNECTEDSTATUS                       = 0x915C  # U16
    DC_MBUSNETWORKINGSTATUS                  = 0x9182  # U16
    FAST_SHUTDOWN_SELF_TEST_STATUS           = 0x9185  # U16
    RUNNINGSTATUS                            = 0x9186  # U16
    SCHEDULESERVER_COMMUNICATIONSTATUS       = 0x9263  # U16
    SCHEDULESERVER_LATESTCONNECTIONSTATUS    = 0x9264  # U16
    UPGRADE_STATUS                           = 0x9279  # U16
    INVERTERCOMPREHENSIVESTATUS              = 0x928E  # U16
    INVERTERINTEGRATEDSTATUSSUPPORTFLAG      = 0x928F  # U16, scale 1
    Q_UCHARACTERISTICCURVEMODE               = 0x9C65  # U16
    OUTPUTMODE                               = 0xA411  # U16
    OF_FGRIDSWITCHOVERMODE                   = 0xA43C  # U16
    OFF_GRIDMODE                             = 0xA43D  # U16
    PQMODE                                   = 0xA43E  # U16
    STRINGCONNECTIONMODE                     = 0xA441  # U16
    POWER_QUALITY_OPTIMIZATION_MODE          = 0xA451  # U16
    FAILUREPROTECTIONACTIVEPOWERMODE         = 0xA45C  # U16
    FAILUREPROTECTIONREACTIVEPOWERMODE       = 0xA45F  # U16
    GRIDFAULTZEROCURRENTMODE                 = 0xA47E  # U16
    BUILT_IN_PIDMODE                         = 0xA4C4  # U16
    MANAGEMENT_SYSTEM_PORTMODE               = 0xA85C  # U16
    STAWIRELESS_ROUTING_ENCRYPTION_MODE      = 0xA89C  # U16
    PARALLELCOMMUNICATIONMODE                = 0xA961  # U16
    REG_4GNETWORKMODE                        = 0xA9A6  # U16
    REG_4GAPNMODE                            = 0xA9A7  # U16
    SECURITYMODE                             = 0xB834  # U16
    ACTIVEPOWERCONTROLMODE                   = 0xB937  # U16
    RESTRICTIONMODE                          = 0xB93B  # U16
    REACTIVEPOWERCONTROLMODE                 = 0xB941  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    ABNORMAL_GROUNDING                       = 0x080D  # U16
    DEVICE_FAULT                             = 0x0810  # U16
    FAULTY_POWER_COLLECTOR2                  = 0x0813  # U16
    BATTERY_ABNORMAL                         = 0x0814  # U16
    ABNORMAL_PV_MODULECONFIGURATION          = 0x0820  # U16
    OPTIMIZER_FAULT5                         = 0x0821  # U16
    ON_GRID_OFF_GRID_CONTROLLERABNORMAL4     = 0x0822  # U16
    BUILT_IN_PID_OPERATIONABNORMAL6          = 0x0825  # U16
    EXTERNAL_FAN_ABNORMAL                    = 0x0826  # U16
    INTERNAL_FAN_ABNORMAL                    = 0x0827  # U16
    DC_PROTECTION_UNIT_ABNORMAL8             = 0x0828  # U16
    REMOTESIGNAL_ALARM_1                     = 0x7D08  # U16
    REMOTESIGNAL_ALARM_2                     = 0x7D09  # U16
    REMOTESIGNAL_ALARM_3                     = 0x7D0A  # U16
    REMOTESIGNAL_ALARM_4                     = 0x7D0B  # U16
    REMOTESIGNAL_ALARM_5                     = 0x7D0C  # U16
    REMOTESIGNAL_ALARM_6                     = 0x7D0D  # U16
    FAULT_CODE                               = 0x7D5A  # U16
    NUMBEROFCRITICALALARMS                   = 0x7D97  # U16, scale 1
    NUMBEROFMAJORALARMS                      = 0x7D98  # U16, scale 1
    NUMBEROF_MINOR_ALARMS                    = 0x7D99  # U16, scale 1
    NUMBEROF_WARNING_ALARMS                  = 0x7D9A  # U16, scale 1
    MONITORINGALARM_1                        = 0x7DFC  # U16
    MONITORINGALARM_2                        = 0x7DFD  # U16
    MONITORALARM_3                           = 0x7DFE  # U16
    EXTERNAL_POWERALARM_1                    = 0x7DFF  # U16
    EXTERNAL_POWERALARM_2                    = 0x7E00  # U16
    EXTERNAL_POWERALARM_3                    = 0x7E01  # U16
    EXTERNAL_POWERALARM_4                    = 0x7E02  # U16
    EXTERNAL_POWERALARM_5                    = 0x7E03  # U16
    EXTERNAL_POWERALARM_6                    = 0x7E04  # U16
    EXTERNAL_POWERALARM_7                    = 0x7E05  # U16
    EXTERNAL_POWERALARM_8                    = 0x7E06  # U16
    EXTERNAL_POWERALARM_9                    = 0x7E07  # U16
    EXTERNAL_POWERALARM10                    = 0x7E08  # U16
    EXTERNAL_POWERALARM11                    = 0x7E09  # U16
    EXTERNAL_POWERALARM12                    = 0x7E0A  # U16
    EXTERNAL_POWERALARM13                    = 0x7E0B  # U16
    EXTERNAL_POWERALARM14                    = 0x7E0C  # U16
    EXTERNAL_POWERALARM15                    = 0x7E0D  # U16
    EXTERNAL_POWERALARM16                    = 0x7E0E  # U16
    MONITORALARM_4                           = 0x7E0F  # U16
    MONITORALARM_5                           = 0x7E10  # U16
    EXTERNAL_POWERALARM17                    = 0x7E11  # U16
    INTERNALALARM                            = 0x88C2  # U16, scale V 1
    AUDIBLEANDVISUALALARM                    = 0xA432  # U16
    POWERGRIDFAULTRECOVERYAUTOMATICSTARTUP   = 0xA44D  # U16
    ABNORMALGROUNDINGSHUTDOWN                = 0xA454  # U16
    POWER_ONSOFTSTARTTIMEDUETOPOWERGRIDFAULTS = 0xA474  # U16, scale 1
    POWERGRIDFAULTRECOVERYTIME               = 0xA478  # U16, scale 1
    REG_4GDEFAULT_IDENTITYAUTHENTICATIONTYPE = 0xA9A9  # U16
    REG_4GDEFAULT_APN                        = 0xA9AA  # STRING, scale 1
    REG_4GDEFAULT_APNUSERNAME                = 0xA9CA  # STRING, scale 1
    SUPPORT_FAULT_CLEARANCE                  = 0xAC32  # U16, scale 1
    CLEARINGACTIVEALARMS                     = 0xAFC9  # U16
    ALARMSETTING                             = 0xAFCB  # U16
    ALARMCLEARANCE                           = 0xAFCD  # U16
    ALARMMASKING                             = 0xAFCE  # U16
    ALARMPORTSELF_CHECKSTART                 = 0xAFED  # U16, scale 1
    AUDIBLEANDVISUALALARMCONFIRMATION        = 0xAFF0  # U16, scale 1
    MAXIMUM_FEED_GRID_POWER_DEFAULT          = 0xBA3B  # S32, scale kW 1000
    MAXIMUM_FEED_GRID_POWER_DEFAULT_HIGH     = 0xBA3C
    DEFAULTACTIVEPOWERCHANGEGRADIENT         = 0xBA3D  # U32, scale 1000
    DEFAULTACTIVEPOWERCHANGEGRADIENT_HIGH    = 0xBA3E
    FAULTY_MONITORING_UNIT                   = 0xF000  # U16

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # L2 없음 → 대체

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    MPPT1_VOLTAGE                            = PV1VOLTAGE
    MPPT1_CURRENT                            = PV1CURRENT
    MPPT2_VOLTAGE                            = PV2VOLTAGE
    MPPT2_CURRENT                            = PV2CURRENT
    MPPT3_VOLTAGE                            = PV3VOLTAGE
    MPPT3_CURRENT                            = PV3CURRENT
    MPPT4_VOLTAGE                            = PV4VOLTAGE
    MPPT4_CURRENT                            = PV4CURRENT
    PV_VOLTAGE                               = MPPT1_VOLTAGE
    PV_STRING_COUNT                          = 4

    # --- RTU modbus_handler / simulator 필수 alias ---
    INNER_TEMP                               = TEMPERATURE
    INVERTER_MODE                            = DEVICE_STATUS
    AC_POWER                                 = PV_POWER
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    ERROR_CODE1                              = ABNORMAL_GROUNDING
    ERROR_CODE2                              = DEVICE_FAULT
    ERROR_CODE3                              = FAULTY_POWER_COLLECTOR2
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834
    MPPT_NUMBER                              = 0x1A4A  # default MPPT count register
    CUMULATIVE_ENERGY_LOW                    = CUMULATIVE_ENERGY
    DER_AVM_DIGITAL_METERCONNECT_STATUS      = 0x1210



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x080D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x0810) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x0813) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x0814) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x0820) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x0821) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x0822) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x0825) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x0826) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode10:
    """Error Code Table10 (0x0827) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode11:
    """Error Code Table11 (0x0828) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode12:
    """Error Code Table12 (0x7D08) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode13:
    """Error Code Table13 (0x7D09) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode14:
    """Error Code Table14 (0x7D0A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode15:
    """Error Code Table15 (0x7D0B) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode16:
    """Error Code Table16 (0x7D0C) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode17:
    """Error Code Table17 (0x7D0D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode18:
    """Error Code Table18 (0x7D5A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode19:
    """Error Code Table19 (0x7D97) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode20:
    """Error Code Table20 (0x7D98) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode21:
    """Error Code Table21 (0x7D99) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode22:
    """Error Code Table22 (0x7D9A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode23:
    """Error Code Table23 (0x7DFC) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode24:
    """Error Code Table24 (0x7DFD) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode25:
    """Error Code Table25 (0x7DFE) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode26:
    """Error Code Table26 (0x7DFF) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode27:
    """Error Code Table27 (0x7E00) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode28:
    """Error Code Table28 (0x7E01) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode29:
    """Error Code Table29 (0x7E02) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode30:
    """Error Code Table30 (0x7E03) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode31:
    """Error Code Table31 (0x7E04) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode32:
    """Error Code Table32 (0x7E05) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode33:
    """Error Code Table33 (0x7E06) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode34:
    """Error Code Table34 (0x7E07) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode35:
    """Error Code Table35 (0x7E08) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode36:
    """Error Code Table36 (0x7E09) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode37:
    """Error Code Table37 (0x7E0A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode38:
    """Error Code Table38 (0x7E0B) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode39:
    """Error Code Table39 (0x7E0C) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode40:
    """Error Code Table40 (0x7E0D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode41:
    """Error Code Table41 (0x7E0E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode42:
    """Error Code Table42 (0x7E0F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode43:
    """Error Code Table43 (0x7E10) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode44:
    """Error Code Table44 (0x7E11) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode45:
    """Error Code Table45 (0x88C2) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode46:
    """Error Code Table46 (0xA432) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode47:
    """Error Code Table47 (0xA44D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode48:
    """Error Code Table48 (0xA454) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode49:
    """Error Code Table49 (0xA474) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode50:
    """Error Code Table50 (0xA478) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode51:
    """Error Code Table51 (0xA9A9) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode52:
    """Error Code Table52 (0xA9AA) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode53:
    """Error Code Table53 (0xA9CA) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode54:
    """Error Code Table54 (0xAC32) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode55:
    """Error Code Table55 (0xAD10) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode56:
    """Error Code Table56 (0xAFC9) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode57:
    """Error Code Table57 (0xAFCB) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode58:
    """Error Code Table58 (0xAFCD) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode59:
    """Error Code Table59 (0xAFCE) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode60:
    """Error Code Table60 (0xAFED) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode61:
    """Error Code Table61 (0xAFF0) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode62:
    """Error Code Table62 (0xBA3B) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode63:
    """Error Code Table63 (0xBA3D) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode64:
    """Error Code Table64 (0xF000) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class HuaweiStatusConverter:
    """Huawei INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw

    @classmethod
    def to_solarize(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)

    @classmethod
    def to_h01(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = HuaweiStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 4
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-4).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-4)."""
    if tracker_num < 1 or tracker_num > 4:
        raise ValueError(f"Tracker number must be 1-4, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'POWER_FACTOR': 'U16',
    'G83_SCOTLAND': 'U16',
    'CEI0_21': 'U16',
    'REG_0X0E': 'U16',
    'RD1699_661': 'U16',
    'SERIAL_NUMBER': 'U16',
    'CUSTOM_MV480_50_HZ': 'U16',
    'FIRMWARE_VERSION': 'U16',
    'ELECTRIC_RULE_NO_21_MV480': 'U16',
    'PV_POWER': 'U16',
    'L1_VOLTAGE': 'U16',
    'L2_VOLTAGE': 'U16',
    'L3_VOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'L2_CURRENT': 'U16',
    'L3_CURRENT': 'U16',
    'DUBAI_MV800': 'U16',
    'NORTHERN_IRELAND_MV800': 'U16',
    'CAMEROON_MV800': 'U16',
    'VDE_AR_N4120_HV': 'U16',
    'VDE_AR_N4120_HV480': 'U16',
    'VDE_AR_N4120_HV800': 'U16',
    'ELECTRIC_RULE_NO_21_MV800': 'U16',
    'CUSTOM_MV800_50HZ': 'U16',
    'ELECTRIC_RULE_NO_21_LV208': 'U16',
    'ELECTRIC_RULE_NO_21_LV240': 'U16',
    'VDE_AR_N4110': 'U16',
    'VDE_AR_N4110_MV480': 'U16',
    'VDE_AR_N4110_MV800': 'U16',
    'FREQUENCY': 'U16',
    'ABNORMAL_GROUNDING': 'U16',
    'LOW_INSULATION_RESISTANCE': 'U16',
    'DEVICE_FAULT': 'U16',
    'FAULTY_POWER_COLLECTOR2': 'U16',
    'BATTERY_ABNORMAL': 'U16',
    'ABNORMAL_PV_MODULECONFIGURATION': 'U16',
    'OPTIMIZER_FAULT5': 'U16',
    'ON_GRID_OFF_GRID_CONTROLLERABNORMAL4': 'U16',
    'BUILT_IN_PID_OPERATIONABNORMAL6': 'U16',
    'EXTERNAL_FAN_ABNORMAL': 'U16',
    'INTERNAL_FAN_ABNORMAL': 'U16',
    'DC_PROTECTION_UNIT_ABNORMAL8': 'U16',
    'MODEL': 'STRING',
    'SOFTWAREVERSION': 'STRING',
    'PROTOCOLVERSION_MODBUS': 'U32',
    'MODEL_ID': 'U16',
    'NUMBEROF_MPPTS': 'U16',
    'RATEDPOWER': 'U32',
    'PRODUCT_SOFTWARE_VERSION_NUMBER': 'U16',
    'POWER_GRID_STANDARD_CODE_PROTOCOL_VERSION': 'U16',
    'THIRD_PARTYLABELING_SN': 'STRING',
    'THIRD_PARTYLABEL_MANUFACTURERMODEL': 'U16',
    'MONITORING_BOARD_SN': 'STRING',
    'MONITORINGSOFTWAREVERSION': 'STRING',
    'REMOTESIGNAL_RUNNINGSTATUSMONITORING': 'U16',
    'REMOTESIGNAL_RUNNINGSTATUSPOWERPROCESSING': 'U32',
    'REMOTESIGNAL_ALARM_1': 'U16',
    'REMOTESIGNAL_ALARM_2': 'U16',
    'REMOTESIGNAL_ALARM_3': 'U16',
    'REMOTESIGNAL_ALARM_4': 'U16',
    'REMOTESIGNAL_ALARM_5': 'U16',
    'REMOTESIGNAL_ALARM_6': 'U16',
    'DEVICE_SNFEATURECODE': 'U16',
    'PV1VOLTAGE': 'S16',
    'PV1CURRENT': 'S16',
    'PV2VOLTAGE': 'S16',
    'PV2CURRENT': 'S16',
    'PV3VOLTAGE': 'S16',
    'PV3CURRENT': 'S16',
    'PV4VOLTAGE': 'S16',
    'PV4CURRENT': 'S16',
    'REACTIVE_POWER': 'S32',
    'INTERNALTEMPERATURE': 'S16',
    'DEVICE_STATUS': 'U16',
    'FAULT_CODE': 'U16',
    'ACCUMULATEDPOWERGENERATION': 'U32',
    'TOTAL_DCINPUT_POWER': 'U32',
    'NUMBEROFCRITICALALARMS': 'U16',
    'NUMBEROFMAJORALARMS': 'U16',
    'NUMBEROF_MINOR_ALARMS': 'U16',
    'NUMBEROF_WARNING_ALARMS': 'U16',
    'ALARMCLEARANCE_SN': 'U16',
    'SERIALNUMBEROFTHELATESTACTIVEALARM': 'U32',
    'LATEST_HISTORICAL_ALARM_SERIAL_NUMBER': 'U32',
    'TOTALBUSVOLTAGE': 'S16',
    'BUILT_IN_PIDRUNNINGSTATUS': 'U16',
    'MPPT3DCTOTAL_ENERGY_YIELD': 'U32',
    'CUMULATIVE_ENERGY': 'U32',
    'MONITORINGALARM_1': 'U16',
    'MONITORINGALARM_2': 'U16',
    'MONITORALARM_3': 'U16',
    'EXTERNAL_POWERALARM_1': 'U16',
    'EXTERNAL_POWERALARM_2': 'U16',
    'EXTERNAL_POWERALARM_3': 'U16',
    'EXTERNAL_POWERALARM_4': 'U16',
    'EXTERNAL_POWERALARM_5': 'U16',
    'EXTERNAL_POWERALARM_6': 'U16',
    'EXTERNAL_POWERALARM_7': 'U16',
    'EXTERNAL_POWERALARM_8': 'U16',
    'EXTERNAL_POWERALARM_9': 'U16',
    'EXTERNAL_POWERALARM10': 'U16',
    'EXTERNAL_POWERALARM11': 'U16',
    'EXTERNAL_POWERALARM12': 'U16',
    'EXTERNAL_POWERALARM13': 'U16',
    'EXTERNAL_POWERALARM14': 'U16',
    'EXTERNAL_POWERALARM15': 'U16',
    'EXTERNAL_POWERALARM16': 'U16',
    'MONITORALARM_4': 'U16',
    'MONITORALARM_5': 'U16',
    'EXTERNAL_POWERALARM17': 'U16',
    'STRING_1ACCESSSTATUS': 'STRINGING',
    'STRING_2ACCESSSTATUS': 'STRINGING',
    'STRING_3ACCESSSTATUS': 'STRINGING',
    'STRING_4ACCESSSTATUS': 'STRINGING',
    'STRING_5ACCESSSTATUS': 'STRINGING',
    'CONNECTIONSTATUS_OFSTRING_6': 'U16',
    'STRING_7ACCESSSTATUS': 'STRINGING',
    'STRING_8ACCESSSTATUS': 'STRINGING',
    'STENT_SYSTEM_STATUS': 'U32',
    'OPERATINGMODE': 'U16',
    'SUPPORTACCESSSTATUS': 'U32',
    'WORKINGMODEMASK': 'U32',
    'SUPPORT_1GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_1USER_DEFINEDFAULTSTATUS': 'U16',
    'SUPPORT_2GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_2CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT_3GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_3USER_DEFINEDFAULTSTATUS': 'U16',
    'SUPPORT_4GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_4CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT_5GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_5CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT_6GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_6CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT_7GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_7CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT_8GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_8CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT_9GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT_9CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT10GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT10CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT11GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT11CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT12GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT12CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT13GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT13CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT14GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT14CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT15GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT15CUSTOM_FAULT_STATUS': 'U16',
    'SUPPORT16GENERAL_FAULT_STATUS': 'U16',
    'SUPPORT16CUSTOM_FAULT_STATUS': 'U16',
    'RUNNINGTIMEOFCAPACITORBANK': 'U32',
    'INTERNALFAN1RUNNINGTIME': 'U32',
    'INTERNALALARM': 'U16',
    'INTERNAL_TEMPERATURE1': 'S16',
    'INTERNAL_TEMPERATURE2': 'S16',
    'INTERNAL_TEMPERATURE3': 'S16',
    'INTERNAL_TEMPERATURE4': 'S16',
    'INTERNAL_TEMPERATURE5': 'S16',
    'INTERNAL_TEMPERATURE6': 'S16',
    'INTERNALTEMPERATURE7': 'S16',
    'INTERNALTEMPERATURE8': 'S16',
    'INTERNALTEMPERATURE9': 'S16',
    'INTERNALTEMPERATURE10': 'S16',
    'INTERNALTEMPERATURE11': 'S16',
    'INTERNALTEMPERATURE12': 'S16',
    'POSITIVEBUSVOLTAGE': 'S16',
    'NEGATIVEBUSVOLTAGE': 'S16',
    'BUSNEGATIVEVOLTAGETOGROUND': 'S16',
    'I_VSCANSTATUS': 'U16',
    'STAWLANLISTSCANNINGSTATUS': 'U16',
    'NTPLAST_NTPSYNCHRONIZATIONSTATUS': 'U16',
    'DEFERREDACTIVATIONSTATE': 'U16',
    'REG_4GTRAFFICSTATUS': 'U16',
    'STAROUTERCONNECTIONSTATUS': 'U16',
    'FECONNECTIONSTATUS': 'U16',
    'SMART_I_V_V_DIAGNOSIS_LICENSE_STATUS': 'U16',
    'LICENSE_SN': 'STRING',
    'STRINGMONITORING_LICENSESTATUS': 'U16',
    'REG_4GMODULESTATUS': 'U16',
    'REG_4GPINCHECKSTATUS': 'U16',
    'ACTIVEPOWERADJUSTMENTSTATUS': 'U16',
    'REACTIVEPOWERADJUSTMENTSTATUS': 'U16',
    'UPGRADESTATUS_ID': 'U16',
    'MODULE1RUNNINGSTATUS_OFTHEBATTERY': 'U16',
    'METER_STATUS': 'U16',
    'METER_MODEL_CHECK_RESULT': 'U16',
    'CURRENTSTATUS_OFTHEPHYSICALLOCATION': 'U16',
    'RELATIVE_POSITIONING_STATUS': 'U16',
    'LAYOUT_FILE_CHANGE_SN': 'U16',
    'DISCONNECTEDSTATUS': 'U16',
    'DC_MBUSNETWORKINGSTATUS': 'U16',
    'FAST_SHUTDOWN_SELF_TEST_STATUS': 'U16',
    'RUNNINGSTATUS': 'U16',
    'SCHEDULESERVER_COMMUNICATIONSTATUS': 'U16',
    'SCHEDULESERVER_LATESTCONNECTIONSTATUS': 'U16',
    'UPGRADE_STATUS': 'U16',
    'INVERTERCOMPREHENSIVESTATUS': 'U16',
    'INVERTERINTEGRATEDSTATUSSUPPORTFLAG': 'U16',
    'Q_UCHARACTERISTICCURVEMODE': 'U16',
    'OUTPUTMODE': 'U16',
    'REPLACETHETARGETMODEL': 'U16',
    'MAXIMUMAPPARENTPOWER': 'U32',
    'APPARENTPOWERREFERENCE': 'U32',
    'AUDIBLEANDVISUALALARM': 'U16',
    'FREQUENCY_ACTIVE_POWER_DERATING_RECOVERY_DELAY_TIME': 'U16',
    'FREQUENCY_ACTIVE_POWER_DERATING_EFFECTIVE_DELAY_TIME': 'U16',
    'FREQUENCYMODULATIONCONTROLRESPONSEDEADBAND': 'U16',
    'OF_FGRIDSWITCHOVERMODE': 'U16',
    'OFF_GRIDMODE': 'U16',
    'PQMODE': 'U16',
    'STRINGCONNECTIONMODE': 'U16',
    'FREQUENCYMODULATIONCONTROLPOWERCHANGEGRADIENT': 'U16',
    'FREQUENCYMODULATIONCONTROLPOWERCHANGELIMITINGAMPLITUDE': 'U16',
    'POWERGRIDFAULTRECOVERYAUTOMATICSTARTUP': 'U16',
    'POWER_QUALITY_OPTIMIZATION_MODE': 'U16',
    'ABNORMALGROUNDINGSHUTDOWN': 'U16',
    'FAILUREPROTECTIONACTIVEPOWERMODE': 'U16',
    'FAILUREPROTECTIONREACTIVEPOWERMODE': 'U16',
    'FREQUENCYRATEPROTECTION': 'U16',
    'FREQUENCYCHANGERATEPROTECTIONPOINT': 'U16',
    'FREQUENCYCHANGERATEPROTECTIONTIME': 'U16',
    'POWER_ONSOFTSTARTTIMEDUETOPOWERGRIDFAULTS': 'U16',
    'POWERGRIDFAULTRECOVERYTIME': 'U16',
    'GRIDFAULTZEROCURRENTMODE': 'U16',
    'FREQUENCYMODULATIONCONTROL': 'U16',
    'FREQUENCYMODULATIONCONTROLDIFFERENTIALMODULATIONRATE': 'U16',
    'BUILT_IN_PIDMODE': 'U16',
    'MANAGEMENT_SYSTEM_PORTMODE': 'U16',
    'STAWIRELESS_ROUTING_ENCRYPTION_MODE': 'U16',
    'PARALLELCOMMUNICATIONMODE': 'U16',
    'REG_4GNETWORKMODE': 'U16',
    'REG_4GAPNMODE': 'U16',
    'REG_4GDEFAULT_IDENTITYAUTHENTICATIONTYPE': 'U16',
    'REG_4GDEFAULT_APN': 'STRING',
    'REG_4GDEFAULT_APNUSERNAME': 'STRING',
    'SUPPORT_FAULT_CLEARANCE': 'U16',
    'SCIENCEAND_TECHNOLOGY_JINGKE_PROTOCOL_VERSION': 'U16',
    'TEMPERATURE': 'S16',
    'CLEARINGACTIVEALARMS': 'U16',
    'ALARMSETTING': 'U16',
    'ALARMCLEARANCE': 'U16',
    'ALARMMASKING': 'U16',
    'CLEAR_THERUNNINGTIMEINFORMATION': 'U16',
    'ESNVALIDATIONCOMMAND': 'U16',
    'ALARMPORTSELF_CHECKSTART': 'U16',
    'AUDIBLEANDVISUALALARMCONFIRMATION': 'U16',
    'SECURITYMODE': 'U16',
    'METERMODEL': 'U16',
    'ACTIVEPOWERCONTROLMODE': 'U16',
    'RESTRICTIONMODE': 'U16',
    'REACTIVEPOWERCONTROLMODE': 'U16',
    'MAXIMUM_FEED_GRID_POWER_DEFAULT': 'S32',
    'DEFAULTACTIVEPOWERCHANGEGRADIENT': 'U32',
    'FAULTY_MONITORING_UNIT': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0000, 'count': 125, 'fc': 3},
    {'start': 0x007D, 'count':  87, 'fc': 3},
    {'start': 0x010C, 'count':   3, 'fc': 3},
    {'start': 0x07F2, 'count':  55, 'fc': 3},
    {'start': 0x7D02, 'count':  22, 'fc': 3},
    {'start': 0x7D52, 'count':  28, 'fc': 3},
    {'start': 0x7D97, 'count':   4, 'fc': 3},
    {'start': 0x7DBE, 'count': 118, 'fc': 3},
    {'start': 0x84D0, 'count':   2, 'fc': 3},
    {'start': 0x84F4, 'count':   6, 'fc': 3},
    {'start': 0x851B, 'count':  32, 'fc': 3},
    {'start': 0x88C2, 'count':  32, 'fc': 3},
    {'start': 0x8916, 'count':  45, 'fc': 3},
    {'start': 0x8995, 'count':  46, 'fc': 3},
    {'start': 0x89E4, 'count':   5, 'fc': 3},
    {'start': 0x8CC1, 'count':   1, 'fc': 3},
    {'start': 0x9088, 'count':   1, 'fc': 3},
    {'start': 0x90EC, 'count':  32, 'fc': 3},
    {'start': 0x9156, 'count':   7, 'fc': 3},
    {'start': 0x9182, 'count':   5, 'fc': 3},
    {'start': 0x9263, 'count':  45, 'fc': 3},
    {'start': 0x9C65, 'count':   1, 'fc': 3},
    {'start': 0x9CBA, 'count':   1, 'fc': 3},
    {'start': 0xA411, 'count': 125, 'fc': 3},
    {'start': 0xA48E, 'count':  17, 'fc': 3},
    {'start': 0xA4C4, 'count':  21, 'fc': 3},
    {'start': 0xA5A9, 'count':   1, 'fc': 3},
    {'start': 0xA85C, 'count':   1, 'fc': 3},
    {'start': 0xA89C, 'count':   1, 'fc': 3},
    {'start': 0xA961, 'count':   1, 'fc': 3},
    {'start': 0xA9A6, 'count':  37, 'fc': 3},
    {'start': 0xABE1, 'count':   1, 'fc': 3},
    {'start': 0xAC32, 'count':   1, 'fc': 3},
    {'start': 0xAD10, 'count':   1, 'fc': 3},
    {'start': 0xAD78, 'count':   1, 'fc': 3},
    {'start': 0xAFC9, 'count':  40, 'fc': 3},
    {'start': 0xB79C, 'count':   1, 'fc': 3},
    {'start': 0xB829, 'count':  12, 'fc': 3},
    {'start': 0xB8C6, 'count':   1, 'fc': 3},
    {'start': 0xB937, 'count':  11, 'fc': 3},
    {'start': 0xBA3B, 'count':   4, 'fc': 3},
    {'start': 0xF000, 'count':   1, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'G83_SCOTLAND',
    's_voltage           ': 'CEI0_21',
    't_voltage           ': 'REG_0X0E',
    'r_current           ': 'L1_CURRENT',
    's_current           ': 'L2_CURRENT',
    't_current           ': 'L3_CURRENT',
    'frequency           ': 'RD1699_661',
    'ac_power            ': 'AC_POWER',
    'cumulative_energy   ': 'ACCUMULATEDPOWERGENERATION',
    'alarm1              ': 'ERROR_CODE1',
    'mppt1_voltage'        : 'PV1VOLTAGE',
    'mppt1_current'        : 'PV1CURRENT',
    'mppt2_voltage'        : 'PV2VOLTAGE',
    'mppt2_current'        : 'PV2CURRENT',
    'mppt3_voltage'        : 'PV3VOLTAGE',
    'mppt3_current'        : 'PV3CURRENT',
    'mppt4_voltage'        : 'PV4VOLTAGE',
    'mppt4_current'        : 'PV4CURRENT',
}



# H01 스칼라 필드 → (RegisterMap 속성명, 변환기 키)
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
H01_FIELD_MAP = {
    'mode                ': ('INVERTER_MODE', 'raw'),
    'r_voltage           ': ('R_PHASE_VOLTAGE', 'voltage_to_V'),
    's_voltage           ': ('S_PHASE_VOLTAGE', 'voltage_to_V'),
    't_voltage           ': ('T_PHASE_VOLTAGE', 'voltage_to_V'),
    'r_current           ': ('R_PHASE_CURRENT', 'current_to_01A'),
    's_current           ': ('S_PHASE_CURRENT', 'current_to_01A'),
    't_current           ': ('T_PHASE_CURRENT', 'current_to_01A'),
    'frequency           ': ('FREQUENCY', 'frequency_to_01Hz'),
    'ac_power            ': ('AC_POWER', 'power_to_W'),
    'pv_power            ': ('PV_POWER', 'power_to_W'),
    'inner_temp          ': ('INNER_TEMP', 'raw'),
    'power_factor        ': ('POWER_FACTOR', 'pf_raw'),
    'cumulative_energy   ': ('TOTAL_ENERGY', 'energy_kwh_to_Wh'),
    'alarm1              ': ('ERROR_CODE1', 'raw'),
    'alarm2              ': ('ERROR_CODE2', 'raw'),
    'alarm3              ': ('ERROR_CODE3', 'raw'),
}
