# -*- coding: utf-8 -*-
"""
MUST Inverter Modbus Register Map
Based on MUST Modbus Protocol 
Protocol Name: must
MPPT: 2 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-03
"""



class RegisterMap:
    """MUST Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    DEVICE_MODEL_PDF                         = 0x0000  # TEXT
    FW_VERSION_M                             = 0x000A  # U16
    FW_VERSION_L                             = 0x000B  # U16
    FW_VERSION2H                             = 0x000C  # ASCII
    FW_VERSION2M                             = 0x000D  # U16
    FW_VERSION2L                             = 0x000E  # U16
    SERIAL_NO_5                              = 0x0017  # ASCII
    SERIAL_NO_4                              = 0x0018  # U16
    SERIAL_NO_3                              = 0x0019  # U16
    SERIAL_NO_2                              = 0x001A  # U16
    SERIAL_NO_1                              = 0x001B  # U16
    PFMODEL                                  = 0x0063  # U16
    GRID_FAULTRECORD_3_VALUE                 = 0x0068  # U16
    GRID_FAULTRECORD_4_CODE                  = 0x0069  # U16
    GRID_FAULTRECORD_4_YEARMONTH             = 0x006A  # U16
    GRID_FAULTRECORD_4_DAYHOUR               = 0x006B  # U16
    GRID_FAULTRECORD_4_MINSEC                = 0x006C  # U16
    GRID_FAULTRECORD_4_VALUE                 = 0x006D  # U16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    INVERTER_STATUS                          = 0x0000  # U16
    ON_OFF                                   = 0x0000  # U16
    PPV_H                                    = 0x0001  # U16, scale W 0.1
    V1_00                                    = 0x0001  # U16
    PPV_L                                    = 0x0002  # U16, scale W 0.1
    V1_10                                    = 0x0002  # U16
    PF_CMDMEMORYSTATE                        = 0x0002  # U16
    VPV1                                     = 0x0003  # U16, scale V 0.1
    V2_01                                    = 0x0003  # U16
    ACTIVE_PRATE                             = 0x0003  # U16
    PV1CURR                                  = 0x0004  # U16, scale A 0.1
    REACTIVE_PRATE                           = 0x0004  # U16
    PV1WATT_H                                = 0x0005  # U16, scale W 0.1
    PV1WATT_L                                = 0x0006  # U16, scale W 0.1
    PMAX_H                                   = 0x0006  # U16, scale VA 0.1
    VPV2                                     = 0x0007  # U16, scale V 0.1
    PMAX_L                                   = 0x0007  # U16, scale VA 0.1
    PV2CURR                                  = 0x0008  # U16, scale A 0.1
    VNORMAL                                  = 0x0008  # U16, scale V 0.1
    PV_POWER                                 = 0x000B  # U16, scale W 0.1
    FREQUENCY                                = 0x000D  # U16, scale Hz 0.01
    L1_VOLTAGE                               = 0x000E  # U16, scale V 0.1
    PAC1_H                                   = 0x0010  # U16, scale VA 0.1
    PAC1_L                                   = 0x0011  # U16, scale VA 0.1
    L2_VOLTAGE                               = 0x0012  # U16, scale V 0.1
    L2_CURRENT                               = 0x0013  # U16, scale A 0.1
    V3_00                                    = 0x0013  # U16
    PAC2_H                                   = 0x0014  # U16, scale VA 0.1
    V3_01                                    = 0x0014  # U16
    PAC2_L                                   = 0x0015  # U16, scale VA 0.1
    V3_02                                    = 0x0015  # U16
    L3_VOLTAGE                               = 0x0016  # U16, scale V 0.1
    V3_03                                    = 0x0016  # U16
    L3_CURRENT                               = 0x0017  # U16, scale A 0.1
    V3_04                                    = 0x0017  # U16
    PAC3_L                                   = 0x0019  # U16, scale VA 0.1
    ENERGY_TODAY_H                           = 0x001A  # U16, scale KWH 0.1
    ENERGY_TODAY_L                           = 0x001B  # U16, scale KWH 0.1
    ENERGY_TOTAL_H                           = 0x001C  # U16, scale KWH 0.1
    MOUDLE_H                                 = 0x001C  # U16
    ENERGY_TOTAL_L                           = 0x001D  # U16, scale KWH 0.1
    MOUDLE_L                                 = 0x001D  # U16
    TIME_TOTAL_H                             = 0x001E  # U16
    COM_ADDRESS                              = 0x001E  # U16
    TEMPERATURE                              = 0x0020  # U16
    AUTO_TEST_START                          = 0x0022  # U16
    FAULT_CODE                               = 0x0028  # U16
    IPMTEMPERATURE                           = 0x0029  # U16
    SYS_YEAR                                 = 0x002D  # U16
    SYS_MONTH                                = 0x002E  # U16
    SYS_DAY                                  = 0x002F  # U16
    EPV1_TODAY_H                             = 0x0030  # U16
    SYS_HOUR                                 = 0x0030  # U16
    EPV1_TODAY_L                             = 0x0031  # U16, scale kWh 0.1
    SYS_MIN                                  = 0x0031  # U16
    EPV1_TOTAL_H                             = 0x0032  # U16
    SYS_SEC                                  = 0x0032  # U16
    EPV1_TOTAL_L                             = 0x0033  # U16, scale kWh 0.1
    EPV2_TODAY_H                             = 0x0034  # U16
    EPV2_TOTAL_H                             = 0x0036  # U16
    EPV2_TOTAL_L                             = 0x0037  # U16, scale kWh 0.1
    EPV_TOTAL_H                              = 0x0038  # U16
    EPV_TOTAL_L                              = 0x0039  # U16, scale kWh 0.1
    WARNING_CODE                             = 0x0040  # U16
    MODBUS_VERSION                           = 0x0049  # U16
    FREQ_DERATE_START                        = 0x0051  # U16
    GRID_FAULTRECORD_1_CODE                  = 0x005A  # U16
    PFLINE_P1_L_P                            = 0x005A  # U16
    GRID_FAULTRECORD_1_YEARMONTH             = 0x005B  # U16
    GRID_FAULTRECORD_1_DAYHOUR               = 0x005C  # U16
    PFLINE_P2_L_P                            = 0x005C  # U16
    GRID_FAULTRECORD_1_MINSEC                = 0x005D  # U16
    PFLINE_P2_P_F                            = 0x005D  # U16
    GRID_FAULTRECORD_1_VALUE                 = 0x005E  # U16
    PFLINE_P3_L_P                            = 0x005E  # U16
    GRID_FAULTRECORD_2_CODE                  = 0x005F  # U16
    PFLINE_P3_P_F                            = 0x005F  # U16
    PFLINE_P4_L_P                            = 0x0060  # U16
    GRID_FAULTRECORD_2_DAYHOUR               = 0x0061  # U16
    PFLINE_P4_P_F                            = 0x0061  # U16
    GRID_FAULTRECORD_3_CODE                  = 0x0064  # U16
    FLRATE                                   = 0x0064  # U16
    GRID_FAULTRECORD_3_YEARMONTH             = 0x0065  # U16
    GRID_FAULTRECORD_3_DAYHOUR               = 0x0066  # U16
    GRID_FAULTRECORD_3_MINSEC                = 0x0067  # U16
    GRID_FAULTRECORD_5_DAY                   = 0x0070  # U16
    GRID_FAULTRECORD_5_MINSEC                = 0x0071  # U16
    GRID_FAULTRECORD_5_VALUE                 = 0x0072  # U16
    B_TEST_PROCESS8_B_AUTO_TEST_STEP         = 0x0087  # U16
    W_AUTO_TEST_RESULT                       = 0x0088  # U16
    C_TEST_STEP_STOP                         = 0x0089  # U16
    VALUE_LIMIT                              = 0x008B  # U16, scale V 0.1
    TIME_LIMIT                               = 0x008C  # U16
    TEST_VALUE                               = 0x008E  # U16, scale V 0.1
    TEST_TREAT_VALUE                         = 0x008F  # U16, scale V 0.1
    TEST_TREAT_TIME                          = 0x0090  # U16
    POWERFACTOR                              = 0x2710  # U16

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    REAL_VALUE                               = 0x008D  # U16, scale V 0.1

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    PV2WATT_H                                = 0x0009  # U16, scale W 0.1
    PV2WATT_L                                = 0x000A  # U16, scale W 0.1
    L1_CURRENT                               = 0x000F  # U16, scale A 0.1
    LCDLANGUAGE                              = 0x000F  # U16
    PAC3_H                                   = 0x0018  # U16, scale VA 0.1
    TIME_TOTAL_L                             = 0x001F  # U16
    EPV2_TODAY_L                             = 0x0035  # U16, scale kWh 0.1
    GRID_FAULTRECORD_5_CODE                  = 0x006E  # U16
    GRID_FAULTRECORD_5_YEARMONTH             = 0x006F  # U16

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    S_PHASE_VOLTAGE                          = L2_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT

    # --- RTU modbus_handler / simulator 필수 alias ---
    INVERTER_MODE                            = INVERTER_STATUS
    AC_POWER                                 = PAC1_H
    TOTAL_ENERGY                             = ENERGY_TOTAL_H
    INNER_TEMP                               = TEMPERATURE
    MPPT1_VOLTAGE                            = VPV1
    MPPT1_CURRENT                            = PV1CURR
    MPPT2_VOLTAGE                            = VPV2
    MPPT2_CURRENT                            = PV2CURR
    ERROR_CODE1                              = FAULT_CODE
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834




class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x0009) — Bit field"""
    BITS = {
        0:  "Inverter over dc-bias current",
        1:  "Inverter relay abnormal",
        2:  "Remote off",
        3:  "Inverter over temperature",
        4:  "GFCI abnormal",
        5:  "PV string reverse",
        6:  "System type error",
        7:  "Fan abnormal",
        8:  "Dc-link unbalance or under voltage",
        9:  "Dc-link over voltage",
        10:  "Internal communication error",
        11:  "Software incompatibility",
        12:  "Internal storage error",
        13:  "Data inconsistency",
        14:  "Inverter abnormal",
        15:  "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x000A) — Bit field"""
    BITS = {
        0:  "Grid over voltage",
        1:  "Grid under voltage",
        2:  "Grid absent",
        3:  "Grid over frequency",
        4:  "Grid under frequency",
        5:  "PV over voltage",
        6:  "PV insulation abnormal",
        7:  "Leakage current abnormal",
        8:  "Inverter in power limit state",
        9:  "Internal power supply abnormal",
        10:  "PV string abnormal",
        11:  "PV under voltage",
        12:  "PV irradiation weak",
        13:  "Grid abnormal",
        14:  "Arc fault detection",
        15:  "AC moving average voltage high",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x000F) — Bit field"""
    BITS = {
        0:  "Reserved",
        1:  "Logger/E-Display EEPROM fail",
        2:  "Reserved",
        3:  "Single tracker detect warning",
        4:  "AFCI lost",
        5:  "Data logger lost",
        6:  "Meter lost",
        7:  "Inverter lost",
        8:  "Grid N abnormal",
        9:  "Surge Protection Devices (SPD) defective",
        10:  "Parallel ID warning",
        11:  "Parallel SYN signal warning",
        12:  "Parallel BAT abnormal",
        13:  "Parallel GRID abnormal",
        14:  "Generator voltage abnormal",
        15:  "Reserved",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x000F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x0018) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x001F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x0035) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x006E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x006F) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class MustStatusConverter:
    """MUST INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = MustStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 2
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0)."""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-2)."""
    if mppt_num < 1 or mppt_num > 2:
        raise ValueError(f"MPPT number must be 1-2, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=0):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-2)."""
    if tracker_num < 1 or tracker_num > 2:
        raise ValueError(f"Tracker number must be 1-2, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=0):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 2:
        raise ValueError(f"MPPT number must be 1-2, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=0):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=0):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'DEVICE_MODEL_PDF': 'TEXT',
    'INVERTER_STATUS': 'U16',
    'ON_OFF': 'U16',
    'PPV_H': 'U16',
    'V1_00': 'U16',
    'PPV_L': 'U16',
    'V1_10': 'U16',
    'PF_CMDMEMORYSTATE': 'U16',
    'VPV1': 'U16',
    'V2_01': 'U16',
    'ACTIVE_PRATE': 'U16',
    'PV1CURR': 'U16',
    'REACTIVE_PRATE': 'U16',
    'PV1WATT_H': 'U16',
    'PV1WATT_L': 'U16',
    'PMAX_H': 'U16',
    'VPV2': 'U16',
    'PMAX_L': 'U16',
    'PV2CURR': 'U16',
    'VNORMAL': 'U16',
    'PV2WATT_H': 'U16',
    'FW_VERSION_M': 'U16',
    'PV2WATT_L': 'U16',
    'FW_VERSION_L': 'U16',
    'PV_POWER': 'U16',
    'FW_VERSION2H': 'ASCII',
    'FW_VERSION2M': 'U16',
    'FREQUENCY': 'U16',
    'FW_VERSION2L': 'U16',
    'L1_VOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'LCDLANGUAGE': 'U16',
    'PAC1_H': 'U16',
    'PAC1_L': 'U16',
    'L2_VOLTAGE': 'U16',
    'L2_CURRENT': 'U16',
    'V3_00': 'U16',
    'PAC2_H': 'U16',
    'V3_01': 'U16',
    'PAC2_L': 'U16',
    'V3_02': 'U16',
    'L3_VOLTAGE': 'U16',
    'V3_03': 'U16',
    'SERIAL_NO_5': 'ASCII',
    'L3_CURRENT': 'U16',
    'V3_04': 'U16',
    'SERIAL_NO_4': 'U16',
    'PAC3_H': 'U16',
    'SERIAL_NO_3': 'U16',
    'PAC3_L': 'U16',
    'SERIAL_NO_2': 'U16',
    'ENERGY_TODAY_H': 'U16',
    'SERIAL_NO_1': 'U16',
    'ENERGY_TODAY_L': 'U16',
    'ENERGY_TOTAL_H': 'U16',
    'MOUDLE_H': 'U16',
    'ENERGY_TOTAL_L': 'U16',
    'MOUDLE_L': 'U16',
    'TIME_TOTAL_H': 'U16',
    'COM_ADDRESS': 'U16',
    'TIME_TOTAL_L': 'U16',
    'TEMPERATURE': 'U16',
    'AUTO_TEST_START': 'U16',
    'FAULT_CODE': 'U16',
    'IPMTEMPERATURE': 'U16',
    'SYS_YEAR': 'U16',
    'SYS_MONTH': 'U16',
    'SYS_DAY': 'U16',
    'EPV1_TODAY_H': 'U16',
    'SYS_HOUR': 'U16',
    'EPV1_TODAY_L': 'U16',
    'SYS_MIN': 'U16',
    'EPV1_TOTAL_H': 'U16',
    'SYS_SEC': 'U16',
    'EPV1_TOTAL_L': 'U16',
    'EPV2_TODAY_H': 'U16',
    'EPV2_TODAY_L': 'U16',
    'EPV2_TOTAL_H': 'U16',
    'EPV2_TOTAL_L': 'U16',
    'EPV_TOTAL_H': 'U16',
    'EPV_TOTAL_L': 'U16',
    'WARNING_CODE': 'U16',
    'MODBUS_VERSION': 'U16',
    'FREQ_DERATE_START': 'U16',
    'GRID_FAULTRECORD_1_CODE': 'U16',
    'PFLINE_P1_L_P': 'U16',
    'GRID_FAULTRECORD_1_YEARMONTH': 'U16',
    'GRID_FAULTRECORD_1_DAYHOUR': 'U16',
    'PFLINE_P2_L_P': 'U16',
    'GRID_FAULTRECORD_1_MINSEC': 'U16',
    'PFLINE_P2_P_F': 'U16',
    'GRID_FAULTRECORD_1_VALUE': 'U16',
    'PFLINE_P3_L_P': 'U16',
    'GRID_FAULTRECORD_2_CODE': 'U16',
    'PFLINE_P3_P_F': 'U16',
    'PFLINE_P4_L_P': 'U16',
    'GRID_FAULTRECORD_2_DAYHOUR': 'U16',
    'PFLINE_P4_P_F': 'U16',
    'PFMODEL': 'U16',
    'GRID_FAULTRECORD_3_CODE': 'U16',
    'FLRATE': 'U16',
    'GRID_FAULTRECORD_3_YEARMONTH': 'U16',
    'GRID_FAULTRECORD_3_DAYHOUR': 'U16',
    'GRID_FAULTRECORD_3_MINSEC': 'U16',
    'GRID_FAULTRECORD_3_VALUE': 'U16',
    'GRID_FAULTRECORD_4_CODE': 'U16',
    'GRID_FAULTRECORD_4_YEARMONTH': 'U16',
    'GRID_FAULTRECORD_4_DAYHOUR': 'U16',
    'GRID_FAULTRECORD_4_MINSEC': 'U16',
    'GRID_FAULTRECORD_4_VALUE': 'U16',
    'GRID_FAULTRECORD_5_CODE': 'U16',
    'GRID_FAULTRECORD_5_YEARMONTH': 'U16',
    'GRID_FAULTRECORD_5_DAY': 'U16',
    'GRID_FAULTRECORD_5_MINSEC': 'U16',
    'GRID_FAULTRECORD_5_VALUE': 'U16',
    'B_TEST_PROCESS8_B_AUTO_TEST_STEP': 'U16',
    'W_AUTO_TEST_RESULT': 'U16',
    'C_TEST_STEP_STOP': 'U16',
    'VALUE_LIMIT': 'U16',
    'TIME_LIMIT': 'U16',
    'REAL_VALUE': 'U16',
    'TEST_VALUE': 'U16',
    'TEST_TREAT_VALUE': 'U16',
    'TEST_TREAT_TIME': 'U16',
    'POWERFACTOR': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False

READ_BLOCKS = [
    {'start': 0x0000, 'count': 50, 'fc': 3},    # 0x0000-0x0031 main monitoring
]

DATA_PARSER = {
    'mode'              : 'INVERTER_MODE',
    'r_voltage'         : 'R_PHASE_VOLTAGE',
    's_voltage'         : 'S_PHASE_VOLTAGE',
    't_voltage'         : 'T_PHASE_VOLTAGE',
    'r_current'         : 'R_PHASE_CURRENT',
    's_current'         : 'S_PHASE_CURRENT',
    't_current'         : 'T_PHASE_CURRENT',
    'frequency'         : 'FREQUENCY',
    'ac_power'          : 'AC_POWER',
    'temperature'       : 'INNER_TEMP',
    'cumulative_energy' : 'TOTAL_ENERGY',
    'alarm1'            : 'ERROR_CODE1',
    'mppt1_voltage'     : 'MPPT1_VOLTAGE',
    'mppt1_current'     : 'MPPT1_CURRENT',
    'mppt2_voltage'     : 'MPPT2_VOLTAGE',
    'mppt2_current'     : 'MPPT2_CURRENT',
}

