# -*- coding: utf-8 -*-
"""
Schneider Electric Conext TL Inverter Modbus Register Map
Based on Schneider Electric Conext TL Modbus Protocol
Protocol Name: schneider
MPPT: 2 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04
"""


class RegisterMap:
    """Schneider Electric Conext TL Inverter Register Addresses."""

    # ── Device Information (FC03) ──────────────────────────────────────────
    PRODUCT_MODEL_START     = 0x0001   # 0x0001-0x0009: Product Model Designation (STRING, 9 regs)
    SERIAL_NUMBER_START     = 0x0014   # 0x0014-0x001D: Serial Number (STRING, 10 regs)
    SW_PART_NUM_A_START     = 0x0082   # 0x0082-0x008B: SW Part Number Processor A (STRING, 10 regs)
    SW_PART_NUM_B_START     = 0x0096   # 0x0096-0x009F: SW Part Number Processor B (STRING, 10 regs)
    SW_PART_NUM_C_START     = 0x00AA   # 0x00AA-0x00B3: SW Part Number Processor C (STRING, 10 regs)

    # ── Energy / Operation Counters (FC03) ─────────────────────────────────
    ENERGY_SINCE_COMM_HIGH  = 0x0802   # UINT32 high word, unit kWh
    ENERGY_SINCE_COMM_LOW   = 0x0803   # UINT32 low  word
    ENERGY_YESTERDAY_HIGH   = 0x0804   # UINT32 high word, unit kWh
    ENERGY_YESTERDAY_LOW    = 0x0805   # UINT32 low  word
    ENERGY_TODAY_1DAY_HIGH  = 0x0806   # UINT32 high word, unit kWh
    ENERGY_TODAY_1DAY_LOW   = 0x0807   # UINT32 low  word
    OPERATING_HOURS_HIGH    = 0x081E   # UINT32 high word
    OPERATING_HOURS_LOW     = 0x081F   # UINT32 low  word

    # ── Status & Temperatures (FC03) ───────────────────────────────────────
    OPERATIONAL_MODE_STATE  = 0x1700   # UINT16 — operational mode
    TEMPERATURE_1_CTRL      = 0x1701   # INT16, 0.1°C — NTC on control board
    TEMPERATURE_2_BOOST1    = 0x1702   # INT16, 0.1°C — Boost module 1
    TEMPERATURE_3_BOOST2    = 0x1703   # INT16, 0.1°C — Boost module 2
    TEMPERATURE_4_INV       = 0x1704   # INT16, 0.1°C — Inverter module

    # ── AC Power Quality (FC03) ────────────────────────────────────────────
    APPARENT_POWER          = 0x17F1   # UINT16, VA
    REACTIVE_POWER_VAR      = 0x17F4   # INT16, VAr
    # Line voltages (L-L), Conext TL uses line voltages, not phase voltages
    L1_VOLTAGE              = 0x17F8   # INT16, scale 0.1V — Vab (L1-L2)
    L2_VOLTAGE              = 0x17F9   # INT16, scale 0.1V — Vbc (L2-L3)
    L3_VOLTAGE              = 0x17FA   # INT16, scale 0.1V — Vca (L3-L1)
    L1_CURRENT              = 0x17FB   # INT16, scale 0.1A — Phase A
    L2_CURRENT              = 0x17FC   # INT16, scale 0.1A — Phase B
    L3_CURRENT              = 0x17FD   # INT16, scale 0.1A — Phase C
    REAL_POWER_TOTAL        = 0x17FE   # INT16, W — total real power

    # ── PV Input Channel 1 (FC03) ──────────────────────────────────────────
    PV1_VOLTAGE             = 0x17FF   # INT16, scale 0.1V
    PV1_CURRENT             = 0x1800   # INT16, scale 0.01A
    PV1_POWER               = 0x1801   # INT16, W

    # ── DC Bus (FC03) ──────────────────────────────────────────────────────
    DC_VOLTAGE              = 0x180D   # UINT16, scale 0.1V

    # ── Frequency & Per-Phase Real Power (FC03) ────────────────────────────
    FREQUENCY_A             = 0x1818   # UINT16, scale 0.01Hz — Phase A
    FREQUENCY_B             = 0x1819   # UINT16, scale 0.01Hz — Phase B
    FREQUENCY_C             = 0x181A   # UINT16, scale 0.01Hz — Phase C
    PHASE_A_REAL_POWER      = 0x181B   # INT16, W
    PHASE_B_REAL_POWER      = 0x181C   # INT16, W
    PHASE_C_REAL_POWER      = 0x181D   # INT16, W

    # ── Fault & PV Channel 2 (FC03) ────────────────────────────────────────
    FAULT_CODE              = 0x1828   # UINT16
    PV2_VOLTAGE             = 0x1829   # INT16, scale 0.1V
    PV2_CURRENT             = 0x182A   # INT16, scale 0.01A
    PV2_POWER               = 0x182F   # INT16, W

    # ── DER-AVM / Control Registers (FC16) ────────────────────────────────
    DER_POWER_FACTOR_SET    = 0xF9FB   # User Phase Angle (power factor set)
    DER_ACTIVE_POWER_PCT    = 0xFA19   # User Active Power Limit
    DER_REACTIVE_POWER_PCT  = 0xFA1B   # User Reactive Power Reference
    DER_ACTION_MODE         = 0xFA60   # Reactive Power Mode Select
    INVERTER_ON_OFF         = 0x1700   # Write 0x0014 → Standby (off)

    # ── R/S/T Phase Aliases ────────────────────────────────────────────────
    R_VOLTAGE               = L1_VOLTAGE
    S_VOLTAGE               = L2_VOLTAGE
    T_VOLTAGE               = L3_VOLTAGE
    R_CURRENT               = L1_CURRENT
    S_CURRENT               = L2_CURRENT
    T_CURRENT               = L3_CURRENT

    # ── Standard Handler Compatibility Aliases ─────────────────────────────
    R_PHASE_VOLTAGE         = L1_VOLTAGE
    S_PHASE_VOLTAGE         = L2_VOLTAGE
    T_PHASE_VOLTAGE         = L3_VOLTAGE
    R_PHASE_CURRENT         = L1_CURRENT
    S_PHASE_CURRENT         = L2_CURRENT
    T_PHASE_CURRENT         = L3_CURRENT

    # ── RTU Mandatory Aliases ──────────────────────────────────────────────
    INVERTER_MODE           = OPERATIONAL_MODE_STATE
    AC_POWER                = REAL_POWER_TOTAL        # INT16, W
    AC_POWER_VAL            = REAL_POWER_TOTAL
    TOTAL_ENERGY            = ENERGY_SINCE_COMM_HIGH  # UINT32 high word
    INNER_TEMP              = TEMPERATURE_1_CTRL      # INT16, 0.1°C
    TEMPERATURE_VAL         = TEMPERATURE_1_CTRL
    MPPT1_VOLTAGE           = PV1_VOLTAGE
    MPPT1_CURRENT           = PV1_CURRENT
    MPPT2_VOLTAGE           = PV2_VOLTAGE
    MPPT2_CURRENT           = PV2_CURRENT
    ERROR_CODE1             = FAULT_CODE
    FREQUENCY               = FREQUENCY_A


# ── Operational Mode State mapping ─────────────────────────────────────────
# 0x0001 = Self-test / Initial
# 0x0002 = Reconnecting  → STANDBY
# 0x0003 = Online        → ON_GRID
# 0x0014 = Standby       → STANDBY
# 0x0015 = No DC         → SHUTDOWN
# 0x0016 = Alarm         → FAULT

class InverterMode:
    INITIAL  = 0x00
    STANDBY  = 0x01
    ON_GRID  = 0x03
    FAULT    = 0x05
    SHUTDOWN = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")


class DeviceType:
    RTU                = 0
    INVERTER           = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER        = 3
    PROTECTION_RELAY   = 4

    @classmethod
    def to_string(cls, d):
        return {
            0: "RTU",
            1: "Inverter",
            2: "Environment Sensor",
            3: "Power Meter",
            4: "Protection Relay",
        }.get(d, f"Unknown({d})")


class ControlMode:
    NONE    = "NONE"
    DER_AVM = "DER_AVM"


class SchneiderStatusConverter:
    """Map raw 0x1700 Operational Mode State → InverterMode constant."""
    STATUS_MAP = {
        0x0001: InverterMode.INITIAL,    # Self-test / Initial
        0x0002: InverterMode.STANDBY,    # Reconnecting
        0x0003: InverterMode.ON_GRID,    # Online
        0x0014: InverterMode.STANDBY,    # Standby
        0x0015: InverterMode.SHUTDOWN,   # No DC
        0x0016: InverterMode.FAULT,      # Alarm
    }

    @classmethod
    def to_inverter_mode(cls, raw):
        return cls.STATUS_MAP.get(raw, InverterMode.INITIAL)


StatusConverter = SchneiderStatusConverter


SCALE = {
    'voltage':           0.1,
    'current':           0.01,
    'power':             0.1,
    'frequency':         0.01,
    'power_factor':      0.001,
    'dea_current':       0.1,
    'dea_voltage':       0.1,
    'dea_active_power':  0.1,
    'dea_reactive_power': 1,
    'dea_frequency':     0.1,
    'iv_voltage':        0.1,
    'iv_current':        0.1,
}

MPPT_CHANNELS = 2
STRING_CHANNELS = 0
STRING_CURRENT_MONITOR = False


def registers_to_u32(low, high):
    """Combine two 16-bit registers into an unsigned 32-bit value."""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two 16-bit registers into a signed 32-bit value."""
    v = (high << 16) | low
    return v - 0x100000000 if v >= 0x80000000 else v


# ── Read Blocks ─────────────────────────────────────────────────────────────
# Optimised contiguous ranges — minimises transaction count.
READ_BLOCKS = [
    # Mode state + 4 temperature sensors  (0x1700-0x1704, 5 regs)
    {'start': 0x1700, 'count': 5,  'fc': 3},
    # Apparent power … PV1 voltage         (0x17F1-0x17FF, 15 regs)
    # covers 0x17F1 apparent, 0x17F4 reactive, 0x17F8-0x17FE voltages/currents/power, 0x17FF pv1v
    {'start': 0x17F1, 'count': 15, 'fc': 3},
    # PV1 current/power … PV2 power        (0x1800-0x182F, 48 regs)
    # covers pv1i/p, DC bus, freq A/B/C, phase powers, fault, pv2v/i, pv2p
    {'start': 0x1800, 'count': 48, 'fc': 3},
    # Energy since commissioning (high + low word)  (0x0802-0x0803)
    {'start': 0x0802, 'count': 2,  'fc': 3},
    # Operating hours (high + low word)             (0x081E-0x081F)
    {'start': 0x081E, 'count': 2,  'fc': 3},
]

# ── Data Parser ──────────────────────────────────────────────────────────────
# Maps RTU field names → RegisterMap attribute names used by modbus_handler.
DATA_PARSER = {
    'mode':             'INVERTER_MODE',
    'r_voltage':        'R_PHASE_VOLTAGE',
    's_voltage':        'S_PHASE_VOLTAGE',
    't_voltage':        'T_PHASE_VOLTAGE',
    'r_current':        'R_PHASE_CURRENT',
    's_current':        'S_PHASE_CURRENT',
    't_current':        'T_PHASE_CURRENT',
    'frequency':        'FREQUENCY',
    'ac_power':         'AC_POWER',
    'temperature':      'INNER_TEMP',
    'cumulative_energy':'TOTAL_ENERGY',
    'alarm1':           'ERROR_CODE1',
    'mppt1_voltage':    'MPPT1_VOLTAGE',
    'mppt1_current':    'MPPT1_CURRENT',
    'mppt2_voltage':    'MPPT2_VOLTAGE',
    'mppt2_current':    'MPPT2_CURRENT',
}
