# -*- coding: utf-8 -*-
"""
SMA Inverter Modbus Register Map
Based on SMA STP/SHP SunSpec Modbus Protocol
Protocol Name: sma
MPPT: 1 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04

SunSpec base: PLC 40001 = protocol address 40000 = 0x9C40
Protocol address (0-based) = PLC address - 1
"""


class RegisterMap:
    # -------------------------------------------------------------------------
    # SunSpec Common Block (PLC 40001–40070 → protocol 40000–40069)
    # -------------------------------------------------------------------------
    SUNSPEC_ID              = 0x9C40  # U32  (2 regs) SunSpec ID "SunS"
    MANUFACTURER            = 0x9C44  # STRING (16 regs)
    MODEL                   = 0x9C54  # STRING (16 regs)
    VERSION                 = 0x9C6C  # STRING (8 regs)
    SERIAL_NUMBER           = 0x9C74  # STRING (16 regs)
    DEVICE_ADDRESS          = 0x9C84  # U16

    # -------------------------------------------------------------------------
    # SunSpec Inverter Block Model 103 (3-phase)
    # PLC 40186 → protocol 40185 = 0x9CF9
    # -------------------------------------------------------------------------
    SUNSPEC_INVERTER_DID    = 0x9CFA  # U16  Model ID (103 = 3-phase AC inverter)
    SUNSPEC_INVERTER_LEN    = 0x9CFB  # U16  Block length

    # AC Current
    AC_CURRENT              = 0x9CFC  # int16 AC current sum (A), SF at A_SF
    AC_CURRENT_A            = 0x9CFD  # int16 AC current L1 (AphA)
    AC_CURRENT_B            = 0x9CFE  # int16 AC current L2 (AphB)
    AC_CURRENT_C            = 0x9CFF  # int16 AC current L3 (AphC)
    A_SF                    = 0x9D00  # int16 Current scale factor (typically -1 → ÷10)

    # AC Voltage (line-to-line)
    AC_VOLTAGE_AB           = 0x9D01  # int16 Voltage L1-L2 (PPVphAB)
    AC_VOLTAGE_BC           = 0x9D02  # int16 Voltage L2-L3 (PPVphBC)
    AC_VOLTAGE_CA           = 0x9D03  # int16 Voltage L3-L1 (PPVphCA)

    # AC Voltage (phase-to-neutral)
    AC_VOLTAGE_AN           = 0x9D04  # int16 Voltage L1-N (PPVphA)
    AC_VOLTAGE_BN           = 0x9D05  # int16 Voltage L2-N (PPVphB)
    AC_VOLTAGE_CN           = 0x9D06  # int16 Voltage L3-N (PPVphC)
    V_SF                    = 0x9D07  # int16 Voltage scale factor (typically -1 → ÷10)

    # AC Power
    AC_POWER                = 0x9D08  # int16 Active power W, SF at W_SF
    W_SF                    = 0x9D09  # int16 Active power scale factor (typically 2 → ×100)

    # Frequency
    FREQUENCY               = 0x9D0A  # int16 Frequency Hz, SF at Hz_SF
    HZ_SF                   = 0x9D0B  # int16 Frequency scale factor (typically -3 → ÷1000)

    # Apparent / Reactive Power
    AC_VA                   = 0x9D0C  # int16 Apparent power (VA)
    VA_SF                   = 0x9D0D  # int16 Apparent power SF
    AC_VAR                  = 0x9D0E  # int16 Reactive power (VAr)
    VAR_SF                  = 0x9D0F  # int16 Reactive power SF

    # Power Factor
    AC_PF                   = 0x9D10  # int16 Power factor (PF), SF at PF_SF
    PF_SF                   = 0x9D11  # int16 PF scale factor (typically -2 → ÷100)

    # Total Energy (acc32 = 2 regs, high word first)
    TOTAL_ENERGY_HI         = 0x9D12  # acc32 high word Total yield Wh
    TOTAL_ENERGY_LO         = 0x9D13  # acc32 low word
    WH_SF                   = 0x9D14  # int16 Wh scale factor (typically 3 → ×1000)

    # DC Input (single aggregate channel)
    DC_CURRENT              = 0x9D15  # int16 DC current (DCA), SF at DCA_SF
    DCA_SF                  = 0x9D16  # int16 DC current scale factor
    DC_VOLTAGE              = 0x9D17  # int16 DC voltage (DCV), SF at DCV_SF
    DCV_SF                  = 0x9D18  # int16 DC voltage scale factor
    DC_POWER                = 0x9D19  # int16 DC power (DCW), SF at DCW_SF
    DCW_SF                  = 0x9D1A  # int16 DC power scale factor

    # Temperature
    INNER_TEMP              = 0x9D1B  # int16 Cabinet temperature (TmpCab), SF at Tmp_SF
    TMP_SF                  = 0x9D1F  # int16 Temperature scale factor

    # Operating Status
    INVERTER_MODE           = 0x9D20  # enum16 Operating status (St)
    STATUS_VENDOR           = 0x9D21  # enum16 Vendor-specific status (StVnd)

    # Event Flags
    ERROR_CODE1             = 0x9D22  # bitfield32 high word Event flags (Evt1)
    ERROR_CODE2             = 0x9D23  # bitfield32 low word

    # -------------------------------------------------------------------------
    # SunSpec Nameplate Block (PLC 40238 → protocol 40237 = 0x9D2D)
    # -------------------------------------------------------------------------
    NAMEPLATE_DER_TYPE      = 0x9D30  # U16 DER type (4 = PV device)
    NAMEPLATE_MAX_W         = 0x9D31  # U16 Continuous active power capability

    # -------------------------------------------------------------------------
    # DER-AVM Control Registers (SMA vendor-specific / SunSpec extensions)
    # -------------------------------------------------------------------------
    DER_POWER_FACTOR_SET    = 0x9D50  # int16 Power factor set point
    DER_ACTION_MODE         = 0x9D51  # U16  Control action / mode select
    DER_ACTIVE_POWER_PCT    = 0x9D52  # U16  Active power limit (% × 10)
    DER_REACTIVE_POWER_PCT  = 0x9D53  # int16 Reactive power set point
    INVERTER_ON_OFF         = 0x9D54  # U16  Inverter on/off control

    # -------------------------------------------------------------------------
    # Logical / alias registers for RTU protocol handler compatibility
    # -------------------------------------------------------------------------
    # Phase voltage (phase-to-neutral)
    L1_VOLTAGE              = AC_VOLTAGE_AN
    L2_VOLTAGE              = AC_VOLTAGE_BN
    L3_VOLTAGE              = AC_VOLTAGE_CN

    # Phase current
    L1_CURRENT              = AC_CURRENT_A
    L2_CURRENT              = AC_CURRENT_B
    L3_CURRENT              = AC_CURRENT_C

    # RST aliases
    R_VOLTAGE               = AC_VOLTAGE_AN
    S_VOLTAGE               = AC_VOLTAGE_BN
    T_VOLTAGE               = AC_VOLTAGE_CN
    R_CURRENT               = AC_CURRENT_A
    S_CURRENT               = AC_CURRENT_B
    T_CURRENT               = AC_CURRENT_C
    R_PHASE_VOLTAGE         = AC_VOLTAGE_AN
    S_PHASE_VOLTAGE         = AC_VOLTAGE_BN
    T_PHASE_VOLTAGE         = AC_VOLTAGE_CN
    R_PHASE_CURRENT         = AC_CURRENT_A
    S_PHASE_CURRENT         = AC_CURRENT_B
    T_PHASE_CURRENT         = AC_CURRENT_C

    # Power / energy aliases
    AC_POWER_ALIAS          = AC_POWER
    TOTAL_ENERGY            = TOTAL_ENERGY_HI  # high word of acc32

    # MPPT aliases (single DC input aggregate)
    MPPT1_VOLTAGE           = DC_VOLTAGE
    MPPT1_CURRENT           = DC_CURRENT
    MPPT2_VOLTAGE           = DC_VOLTAGE   # single MPPT — same register
    MPPT2_CURRENT           = DC_CURRENT


class InverterMode:
    INITIAL  = 0x00
    STANDBY  = 0x01
    ON_GRID  = 0x03
    FAULT    = 0x05
    SHUTDOWN = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")


class DeviceType:
    RTU                = 0
    INVERTER           = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER        = 3
    PROTECTION_RELAY   = 4

    @classmethod
    def to_string(cls, d):
        return {
            0: "RTU",
            1: "Inverter",
            2: "Environment Sensor",
            3: "Power Meter",
            4: "Protection Relay",
        }.get(d, f"Unknown({d})")


class ControlMode:
    NONE    = "NONE"
    DER_AVM = "DER_AVM"


class SMAStatusConverter:
    """
    Maps SunSpec/SMA operating status codes (St register at INVERTER_MODE)
    to the unified InverterMode constants used by the RTU protocol handler.

    SMA St codes:
        1 = Off
        2 = Sleeping (auto-shutdown)
        3 = Starting up
        4 = MPPT (normal / On-Grid)
        5 = Throttled (still On-Grid, derated)
        6 = Shutting down
        7 = Fault
        8 = Standby
    """
    STATUS_MAP = {
        1: InverterMode.SHUTDOWN,
        2: InverterMode.STANDBY,
        3: InverterMode.STANDBY,
        4: InverterMode.ON_GRID,
        5: InverterMode.ON_GRID,
        6: InverterMode.SHUTDOWN,
        7: InverterMode.FAULT,
        8: InverterMode.STANDBY,
    }

    @classmethod
    def to_inverter_mode(cls, raw):
        return cls.STATUS_MAP.get(raw, InverterMode.INITIAL)


StatusConverter = SMAStatusConverter

# ---------------------------------------------------------------------------
# Scale factors
# Fixed (not read from SF registers) — modbus_handler uses these as defaults.
# The handler should apply SunSpec dynamic SF registers where available.
# ---------------------------------------------------------------------------
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    # DER-AVM measurement scales
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    # IV scan (not used)
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}

MPPT_CHANNELS    = 1
STRING_CHANNELS  = 0

STRING_CURRENT_MONITOR = False


def registers_to_u32(low, high):
    """Combine two 16-bit registers into a 32-bit unsigned integer."""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two 16-bit registers into a 32-bit signed integer."""
    v = (high << 16) | low
    return v - 0x100000000 if v >= 0x80000000 else v


# ---------------------------------------------------------------------------
# READ_BLOCKS — contiguous register ranges to read in one FC03 request
# Covers the SunSpec Inverter Model 103 block and key DER registers.
# ---------------------------------------------------------------------------
READ_BLOCKS = [
    # SunSpec Common Block (Manufacturer / Model / SN / Address)
    {'start': 0x9C40, 'count': 70, 'fc': 3},
    # SunSpec Inverter Model 103 block (DID through event flags)
    {'start': 0x9CFA, 'count': 46, 'fc': 3},
    # DER-AVM control registers
    {'start': 0x9D50, 'count': 5,  'fc': 3},
]

# ---------------------------------------------------------------------------
# DATA_PARSER — maps RTU protocol field names to RegisterMap attribute names
# ---------------------------------------------------------------------------
DATA_PARSER = {
    'mode':             'INVERTER_MODE',
    'r_voltage':        'R_PHASE_VOLTAGE',
    's_voltage':        'S_PHASE_VOLTAGE',
    't_voltage':        'T_PHASE_VOLTAGE',
    'r_current':        'R_PHASE_CURRENT',
    's_current':        'S_PHASE_CURRENT',
    't_current':        'T_PHASE_CURRENT',
    'frequency':        'FREQUENCY',
    'ac_power':         'AC_POWER',
    'temperature':      'INNER_TEMP',
    'cumulative_energy':'TOTAL_ENERGY',
    'alarm1':           'ERROR_CODE1',
    'mppt1_voltage':    'MPPT1_VOLTAGE',
    'mppt1_current':    'MPPT1_CURRENT',
    'mppt2_voltage':    'MPPT2_VOLTAGE',
    'mppt2_current':    'MPPT2_CURRENT',
}
