# -*- coding: utf-8 -*-
"""
SOFAR Inverter Modbus Register Map
Based on SOFAR Modbus Protocol 
Protocol Name: sofar
MPPT: 4 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-06
"""



class RegisterMap:
    """SOFAR Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    DEVICE_MODEL_PDF                         = 0x0000  # TEXT
    INVERTER_MODE                            = 0x0000  # U16, Operating State (0=wait,2=normal,3=fault)
    FREQUENCY                                = 0x000F  # U16, scale A
    TOTAL_GENERATIONTIME_HIGH_BYTE           = 0x0017  # U16
    INVERTER_MODULETEMPERATURE               = 0x001B  # U16
    INVERTER_INNERTEMPERATURE                = 0x001C  # U16
    INVERTER_BUSVOLTAGE                      = 0x001D  # U16
    L2_CURRENT                               = 0x002C  # U16
    DAILY_ENERGY                             = 0x0036  # U16

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    # POWER_FACTOR: Sofar 프로토콜에 PF 레지스터 없음 → H01 기본값 1000(=1.0) 사용
    TEMPERATURE                              = 0x0001  # U16
    REACTIVE_POWER                           = 0x0003  # U16
    PV2_CURRENT                              = 0x0009  # U16
    PV_POWER                                 = 0x000B  # U16
    PV_VOLTAGE                               = 0x000C  # U16
    L2_VOLTAGE                               = 0x000D  # U16
    B_PHASE_VOLTAGE                          = 0x0011  # U16
    B_PHASE_CURRENT                          = 0x0012  # U16
    C_PHASE_VOLTAGE                          = 0x0013  # U16
    L3_CURRENT                               = 0x0014  # U16
    TOTAL_PRODUCTIONHIGH_BYTE                = 0x0015  # U16
    L3_VOLTAGE                               = 0x0016  # U16
    TOTAL_GENERATIONTIME_LOW_BYTE            = 0x0018  # U16
    THE_DAYGENERATION                        = 0x0019  # U16
    PV1_INOUT_VOLTAGESAMPLING_BY_SLAVE_CPU   = 0x001E  # U16
    ERROR_CODE2                              = 0x001F  # U16
    REG_0X21                                 = 0x0021  # U16
    INPUT_MODE                               = 0x0022  # U16
    CUMULATIVE_ENERGY                        = 0x0023  # U16
    L1_VOLTAGE                               = 0x0026  # U16
    L1_CURRENT                               = 0x0027  # U16
    CT_POWER                                 = 0x0029  # U16
    REG_0X33                                 = 0x0033  # U16
    REG_0X35                                 = 0x0035  # U16
    REG_0X84                                 = 0x0084  # U16
    REG_0X_B8                                = 0x00B8  # U16
    REG_1_PV1_VOLTAGE                        = 0x0105  # U16
    REG_1PV1_CURRENT                         = 0x0106  # U16
    PV2_VOLTAGE                              = 0x0107  # U16
    REG_3PV3_VOLTAGE                         = 0x0109  # U16
    PV3_CURRENT                              = 0x010A  # U16
    PV4_VOLTAGE                              = 0x010B  # U16
    PV4_CURRENT                              = 0x010C  # U16
    REG_0X04                                 = 0x1000  # U16

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    FAULT_5                                  = 0x0005  # U16
    ALARM1                                   = 0x000A  # U16
    REG_0X61                                 = 0x0061  # U16
    FAULT_2                                  = 0x0101  # U16
    FAULT_3                                  = 0x0102  # U16
    FAULT_4                                  = 0x0103  # U16

    # R/S/T Phase Aliases
    R_VOLTAGE                                = L1_VOLTAGE
    R_CURRENT                                = L1_CURRENT
    S_VOLTAGE                                = L2_VOLTAGE
    S_CURRENT                                = L2_CURRENT
    T_VOLTAGE                                = L3_VOLTAGE
    T_CURRENT                                = L3_CURRENT

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    R_PHASE_VOLTAGE                          = L1_VOLTAGE
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT
    S_PHASE_VOLTAGE                          = L2_VOLTAGE  # L2 없음 → 대체

    # --- MPPT alias (modbus_handler: MPPT{N}_ 형식) ---
    PV_STRING_COUNT                          = 4

    # --- RTU modbus_handler / simulator 필수 alias ---
    INNER_TEMP                               = TEMPERATURE
    AC_POWER                                 = PV_POWER
    TOTAL_ENERGY                             = CUMULATIVE_ENERGY
    ERROR_CODE1                              = FAULT_5
    ERROR_CODE3                              = FREQUENCY
    DER_POWER_FACTOR_SET                     = 0x07D0
    DER_ACTION_MODE                          = 0x07D1
    DER_REACTIVE_POWER_PCT                   = 0x07D2
    DER_ACTIVE_POWER_PCT                     = 0x07D3
    INVERTER_ON_OFF                          = 0x0834
    MPPT_NUMBER                              = 0x1A4A  # default MPPT count register
    MPPT1_VOLTAGE                            = PV_VOLTAGE
    MPPT1_CURRENT                            = REG_1PV1_CURRENT
    MPPT2_VOLTAGE                            = PV2_VOLTAGE
    MPPT2_CURRENT                            = PV2_CURRENT
    MPPT3_VOLTAGE                            = REG_3PV3_VOLTAGE
    MPPT3_CURRENT                            = PV3_CURRENT
    MPPT4_VOLTAGE                            = PV4_VOLTAGE
    MPPT4_CURRENT                            = PV4_CURRENT
    CUMULATIVE_ENERGY_LOW                    = CUMULATIVE_ENERGY
    DER_AVM_DIGITAL_METERCONNECT_STATUS      = 0x1210

    # --- STRING alias (Built-in Combiner: MPPT = String, 1:1 매핑) ---
    STRING1_CURRENT                          = MPPT1_CURRENT
    STRING2_CURRENT                          = 0x0108  # PV2 Current (combiner)
    STRING3_CURRENT                          = MPPT3_CURRENT
    STRING4_CURRENT                          = MPPT4_CURRENT



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x0005) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x000A) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x000E) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode4:
    """Error Code Table4 (0x0020) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode5:
    """Error Code Table5 (0x0061) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode6:
    """Error Code Table6 (0x0101) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode7:
    """Error Code Table7 (0x0102) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode8:
    """Error Code Table8 (0x0103) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode9:
    """Error Code Table9 (0x0104) — Bit field"""
    BITS = {
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class SofarStatusConverter:
    """SOFAR INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw

    @classmethod
    def to_solarize(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)

    @classmethod
    def to_h01(cls, raw):
        """RTU 호환 alias"""
        return cls.to_inverter_mode(raw)


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = SofarStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 4
STRING_CHANNELS = 4


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0).
    # Solarize 프로토콜 전용 주소 (0x1050 기반)"""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-4).
    # Solarize 프로토콜 전용 주소 (0x1010 기반)"""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-4)."""
    if tracker_num < 1 or tracker_num > 4:
        raise ValueError(f"Tracker number must be 1-4, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'DEVICE_MODEL_PDF': 'TEXT',
    'POWER_FACTOR': 'U16',
    'TEMPERATURE': 'U16',
    'FREQUENCY': 'U16',
    'REACTIVE_POWER': 'U16',
    'FAULT_5': 'U16',
    'PV2_CURRENT': 'U16',
    'ALARM1': 'U16',
    'PV_POWER': 'U16',
    'PV_VOLTAGE': 'U16',
    'L2_VOLTAGE': 'U16',
    'B_PHASE_VOLTAGE': 'U16',
    'B_PHASE_CURRENT': 'U16',
    'C_PHASE_VOLTAGE': 'U16',
    'L3_CURRENT': 'U16',
    'TOTAL_PRODUCTIONHIGH_BYTE': 'U16',
    'L3_VOLTAGE': 'U16',
    'TOTAL_GENERATIONTIME_HIGH_BYTE': 'U16',
    'TOTAL_GENERATIONTIME_LOW_BYTE': 'U16',
    'THE_DAYGENERATION': 'U16',
    'INVERTER_MODULETEMPERATURE': 'U16',
    'INVERTER_INNERTEMPERATURE': 'U16',
    'INVERTER_BUSVOLTAGE': 'U16',
    'PV1_INOUT_VOLTAGESAMPLING_BY_SLAVE_CPU': 'U16',
    'ERROR_CODE2': 'U16',
    'REG_0X21': 'U16',
    'INPUT_MODE': 'U16',
    'CUMULATIVE_ENERGY': 'U16',
    'L1_VOLTAGE': 'U16',
    'L1_CURRENT': 'U16',
    'CT_POWER': 'U16',
    'L2_CURRENT': 'U16',
    'REG_0X33': 'U16',
    'REG_0X35': 'U16',
    'DAILY_ENERGY': 'U16',
    'REG_0X61': 'U16',
    'REG_0X84': 'U16',
    'REG_0X_B8': 'U16',
    'FAULT_2': 'U16',
    'FAULT_3': 'U16',
    'FAULT_4': 'U16',
    'REG_1_PV1_VOLTAGE': 'U16',
    'REG_1PV1_CURRENT': 'U16',
    'PV2_VOLTAGE': 'U16',
    'REG_3PV3_VOLTAGE': 'U16',
    'PV3_CURRENT': 'U16',
    'PV4_VOLTAGE': 'U16',
    'PV4_CURRENT': 'U16',
    'REG_0X04': 'U16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False



# RTU 배치 읽기 블록 — start/count/fc 지정으로 트랜잭션 최소화
READ_BLOCKS = [
    {'start': 0x0000, 'count': 125, 'fc': 3},
    {'start': 0x007D, 'count':   8, 'fc': 3},
    {'start': 0x00B8, 'count':   1, 'fc': 3},
    {'start': 0x0100, 'count':  13, 'fc': 3},
    {'start': 0x1000, 'count':   1, 'fc': 3},
    {'start': 0x1100, 'count':   1, 'fc': 3},
    {'start': 0x7001, 'count':   1, 'fc': 3},
]



# H01 출력 필드 → RegisterMap 속성명 매핑
# modbus_handler._read_inverter_data_dynamic()이 이 매핑을 사용한다.
DATA_PARSER = {
    'mode                ': 'INVERTER_MODE',
    'r_voltage           ': 'DEA_L1_VOLTAGE (0x03EE~0x03EF); L1_VOLTAGE (0x0026); REG_0X61 (0x0061); FAULT_2 (0x0101); FAULT_3 (0x0102); FAULT_4 (0x0103)',
    's_voltage           ': 'DEA_L2_VOLTAGE (0x03F0~0x03F1); L2_VOLTAGE (0x000D); THE_DAYGENERATION (0x0019); FAULT_5 (0x0005)',
    't_voltage           ': 'DEA_L3_VOLTAGE (0x03F2~0x03F3); L3_VOLTAGE (0x0016); ERROR_CODE2 (0x001F)',
    'r_current           ': 'DEA_L1_CURRENT (0x03E8~0x03E9); INPUT_MODE (0x0022); L1_CURRENT (0x0027)',
    's_current           ': 'DEA_L2_CURRENT (0x03EA~0x03EB); B_PHASE_CURRENT (0x0012); CT_POWER (0x0029); L2_CURRENT (0x002B)',
    't_current           ': 'DEA_L3_CURRENT (0x03EC~0x03ED); L3_CURRENT (0x0014)',
    'frequency           ': 'DEA_FREQUENCY (0x03FA~0x03FB); FREQUENCY (0x0002); REG_0X21 (0x0021); REG_0X04 (0x1000)',
    'ac_power            ': 'DEA_TOTAL_ACTIVE_POWER (0x03F4~0x03F5); B_PHASE_VOLTAGE (0x0011)',
    'cumulative_energy   ': 'REG_0X33 (0x0033); CUMULATIVE_ENERGY (0x0023); REG_0X35 (0x0035); REG_0X_B8 (0x00B8)',
    'alarm1              ': 'ERROR_CODE2 (0x001F); ALARM1 (0x000A)',
    'mppt1_voltage'        : 'PV_VOLTAGE',
    'mppt1_current'        : 'REG_1PV1_CURRENT',
    'mppt2_voltage'        : 'PV2_VOLTAGE',
    'mppt2_current'        : 'PV2_CURRENT',
    'mppt3_voltage'        : 'REG_3PV3_VOLTAGE',
    'mppt3_current'        : 'PV3_CURRENT',
    'mppt4_voltage'        : 'PV4_VOLTAGE',
    'mppt4_current'        : 'PV4_CURRENT',
}



# U32 워드 순서: 'LH' = Low word at lower addr, 'HL' = High word at lower addr
U32_WORD_ORDER = 'LH'


# H01 스칼라 필드 → (RegisterMap 속성명, 변환기 키)
H01_FIELD_MAP = {
    'r_voltage':         ('R_PHASE_VOLTAGE', 'voltage_to_V'),
    's_voltage':         ('S_PHASE_VOLTAGE', 'voltage_to_V'),
    't_voltage':         ('T_PHASE_VOLTAGE', 'voltage_to_V'),
    'r_current':         ('R_PHASE_CURRENT', 'current_to_01A'),
    's_current':         ('S_PHASE_CURRENT', 'current_to_01A'),
    't_current':         ('T_PHASE_CURRENT', 'current_to_01A'),
    'frequency':         ('FREQUENCY', 'frequency_to_01Hz'),
    'ac_power':          ('AC_POWER', 'power_to_W'),
    'pv_power':          ('PV_POWER', 'power_to_W'),
    'power_factor':      ('POWER_FACTOR', 'pf_raw'),
    'cumulative_energy': ('TOTAL_ENERGY', 'energy_kwh_to_Wh'),
    'mode':              ('INVERTER_MODE', 'raw'),
    'alarm1':            ('ERROR_CODE1', 'raw'),
    'alarm2':            ('ERROR_CODE2', 'raw'),
    'alarm3':            ('ERROR_CODE3', 'raw'),
}
