# -*- coding: utf-8 -*-
"""
SolarEdge Inverter Modbus Register Map
Based on SolarEdge SunSpec Logging Protocol v3.2
Protocol Name: solaredge
MPPT: 1 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-04

SunSpec base: PLC 40001 = protocol address 40000 = 0x9C40
Protocol address (0-based) = PLC address - 1
Note: SolarEdge is typically single MPPT/tracker; no string monitoring.
"""


class RegisterMap:
    # -------------------------------------------------------------------------
    # SunSpec Common Block (PLC 40001–40069 → protocol 40000–40068)
    # -------------------------------------------------------------------------
    SUNSPEC_ID              = 0x9C40  # U32  (2 regs) SunSpec ID "SunS"
    C_SUNSPEC_DID           = 0x9C42  # U16  Common block model ID (1)
    MANUFACTURER            = 0x9C44  # STRING (16 regs) C_Manufacturer
    MODEL                   = 0x9C54  # STRING (16 regs) C_Model
    VERSION                 = 0x9C6C  # STRING (8 regs)  C_Version
    SERIAL_NUMBER           = 0x9C74  # STRING (16 regs) C_SerialNumber
    DEVICE_ADDRESS          = 0x9C84  # U16  C_DeviceAddress

    # -------------------------------------------------------------------------
    # SunSpec Inverter Block (Device block at PLC 40069 → protocol 40068)
    # SolarEdge places the inverter model block immediately after common block.
    # -------------------------------------------------------------------------
    DEVICE_SUNSPEC_DID      = 0x9C85  # U16  C_SunSpec_DID (device model ID, e.g. 101/103)
    DEVICE_SUNSPEC_LEN      = 0x9C86  # U16  C_SunSpec_Length

    # AC Current
    AC_CURRENT              = 0x9C87  # int16 I_AC_Current (total AC current)
    AC_CURRENT_A            = 0x9C88  # int16 I_AC_CurrentA (L1 current)
    AC_CURRENT_B            = 0x9C89  # int16 I_AC_CurrentB (L2 current)
    AC_CURRENT_C            = 0x9C8A  # int16 I_AC_CurrentC (L3 current)
    I_AC_CURRENT_SF         = 0x9C8B  # int16 I_AC_Current_SF (scale factor)

    # AC Voltage (line-to-line)
    AC_VOLTAGE_AB           = 0x9C8C  # int16 I_AC_VoltageAB (L1-L2)
    AC_VOLTAGE_BC           = 0x9C8D  # int16 I_AC_VoltageBC (L2-L3)
    AC_VOLTAGE_CA           = 0x9C8E  # int16 I_AC_VoltageCA (L3-L1)

    # AC Voltage (phase-to-neutral)
    AC_VOLTAGE_AN           = 0x9C8F  # int16 I_AC_VoltageAN (L1 = R phase)
    AC_VOLTAGE_BN           = 0x9C90  # int16 I_AC_VoltageBN (L2 = S phase)
    AC_VOLTAGE_CN           = 0x9C91  # int16 I_AC_VoltageCN (L3 = T phase)
    I_AC_VOLTAGE_SF         = 0x9C92  # int16 I_AC_Voltage_SF

    # AC Power
    AC_POWER                = 0x9C93  # int16 I_AC_Power (W)
    I_AC_POWER_SF           = 0x9C94  # int16 I_AC_Power_SF

    # Frequency
    FREQUENCY               = 0x9C95  # int16 I_AC_Frequency (Hz)
    I_AC_FREQUENCY_SF       = 0x9C96  # int16 I_AC_Frequency_SF

    # Apparent / Reactive Power
    AC_VA                   = 0x9C97  # int16 I_AC_VA (apparent power)
    I_AC_VA_SF              = 0x9C98  # int16 I_AC_VA_SF
    AC_VAR                  = 0x9C99  # int16 I_AC_VAR (reactive power)
    I_AC_VAR_SF             = 0x9C9A  # int16 I_AC_VAR_SF

    # Power Factor
    AC_PF                   = 0x9C9B  # int16 I_AC_PF (power factor)
    I_AC_PF_SF              = 0x9C9C  # int16 I_AC_PF_SF

    # Total Energy (acc32 = 2 regs, high word first)
    TOTAL_ENERGY_HI         = 0x9C9D  # acc32 high word I_AC_Energy_WH
    TOTAL_ENERGY_LO         = 0x9C9E  # acc32 low word
    I_AC_ENERGY_WH_SF       = 0x9C9F  # int16 I_AC_Energy_WH_SF

    # DC Input (single tracker / aggregate)
    DC_CURRENT              = 0x9CA0  # int16 I_DC_Current
    I_DC_CURRENT_SF         = 0x9CA1  # int16 I_DC_Current_SF
    DC_VOLTAGE              = 0x9CA2  # int16 I_DC_Voltage
    I_DC_VOLTAGE_SF         = 0x9CA3  # int16 I_DC_Voltage_SF
    DC_POWER                = 0x9CA4  # int16 I_DC_Power
    I_DC_POWER_SF           = 0x9CA5  # int16 I_DC_Power_SF

    # Temperature (PLC 40103 → protocol 40102 = 0x9CA6 is reserved; sink at 40103)
    INNER_TEMP              = 0x9CA7  # int16 I_Temp_Sink (heat sink, °C)
    # PLC 40104–40106 reserved / other temps; SF at PLC 40106 → protocol 40105 = 0x9CA9
    I_TEMP_SF               = 0x9CA9  # int16 I_Temp_SF (shared temperature SF)

    # Operating Status
    INVERTER_MODE           = 0x9CAB  # enum16 I_Status (inverter operating state)
    STATUS_VENDOR           = 0x9CAC  # enum16 I_Status_Vendor

    # -------------------------------------------------------------------------
    # DER-AVM Control Registers (SolarEdge vendor-specific Modbus addresses)
    # -------------------------------------------------------------------------
    # Active power limit: User Active Power Limit (%)
    DER_ACTIVE_POWER_PCT    = 0xFA19  # uint16 User Active Power Limit (% × 10)
    # Reactive power reference: User Reactive Power Reference
    DER_REACTIVE_POWER_PCT  = 0xFA1B  # int16  User Reactive Power Reference
    # Reactive power mode: Reactive Power Mode Select
    DER_ACTION_MODE         = 0xFA60  # uint16 Reactive Power Mode Select
    # Power factor set point: User Phase Angle
    DER_POWER_FACTOR_SET    = 0xF9FB  # int16  User Phase Angle (cos φ × 1000)
    # Inverter on/off (no standard register; placeholder vendor address)
    INVERTER_ON_OFF         = 0xF000  # uint16 Inverter enable/disable (vendor-specific)

    # -------------------------------------------------------------------------
    # Logical / alias registers for RTU protocol handler compatibility
    # -------------------------------------------------------------------------
    # Phase voltage (phase-to-neutral)
    L1_VOLTAGE              = AC_VOLTAGE_AN
    L2_VOLTAGE              = AC_VOLTAGE_BN
    L3_VOLTAGE              = AC_VOLTAGE_CN

    # Phase current
    L1_CURRENT              = AC_CURRENT_A
    L2_CURRENT              = AC_CURRENT_B
    L3_CURRENT              = AC_CURRENT_C

    # RST aliases
    R_VOLTAGE               = AC_VOLTAGE_AN
    S_VOLTAGE               = AC_VOLTAGE_BN
    T_VOLTAGE               = AC_VOLTAGE_CN
    R_CURRENT               = AC_CURRENT_A
    S_CURRENT               = AC_CURRENT_B
    T_CURRENT               = AC_CURRENT_C
    R_PHASE_VOLTAGE         = AC_VOLTAGE_AN
    S_PHASE_VOLTAGE         = AC_VOLTAGE_BN
    T_PHASE_VOLTAGE         = AC_VOLTAGE_CN
    R_PHASE_CURRENT         = AC_CURRENT_A
    S_PHASE_CURRENT         = AC_CURRENT_B
    T_PHASE_CURRENT         = AC_CURRENT_C

    # Power / energy aliases
    AC_POWER_ALIAS          = AC_POWER
    TOTAL_ENERGY            = TOTAL_ENERGY_HI  # high word of acc32

    # MPPT aliases (single DC input tracker)
    MPPT1_VOLTAGE           = DC_VOLTAGE
    MPPT1_CURRENT           = DC_CURRENT
    MPPT2_VOLTAGE           = DC_VOLTAGE   # single MPPT — same register
    MPPT2_CURRENT           = DC_CURRENT

    # Error code alias
    ERROR_CODE1             = STATUS_VENDOR


class InverterMode:
    INITIAL  = 0x00
    STANDBY  = 0x01
    ON_GRID  = 0x03
    FAULT    = 0x05
    SHUTDOWN = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")


class DeviceType:
    RTU                = 0
    INVERTER           = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER        = 3
    PROTECTION_RELAY   = 4

    @classmethod
    def to_string(cls, d):
        return {
            0: "RTU",
            1: "Inverter",
            2: "Environment Sensor",
            3: "Power Meter",
            4: "Protection Relay",
        }.get(d, f"Unknown({d})")


class ControlMode:
    NONE    = "NONE"
    DER_AVM = "DER_AVM"


class SolarEdgeStatusConverter:
    """
    Maps SunSpec/SolarEdge I_Status codes (I_Status register at INVERTER_MODE)
    to the unified InverterMode constants used by the RTU protocol handler.

    SolarEdge I_Status codes:
        1 = Off
        2 = Sleeping (auto-shutdown)
        3 = Starting up
        4 = MPPT (normal / On-Grid)
        5 = Throttled (still On-Grid, derated)
        6 = Shutting down
        7 = Fault
        8 = Standby
    """
    STATUS_MAP = {
        1: InverterMode.SHUTDOWN,
        2: InverterMode.STANDBY,
        3: InverterMode.STANDBY,
        4: InverterMode.ON_GRID,
        5: InverterMode.ON_GRID,
        6: InverterMode.SHUTDOWN,
        7: InverterMode.FAULT,
        8: InverterMode.STANDBY,
    }

    @classmethod
    def to_inverter_mode(cls, raw):
        return cls.STATUS_MAP.get(raw, InverterMode.INITIAL)


StatusConverter = SolarEdgeStatusConverter

# ---------------------------------------------------------------------------
# Scale factors
# Fixed (not read from SF registers) — modbus_handler uses these as defaults.
# The handler should apply SunSpec dynamic SF registers where available.
# ---------------------------------------------------------------------------
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    # DER-AVM measurement scales
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    # IV scan (not used)
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}

MPPT_CHANNELS    = 1
STRING_CHANNELS  = 0

STRING_CURRENT_MONITOR = False


def registers_to_u32(low, high):
    """Combine two 16-bit registers into a 32-bit unsigned integer."""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two 16-bit registers into a 32-bit signed integer."""
    v = (high << 16) | low
    return v - 0x100000000 if v >= 0x80000000 else v


# ---------------------------------------------------------------------------
# READ_BLOCKS — contiguous register ranges to read in one FC03 request
# Covers the SunSpec Common Block, the SolarEdge Inverter block, and the
# vendor-specific DER-AVM control registers (non-contiguous, separate reads).
# ---------------------------------------------------------------------------
READ_BLOCKS = [
    # SunSpec Common Block (Manufacturer / Model / SN / Address)
    {'start': 0x9C40, 'count': 70, 'fc': 3},
    # SunSpec Inverter block: device DID through I_Status_Vendor
    {'start': 0x9C85, 'count': 40, 'fc': 3},
    # DER-AVM vendor registers: active power limit + reactive power reference
    {'start': 0xFA19, 'count': 3,  'fc': 3},
    # DER-AVM reactive power mode select
    {'start': 0xFA60, 'count': 1,  'fc': 3},
    # DER power factor set point
    {'start': 0xF9FB, 'count': 1,  'fc': 3},
]

# ---------------------------------------------------------------------------
# DATA_PARSER — maps RTU protocol field names to RegisterMap attribute names
# ---------------------------------------------------------------------------
DATA_PARSER = {
    'mode':             'INVERTER_MODE',
    'r_voltage':        'R_PHASE_VOLTAGE',
    's_voltage':        'S_PHASE_VOLTAGE',
    't_voltage':        'T_PHASE_VOLTAGE',
    'r_current':        'R_PHASE_CURRENT',
    's_current':        'S_PHASE_CURRENT',
    't_current':        'T_PHASE_CURRENT',
    'frequency':        'FREQUENCY',
    'ac_power':         'AC_POWER',
    'temperature':      'INNER_TEMP',
    'cumulative_energy':'TOTAL_ENERGY',
    'alarm1':           'ERROR_CODE1',
    'mppt1_voltage':    'MPPT1_VOLTAGE',
    'mppt1_current':    'MPPT1_CURRENT',
    'mppt2_voltage':    'MPPT2_VOLTAGE',
    'mppt2_current':    'MPPT2_CURRENT',
}
