"""
Solarize VK50 Inverter Modbus Register Map
Based on Solarize Modbus Protocol
Auto-generated by UDP RTU Model Maker
Date: 2026-03-29 (MPPT: 9→4, String: 24→8)
"""


class RegisterMap:
    """Solarize VK50 Modbus Register Map - Solarize Protocol Compliant"""
    
    # =========================================================================
    # Device Information (0x1A00-0x1A90)
    # =========================================================================
    DEVICE_MODEL = 0x1A00      # 8 regs, ASCII string
    SERIAL_NUMBER = 0x1A10      # 8 regs, ASCII string
    MASTER_FIRMWARE_VERSION = 0x1A1C      # 3 regs, ASCII string
    SLAVE_FIRMWARE_VERSION = 0x1A26      # 3 regs, ASCII string
    MPPT_COUNT = 0x1A3B      # 1 reg, U16
    NOMINAL_VOLTAGE = 0x1A44      # 1 reg, U16, scale 0.1V
    NOMINAL_FREQUENCY = 0x1A45      # 1 reg, U16, scale 0.01Hz
    NOMINAL_POWER_LOW = 0x1A46      # 1 reg, U16, 1W
    NOMINAL_POWER_HIGH = 0x1A4E      # 1 reg, U16, 1W (high word)
    GRID_PHASE_NUMBER = 0x1A48      # 1 reg, U16: 1=single, 2=split, 3=three
    EMS_FIRMWARE_VERSION = 0x1A60      # 3 regs, ASCII string
    LCD_FIRMWARE_VERSION = 0x1A8E      # 3 regs, ASCII string
    
    # Alias for backward compatibility
    FIRMWARE_VERSION = MASTER_FIRMWARE_VERSION
    
    # =========================================================================
    # Inverter Real-time Data - AC Side (0x1001-0x100F)
    # =========================================================================
    MPPT1_VOLTAGE = 0x1010      # U16, scale 0.1V
    MPPT1_CURRENT = 0x1011      # S16, scale 0.01A
    PV_TOTAL_INPUT_POWER_LOW = 0x1048      # U32, scale 0.1W (all MPPT sum)
    L1_VOLTAGE = 0x1001      # U16, scale 0.1V
    L2_VOLTAGE = 0x1006      # U16, scale 0.1V
    L3_VOLTAGE = 0x100B      # U16, scale 0.1V
    L1_CURRENT = 0x1002      # U16, scale 0.01A
    L2_CURRENT = 0x1007      # U16, scale 0.01A
    L3_CURRENT = 0x100C      # U16, scale 0.01A
    GRID_TOTAL_ACTIVE_POWER_LOW = 0x1037      # S32, scale 0.1W (L1+L2+L3)
    POWER_FACTOR = 0x103D      # S16, scale 0.001
    L1_FREQUENCY = 0x1005      # U16, scale 0.01Hz
    TOTAL_ENERGY_LOW = 0x1021      # U32, kWh
    INVERTER_MODE = 0x101D      # U16, see InverterMode class
    ERROR_CODE1 = 0x101E      # U16, bit field
    ERROR_CODE2 = 0x101F      # U16, bit field
    ERROR_CODE3 = 0x1020      # U16, bit field
    L1_POWER_LOW = 0x1003      # S32, scale 0.1W
    L1_POWER_HIGH = 0x1004
    L2_POWER_LOW = 0x1008      # S32, scale 0.1W
    L2_POWER_HIGH = 0x1009
    L2_FREQUENCY = 0x100A      # U16, scale 0.01Hz
    L3_POWER_LOW = 0x100D      # S32, scale 0.1W
    L3_POWER_HIGH = 0x100E
    L3_FREQUENCY = 0x100F      # U16, scale 0.01Hz
    
    # R/S/T Phase Aliases
    R_VOLTAGE = L1_VOLTAGE
    R_CURRENT = L1_CURRENT
    R_POWER_LOW = L1_POWER_LOW
    R_POWER_HIGH = L1_POWER_HIGH
    R_FREQUENCY = L1_FREQUENCY
    S_VOLTAGE = L2_VOLTAGE
    S_CURRENT = L2_CURRENT
    S_POWER_LOW = L2_POWER_LOW
    S_POWER_HIGH = L2_POWER_HIGH
    S_FREQUENCY = L2_FREQUENCY
    T_VOLTAGE = L3_VOLTAGE
    T_CURRENT = L3_CURRENT
    T_POWER_LOW = L3_POWER_LOW
    T_POWER_HIGH = L3_POWER_HIGH
    T_FREQUENCY = L3_FREQUENCY
    
    # =========================================================================
    # MPPT Data (0x1010-0x1093)
    # =========================================================================
    MPPT2_VOLTAGE = 0x1014      # U16, scale 0.1V
    MPPT2_CURRENT = 0x1015      # S16, scale 0.01A
    MPPT3_VOLTAGE = 0x1018      # U16, scale 0.1V
    MPPT3_CURRENT = 0x1019      # S16, scale 0.01A
    MPPT4_VOLTAGE = 0x103E      # U16, scale 0.1V
    MPPT4_CURRENT = 0x103F      # S16, scale 0.01A
    MPPT1_POWER_LOW = 0x1012      # U32, scale 0.1W
    MPPT1_POWER_HIGH = 0x1013
    MPPT2_POWER_LOW = 0x1016      # U32, scale 0.1W
    MPPT2_POWER_HIGH = 0x1017
    MPPT3_POWER_LOW = 0x101A      # U32, scale 0.1W
    MPPT3_POWER_HIGH = 0x101B
    MPPT4_POWER_LOW = 0x1040      # U32, scale 0.1W
    MPPT4_POWER_HIGH = 0x1041
    # =========================================================================
    # Status & Error (0x101C-0x1020)
    # =========================================================================
    INNER_TEMP = 0x101C      # S16, 1C
    
    # =========================================================================
    # Energy Data (0x1021-0x1028)
    # =========================================================================
    TOTAL_ENERGY_HIGH = 0x1022
    TOTAL_GENERATION_TIME_LOW = 0x1023      # U32, Hour
    TOTAL_GENERATION_TIME_HIGH = 0x1024
    TODAY_ENERGY_LOW = 0x1027      # U32, Wh
    TODAY_ENERGY_HIGH = 0x1028
    
    # =========================================================================
    # Grid Power Data (0x1034-0x103D)
    # =========================================================================
    FUSE_OPEN_DATA_LOW = 0x1034      # U16, bit field
    FUSE_OPEN_DATA_HIGH = 0x1035      # U16, bit field
    GRID_TOTAL_ACTIVE_POWER_HIGH = 0x1038
    GRID_TOTAL_REACTIVE_POWER_LOW = 0x1039      # S32, scale 0.1Var (L1+L2+L3)
    GRID_TOTAL_REACTIVE_POWER_HIGH = 0x103A
    PV_TODAY_PEAK_POWER_LOW = 0x103B      # S32, scale 0.1W
    PV_TODAY_PEAK_POWER_HIGH = 0x103C
    
    # Aliases
    GRID_POWER_LOW = GRID_TOTAL_ACTIVE_POWER_LOW
    GRID_POWER_HIGH = GRID_TOTAL_ACTIVE_POWER_HIGH
    
    # =========================================================================
    # PV Total Power (0x1048-0x104C)
    # =========================================================================
    PV_TOTAL_INPUT_POWER_HIGH = 0x1049
    TOTAL_ENERGY_DECIMALS = 0x104C      # U16, Wh (decimals of 0x1021)
    
    # Aliases
    PV_POWER_LOW = PV_TOTAL_INPUT_POWER_LOW
    PV_POWER_HIGH = PV_TOTAL_INPUT_POWER_HIGH
    
    # --- Standard handler compatibility aliases (T03 required) ---
    R_PHASE_VOLTAGE = L1_VOLTAGE
    S_PHASE_VOLTAGE = L2_VOLTAGE
    T_PHASE_VOLTAGE = L3_VOLTAGE
    R_PHASE_CURRENT = L1_CURRENT
    S_PHASE_CURRENT = L2_CURRENT
    T_PHASE_CURRENT = L3_CURRENT
    FREQUENCY = L1_FREQUENCY
    AC_POWER = GRID_TOTAL_ACTIVE_POWER_LOW
    PV_POWER = PV_TOTAL_INPUT_POWER_LOW
    TOTAL_ENERGY = TOTAL_ENERGY_LOW
    
    # =========================================================================
    # String Input Data (0x1050-0x107F) - Voltage/Current pairs
    # =========================================================================
    STRING1_CURRENT = 0x1051      # S16, scale 0.01A
    STRING2_CURRENT = 0x1053      # S16, scale 0.01A
    STRING3_CURRENT = 0x1055      # S16, scale 0.01A
    STRING4_CURRENT = 0x1057      # S16, scale 0.01A
    STRING5_CURRENT = 0x1059      # S16, scale 0.01A
    STRING6_CURRENT = 0x105B      # S16, scale 0.01A
    STRING7_CURRENT = 0x105D      # S16, scale 0.01A
    STRING8_CURRENT = 0x105F      # S16, scale 0.01A
    STRING1_VOLTAGE = 0x1050      # U16, scale 0.1V
    STRING2_VOLTAGE = 0x1052      # U16, scale 0.1V
    STRING3_VOLTAGE = 0x1054      # U16, scale 0.1V
    STRING4_VOLTAGE = 0x1056      # U16, scale 0.1V
    STRING5_VOLTAGE = 0x1058      # U16, scale 0.1V
    STRING6_VOLTAGE = 0x105A      # U16, scale 0.1V
    STRING7_VOLTAGE = 0x105C      # U16, scale 0.1V
    STRING8_VOLTAGE = 0x105E      # U16, scale 0.1V
    
    # =========================================================================
    # DEA-AVM Real-time Data (0x03E8-0x03FD) - For H05 Body Type 14
    # =========================================================================
    DEA_L1_CURRENT_LOW = 0x03E8      # S32, scale 0.1A
    DEA_L2_CURRENT_LOW = 0x03EA      # S32, scale 0.1A
    DEA_L3_CURRENT_LOW = 0x03EC      # S32, scale 0.1A
    DEA_L1_VOLTAGE_LOW = 0x03EE      # S32, scale 0.1V
    DEA_L2_VOLTAGE_LOW = 0x03F0      # S32, scale 0.1V
    DEA_L3_VOLTAGE_LOW = 0x03F2      # S32, scale 0.1V
    DEA_TOTAL_ACTIVE_POWER_LOW = 0x03F4      # S32, scale 0.1kW
    DEA_TOTAL_REACTIVE_POWER_LOW = 0x03F6      # S32, scale 1 Var
    DEA_POWER_FACTOR_LOW = 0x03F8      # S32, scale 0.001
    DEA_FREQUENCY_LOW = 0x03FA      # S32, scale 0.1Hz
    DEA_STATUS_FLAG_LOW = 0x03FC      # S32, bit field
    DEA_L1_CURRENT_HIGH = 0x03E9
    DEA_L2_CURRENT_HIGH = 0x03EB
    DEA_L3_CURRENT_HIGH = 0x03ED
    DEA_L1_VOLTAGE_HIGH = 0x03EF
    DEA_L2_VOLTAGE_HIGH = 0x03F1
    DEA_L3_VOLTAGE_HIGH = 0x03F3
    DEA_TOTAL_ACTIVE_POWER_HIGH = 0x03F5
    DEA_TOTAL_REACTIVE_POWER_HIGH = 0x03F7
    DEA_POWER_FACTOR_HIGH = 0x03F9
    DEA_FREQUENCY_HIGH = 0x03FB
    DEA_STATUS_FLAG_HIGH = 0x03FD
    
    # =========================================================================
    # DER-AVM Control Parameters (0x07D0-0x0835) - For H05 Body Type 13
    # =========================================================================
    INVERTER_ON_OFF = 0x0834      # U16: 0=ON, 1=OFF
    DER_POWER_FACTOR_SET = 0x07D0      # S16, scale 0.001, [-1000,-800],[800,1000]
    DER_ACTION_MODE = 0x07D1      # U16: 0=self, 2=DER-AVM, 5=Q(V)
    DER_REACTIVE_POWER_PCT = 0x07D2      # S16, scale 0.1%, [-484, 484]
    DER_ACTIVE_POWER_PCT = 0x07D3      # U16, scale 0.1%, [0, 1100]
    CLEAR_PV_INSULATION_WARNING = 0x0835      # U16: 0=Non-active, 1=Clear
    
    # Aliases for backward compatibility
    POWER_FACTOR_SET = DER_POWER_FACTOR_SET
    ACTION_MODE = DER_ACTION_MODE
    REACTIVE_POWER_PCT = DER_REACTIVE_POWER_PCT
    ACTIVE_POWER_PCT = DER_ACTIVE_POWER_PCT
    OPERATION_MODE = DER_ACTION_MODE
    REACTIVE_POWER_SET = DER_REACTIVE_POWER_PCT
    
    # =========================================================================
    # Inverter Control (0x6001-0x6010)
    # =========================================================================
    INVERTER_CONTROL = 0x6001      # U16: 0=power on, 1=shut down
    EEPROM_DEFAULT = 0x6006      # U16: 0=not default, 1=default
    CLEAR_ENERGY_RECORD = 0x6009      # U16: 0=not clear, 1=clear
    IV_CURVE_SCAN = 0x600D      # U16: Write 0=Non-active, 1=Active; Read 0=Idle, 1=Running, 2=Finished
    POWER_FACTOR_DYNAMIC = 0x600F      # S16, scale 0.001 (dynamic control)
    REACTIVE_POWER_DYNAMIC = 0x6010      # S16, scale 0.01% (dynamic control)
    
    # Alias
    IV_SCAN_COMMAND = IV_CURVE_SCAN
    IV_SCAN_STATUS = IV_CURVE_SCAN
    
    POWER_DERATING_PCT = 0x3005      # U16, [0-110]%, dynamic active power
    
    # =========================================================================
    # IV Scan Data Registers (0x8000-0x847F)
    # =========================================================================
    IV_TRACKER1_VOLTAGE_BASE = 0x8000      # 64 regs (0x8000-0x803F)
    IV_STRING1_1_CURRENT_BASE = 0x8040      # 64 regs (0x8040-0x807F)
    IV_STRING1_2_CURRENT_BASE = 0x8080      # 64 regs (0x8080-0x80BF)
    IV_TRACKER2_VOLTAGE_BASE = 0x8140      # 64 regs (0x8140-0x817F)
    IV_STRING2_1_CURRENT_BASE = 0x8180      # 64 regs (0x8180-0x81BF)
    IV_STRING2_2_CURRENT_BASE = 0x81C0      # 64 regs (0x81C0-0x81FF)
    IV_TRACKER3_VOLTAGE_BASE = 0x8280      # 64 regs (0x8280-0x82BF)
    IV_STRING3_1_CURRENT_BASE = 0x82C0      # 64 regs (0x82C0-0x82FF)
    IV_STRING3_2_CURRENT_BASE = 0x8300      # 64 regs (0x8300-0x833F)
    IV_TRACKER4_VOLTAGE_BASE = 0x83C0      # 64 regs (0x83C0-0x83FF)
    IV_STRING4_1_CURRENT_BASE = 0x8400      # 64 regs (0x8400-0x843F)
    IV_STRING4_2_CURRENT_BASE = 0x8440      # 64 regs (0x8440-0x847F)
    
    # IV Scan data points count
    IV_SCAN_DATA_POINTS = 64
    
    # IV Scan tracker block size (0x140 = 320 registers)
    IV_TRACKER_BLOCK_SIZE = 0x140


class IVScanCommand:
    """IV Scan Command values for writing to 0x600D"""
    NON_ACTIVE = 0x0000  # Stop/Disable IV Scan
    ACTIVE = 0x0001      # Start IV Scan


class IVScanStatus:
    """IV Scan Status values when reading from 0x600D"""
    IDLE = 0x0000        # Idle or had been read
    RUNNING = 0x0001     # IV Scan in progress
    FINISHED = 0x0002    # IV Scan completed
    
    @classmethod
    def to_string(cls, status):
        status_map = {
            0x0000: "Idle",
            0x0001: "Running",
            0x0002: "Finished"
        }
        return status_map.get(status, f"Unknown({status})")


class InverterMode:
    """Inverter Mode Table (0x101D) - Per Solarize Document"""
    INITIAL = 0x00
    STANDBY = 0x01
    ON_GRID = 0x03
    OFF_GRID = 0x04
    FAULT = 0x05
    SHUTDOWN = 0x09
    
    @classmethod
    def to_string(cls, mode):
        mode_map = {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown"
        }
        return mode_map.get(mode, f"Unknown({mode})")


class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL = 5


class DeviceType:
    """Device Type for config file"""
    RTU = 0
    INVERTER = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER = 3
    PROTECTION_RELAY = 4
    
    @classmethod
    def to_string(cls, dtype):
        type_map = {
            0: "RTU",
            1: "Inverter",
            2: "Environment Sensor",
            3: "Power Meter",
            4: "Protection Relay"
        }
        return type_map.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE = "NONE"
    DER_AVM = "DER_AVM"


class IVScanBodyType:
    """IV Scan Body Type mapping for H05 protocol"""
    IV_SCAN_RESULT = 12
    IV_SCAN_DATA = 15
    TRACKER1_VOLTAGE = 134
    TRACKER2_VOLTAGE = 139
    TRACKER3_VOLTAGE = 144
    TRACKER4_VOLTAGE = 149
    STRING1_1_CURRENT = 135
    STRING1_2_CURRENT = 136
    STRING2_1_CURRENT = 140
    STRING2_2_CURRENT = 141
    STRING3_1_CURRENT = 145
    STRING3_2_CURRENT = 146
    STRING4_1_CURRENT = 150
    STRING4_2_CURRENT = 151


class ErrorCode1:
    """Error Code Table1 (0x101E) - Bit field"""
    BITS = {
        0: "Inverter over dc-bias current",
        1: "Inverter relay abnormal",
        2: "Remote off",
        3: "Inverter over temperature",
        4: "GFCI abnormal",
        5: "PV string reverse",
        6: "System type error",
        7: "Fan abnormal",
        8: "Dc-link unbalance or under voltage",
        9: "Dc-link over voltage",
        10: "Internal communication error",
        11: "Software incompatibility",
        12: "Internal storage error",
        13: "Data inconsistency",
        14: "Inverter abnormal",
        15: "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode2:
    """Error Code Table2 (0x101F) - Bit field"""
    BITS = {
        0: "Grid over voltage",
        1: "Grid under voltage",
        2: "Grid absent",
        3: "Grid over frequency",
        4: "Grid under frequency",
        5: "PV over voltage",
        6: "PV insulation abnormal",
        7: "Leakage current abnormal",
        8: "Inverter in power limit state",
        9: "Internal power supply abnormal",
        10: "PV string abnormal",
        11: "PV under voltage",
        12: "PV irradiation weak",
        13: "Grid abnormal",
        14: "Arc fault detection",
        15: "AC moving average voltage high",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


class ErrorCode3:
    """Error Code Table3 (0x1020) - Bit field"""
    BITS = {
        0: "Reserved",
        1: "Logger/E-Display EEPROM fail",
        2: "Reserved",
        3: "Single tracker detect warning",
        4: "AFCI lost",
        5: "Data logger lost",
        6: "Meter lost",
        7: "Inverter lost",
        8: "Grid N abnormal",
        9: "Surge Protection Devices (SPD) defective",
        10: "Parallel ID warning",
        11: "Parallel SYN signal warning",
        12: "Parallel BAT abnormal",
        13: "Parallel GRID abnormal",
        14: "Generator voltage abnormal",
        15: "Reserved",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"


# Scale factors - Per Solarize protocol document
SCALE = {
    'voltage': 0.1,
    'current': 0.01,
    'power': 0.1,
    'frequency': 0.01,
    'power_factor': 0.001,
    'dea_current': 0.1,
    'dea_voltage': 0.1,
    'dea_active_power': 0.1,
    'dea_reactive_power': 1,
    'dea_frequency': 0.1,
    'iv_voltage': 0.1,
    'iv_current': 0.1,
}


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Get voltage and current register addresses for a string number (1-8)"""
    if string_num < 1 or string_num > 8:
        raise ValueError(f"String number must be 1-8, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)  # (voltage, current)


def get_mppt_registers(mppt_num):
    """Get voltage, current, power registers for MPPT number (1-4)"""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    else:  # mppt_num == 4
        base = 0x103E
    return (base, base + 1, base + 2, base + 3)  # (voltage, current, power_low, power_high)


def get_iv_tracker_voltage_registers(tracker_num, data_points=64):
    """Get IV scan voltage register range for a tracker (1-4)"""
    if tracker_num < 1 or tracker_num > 4:
        raise ValueError(f"Tracker number must be 1-4, got {tracker_num}")
    base_addresses = {
        1: RegisterMap.IV_TRACKER1_VOLTAGE_BASE,
        2: RegisterMap.IV_TRACKER2_VOLTAGE_BASE,
        3: RegisterMap.IV_TRACKER3_VOLTAGE_BASE,
        4: RegisterMap.IV_TRACKER4_VOLTAGE_BASE,
    }
    base = base_addresses[tracker_num]
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=64):
    """Get IV scan current register range for a specific string"""
    if mppt_num < 1 or mppt_num > 4:
        raise ValueError(f"MPPT number must be 1-4, got {mppt_num}")
    if string_num < 1 or string_num > 2:
        raise ValueError(f"String number must be 1-2, got {string_num}")
    base_addresses = {
        (1, 1): RegisterMap.IV_STRING1_1_CURRENT_BASE,
        (1, 2): RegisterMap.IV_STRING1_2_CURRENT_BASE,
        (2, 1): RegisterMap.IV_STRING2_1_CURRENT_BASE,
        (2, 2): RegisterMap.IV_STRING2_2_CURRENT_BASE,
        (3, 1): RegisterMap.IV_STRING3_1_CURRENT_BASE,
        (3, 2): RegisterMap.IV_STRING3_2_CURRENT_BASE,
        (4, 1): RegisterMap.IV_STRING4_1_CURRENT_BASE,
        (4, 2): RegisterMap.IV_STRING4_2_CURRENT_BASE,
    }
    base = base_addresses[(mppt_num, string_num)]
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=8, strings_per_mppt=2):
    """Get mapping of string numbers to voltage/current register addresses"""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num': string_idx + 1,
            'total_strings': total_strings,
            'mppt_num': mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base': v_regs['base'],
            'current_base': i_regs['base'],
            'data_points': data_points
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=64):
    """Generate IV scan voltage data array (U16, 0.1V units, ascending from v_min to voc)"""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=64):
    """Generate IV scan current data array (U16, 0.01A units) using IV curve approximation"""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 2))
        regs.append(int(current * 100) & 0xFFFF)
    return regs


class SolarizeStatusConverter:
    """Solarize INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        """Solarize INVERTER_MODE is already InverterMode-compatible."""
        return raw


# Dynamic-loader alias
StatusConverter = SolarizeStatusConverter


# Data type info per register
DATA_TYPES = {
    'PV_VOLTAGE': 'U16',
    'PV_CURRENT': 'U16',
    'PV_POWER': 'U16',
    'R_PHASE_VOLTAGE': 'U16',
    'S_PHASE_VOLTAGE': 'U16',
    'T_PHASE_VOLTAGE': 'U16',
    'R_PHASE_CURRENT': 'U16',
    'S_PHASE_CURRENT': 'U16',
    'T_PHASE_CURRENT': 'U16',
    'AC_POWER': 'U16',
    'POWER_FACTOR': 'U16',
    'FREQUENCY': 'U16',
    'TOTAL_ENERGY': 'U16',
    'INVERTER_MODE': 'U16',
    'ERROR_CODE1': 'U16',
    'ERROR_CODE2': 'U16',
    'INNER_TEMP': 'U16',
    'MPPT1_VOLTAGE': 'U16',
    'MPPT1_CURRENT': 'U16',
    'MPPT2_VOLTAGE': 'U16',
    'MPPT2_CURRENT': 'U16',
    'MPPT3_VOLTAGE': 'U16',
    'MPPT3_CURRENT': 'U16',
    'MPPT4_VOLTAGE': 'U16',
    'MPPT4_CURRENT': 'U16',
    'STRING1_CURRENT': 'U16',
    'STRING2_CURRENT': 'U16',
    'STRING3_CURRENT': 'U16',
    'STRING4_CURRENT': 'U16',
    'STRING5_CURRENT': 'U16',
    'STRING6_CURRENT': 'U16',
    'STRING7_CURRENT': 'U16',
    'STRING8_CURRENT': 'U16',
}

FLOAT32_FIELDS = set()

