# -*- coding: utf-8 -*-
"""
SchneiderElectric Inverter Modbus Register Map
Based on SchneiderElectric Modbus Protocol 
Protocol Name: schneiderelectric
MPPT: 2 | Strings: 0 (0/MPPT)
IV Scan: No | DER-AVM: Yes
Generated by Model Maker Web v2 on 2026-04-03
"""



class RegisterMap:
    """SchneiderElectric Modbus Register Map"""

    # =========================================================================
    # Device Information
    # =========================================================================
    DEVICE_MODEL_PDF                         = 0x0000  # TEXT
    APPARENT_POWER                           = 0x17F1  # U16, scale kVA

    # =========================================================================
    # Monitoring Data
    # =========================================================================
    ILLEGAL_FUNCTION                         = 0x0001  # U16
    ILLEGAL_DATA_VALUE                       = 0x0003  # U16
    SLAVE_DEVICE_ERROR                       = 0x0004  # U16
    MODBUS_PHYSICAL_LAYER                    = 0x0005  # U16
    THE_AC_OUTPUT_CURRENTEXCEEDS_THE_INVERTERSPROTECTION_LIMIT = 0x0006  # U16
    TRANSIENT_AC_OVER_CURRENT                = 0x0007  # U16
    TERMINATION_RESISTOR                     = 0x0008  # U16
    COMMUNICATION_PARAMETERS                 = 0x0009  # U16
    GR_L                                     = 0x000A  # U16
    THE_DC_COMPONENT_OF_THE_ACCURRENT_EXCEEDS_THE_INVERTERSLIMIT = 0x000B  # U16
    MODBUS_LOGICAL_LAYER                     = 0x000C  # U16
    ERROR_CHECK_FIELD_CHECKSUM               = 0x000D  # U16
    L3_VOLTAGE                               = 0x000E  # U16
    FUNCTION_43_DEVICE_DISCOVERY             = 0x0010  # U16
    BROADCASTS                               = 0x0012  # U16
    HIGH_DC_BUS_VOLTAGE                      = 0x0014  # U16
    SOFTWARE_PART_NUMBER_FOR_PROCESSOR_A     = 0x0082  # U16, scale A
    SOFTWARE_PART_NUMBER_FOR_PROCESSOR_B     = 0x0096  # U16
    SOFTWARE_PART_NUMBER_FOR_PROCESSOR_C     = 0x00AA  # U16
    CUMULATIVE_ENERGY                        = 0x0802  # U32
    CUMULATIVE_ENERGY_HIGH                   = 0x0803
    DAILY_ENERGY                             = 0x0804  # U32
    DAILY_ENERGY_HIGH                        = 0x0805
    ENERGY_TODAY_1_DAYEARLIER                = 0x0806  # U32
    ENERGY_TODAY_1_DAYEARLIER_HIGH           = 0x0807
    ENERGY_TODAY_2_DAYSEARLIER               = 0x0808  # U32
    ENERGY_TODAY_2_DAYSEARLIER_HIGH          = 0x0809
    ENERGY_TODAY_3_DAYSEARLIER               = 0x080A  # U32
    ENERGY_TODAY_3_DAYSEARLIER_HIGH          = 0x080B
    ENERGY_TODAY_4_DAYSEARLIER               = 0x080C  # U32
    ENERGY_TODAY_4_DAYSEARLIER_HIGH          = 0x080D
    ENERGY_TODAY_5_DAYSEARLIER               = 0x080E  # U32
    ENERGY_TODAY_5_DAYSEARLIER_HIGH          = 0x080F
    ENERGY_TODAY_6_DAYSEARLIER               = 0x0810  # U32
    ENERGY_TODAY_6_DAYSEARLIER_HIGH          = 0x0811
    OPERATING_HOURS                          = 0x081E  # U32
    OPERATING_HOURS_HIGH                     = 0x081F
    TEMPERATURE_1_NTC_ONCONTROL_BOARD        = 0x1701  # S16
    TEMPERATURE_2_BOOSTMODULE_1              = 0x1702  # S16
    TEMPERATURE_3_BOOSTMODULE_2              = 0x1703  # S16
    TEMPERATURE_4_INVERTERMODULE             = 0x1704  # S16
    REACTIVE_POWER                           = 0x17F4  # S16, scale kVAr
    INVERTER_VAB                             = 0x17F8  # S16
    INVERTER_VBC                             = 0x17F9  # S16
    INVERTER_VCA                             = 0x17FA  # S16
    L1_CURRENT                               = 0x17FB  # S16, scale A
    L2_CURRENT                               = 0x17FC  # S16
    L3_CURRENT                               = 0x17FD  # S16
    REAL_POWER_TOTAL                         = 0x17FE  # S16, scale kW
    PV1_VOLTAGE                              = 0x17FF  # S16, scale V
    PV1_CURRENT                              = 0x1800  # S16, scale A
    MPPT1_POWER_LOW                          = 0x1801  # S16, scale kW
    DC_VOLTAGE                               = 0x180D  # U16, scale V
    PHASE_A_FREQUENCY                        = 0x1818  # U16, scale Hz
    PHASE_B_FREQUENCY                        = 0x1819  # U16, scale Hz
    PHASE_C_FREQUENCY                        = 0x181A  # U16, scale Hz
    PHASE_A_REAL_POWER                       = 0x181B  # S16, scale kW
    PHASE_B_REAL_POWER                       = 0x181C  # S16, scale kW
    PHASE_C_REAL_POWER                       = 0x181D  # S16, scale kW
    PV2_VOLTAGE                              = 0x1829  # S16, scale V
    PV2_CURRENT                              = 0x182A  # S16, scale A
    PV2_POWERA                               = 0x182F  # S16, scale kW
    TIMESTAMP_HIGH                           = 0x4720  # U32
    TIMESTAMP_LOW                            = 0x4721  # U16
    TIMESTAMP_MS                             = 0x4722  # U16
    EVENT_1                                  = 0x4723  # U16
    EVENT_2                                  = 0x4724  # U16
    EVENT_3                                  = 0x4725  # U16
    EVENT_4                                  = 0x4726  # U16
    USER_REACTIVE_POWER                      = 0xFA1B  # S16, scale kVAr
    COS_WITH_POWERA_UPPER_LIMIT              = 0xFA62  # S16
    COS_WITH_POWERA_LOWER_LIMIT              = 0xFA63  # S16

    # =========================================================================
    # Status & Temperature
    # =========================================================================
    OPERATIONAL_MODE_STATE                   = 0x1700  # U16
    REACTIVE_POWER_MODE_SELECTA              = 0xFA60  # U16, scale kVAr

    # =========================================================================
    # Alarm / Error Codes
    # =========================================================================
    FAULT_CODE                               = 0x1828  # U16

    # --- Standard handler compatibility aliases (H01 Body Type 4 required) ---
    T_PHASE_VOLTAGE                          = L3_VOLTAGE
    R_PHASE_CURRENT                          = L1_CURRENT
    S_PHASE_CURRENT                          = L2_CURRENT
    T_PHASE_CURRENT                          = L3_CURRENT



class InverterMode:
    """Inverter Mode Table (0x101D)"""
    INITIAL      = 0x00
    STANDBY      = 0x01
    ON_GRID      = 0x03
    OFF_GRID     = 0x04
    FAULT        = 0x05
    SHUTDOWN     = 0x09

    @classmethod
    def to_string(cls, mode):
        return {
            0x00: "Initial",
            0x01: "Standby",
            0x03: "On-Grid",
            0x04: "Off-Grid",
            0x05: "Fault",
            0x09: "Shutdown",
        }.get(mode, f"Unknown(0x{mode:02X})")



class DerActionMode:
    """DER-AVM Action Mode (0x07D1)"""
    SELF_CONTROL    = 0
    DER_AVM_CONTROL = 2
    QV_CONTROL      = 5



class DeviceType:
    """Device Type for config file"""
    RTU              = 0
    INVERTER         = 1
    ENVIRONMENT_SENSOR = 2
    POWER_METER      = 3
    PROTECTION_RELAY = 4

    @classmethod
    def to_string(cls, dtype):
        return {
            0: "RTU", 1: "Inverter", 2: "Environment Sensor",
            3: "Power Meter", 4: "Protection Relay",
        }.get(dtype, f"Unknown({dtype})")


class ControlMode:
    """Control Mode for config file"""
    NONE    = "NONE"
    DER_AVM = "DER_AVM"




class ErrorCode1:
    """Error Code Table1 (0x1828) — Bit field"""
    BITS = {
        0:  "Inverter over dc-bias current",
        1:  "Inverter relay abnormal",
        2:  "Remote off",
        3:  "Inverter over temperature",
        4:  "GFCI abnormal",
        5:  "PV string reverse",
        6:  "System type error",
        7:  "Fan abnormal",
        8:  "Dc-link unbalance or under voltage",
        9:  "Dc-link over voltage",
        10:  "Internal communication error",
        11:  "Software incompatibility",
        12:  "Internal storage error",
        13:  "Data inconsistency",
        14:  "Inverter abnormal",
        15:  "Boost abnormal",
    }

    @classmethod
    def decode(cls, value):
        return [f"E{b}:{d}" for b, d in cls.BITS.items() if value & (1 << b)]

    @classmethod
    def to_string(cls, value):
        return ", ".join(cls.decode(value)) if value else "OK"



class SchneiderelectricStatusConverter:
    """SchneiderElectric INVERTER_MODE register already contains InverterMode values."""

    @classmethod
    def to_inverter_mode(cls, raw):
        return raw


# Dynamic-loader alias required by modbus_handler.load_register_module
StatusConverter = SchneiderelectricStatusConverter



# Scale factors
SCALE = {
    'voltage':            0.1,
    'current':            0.01,
    'power':              0.1,
    'frequency':          0.01,
    'power_factor':       0.001,
    'dea_current':        0.1,
    'dea_voltage':        0.1,
    'dea_active_power':   0.1,
    'dea_reactive_power': 1,
    'dea_frequency':      0.1,
    'iv_voltage':         0.1,
    'iv_current':         0.1,
}



# Channel configuration (used by modbus_handler for dynamic array sizing)
MPPT_CHANNELS = 2
STRING_CHANNELS = 0


def registers_to_u32(low, high):
    """Combine two U16 to U32"""
    return (high << 16) | low


def registers_to_s32(low, high):
    """Combine two U16 to S32"""
    value = (high << 16) | low
    if value >= 0x80000000:
        value -= 0x100000000
    return value


def get_string_registers(string_num):
    """Return (voltage_addr, current_addr) for a string number (1-0)."""
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0, got {string_num}")
    base = 0x1050 + (string_num - 1) * 2
    return (base, base + 1)


def get_mppt_registers(mppt_num):
    """Return (voltage, current, power_low, power_high) for MPPT number (1-2)."""
    if mppt_num < 1 or mppt_num > 2:
        raise ValueError(f"MPPT number must be 1-2, got {mppt_num}")
    if mppt_num <= 3:
        base = 0x1010 + (mppt_num - 1) * 4
    elif mppt_num == 4:
        base = 0x103E
    else:  # 5+
        base = 0x1080 + (mppt_num - 5) * 4
    return (base, base + 1, base + 2, base + 3)


def get_iv_tracker_voltage_registers(tracker_num, data_points=0):
    """Return {'base', 'count', 'end'} for IV voltage block of a tracker (1-2)."""
    if tracker_num < 1 or tracker_num > 2:
        raise ValueError(f"Tracker number must be 1-2, got {tracker_num}")
    base = 0x8000 + (tracker_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_current_registers(mppt_num, string_num, data_points=0):
    """Return {'base', 'count', 'end'} for IV current block of a string (string_num 1-0)."""
    if mppt_num < 1 or mppt_num > 2:
        raise ValueError(f"MPPT number must be 1-2, got {mppt_num}")
    if string_num < 1 or string_num > 0:
        raise ValueError(f"String number must be 1-0 per MPPT, got {string_num}")
    tracker_base = 0x8000 + (mppt_num - 1) * RegisterMap.IV_TRACKER_BLOCK_SIZE
    base = tracker_base + string_num * 0x40
    return {'base': base, 'count': data_points, 'end': base + data_points - 1}


def get_iv_string_mapping(total_strings=0, strings_per_mppt=0):
    """Return list of dicts mapping string index to IV scan register addresses."""
    mapping = []
    data_points = RegisterMap.IV_SCAN_DATA_POINTS
    for string_idx in range(total_strings):
        mppt_num       = (string_idx // strings_per_mppt) + 1
        string_in_mppt = (string_idx % strings_per_mppt) + 1
        v_regs = get_iv_tracker_voltage_registers(mppt_num, data_points)
        i_regs = get_iv_string_current_registers(mppt_num, string_in_mppt, data_points)
        mapping.append({
            'string_num':     string_idx + 1,
            'total_strings':  total_strings,
            'mppt_num':       mppt_num,
            'string_in_mppt': string_in_mppt,
            'voltage_base':   v_regs['base'],
            'current_base':   i_regs['base'],
            'data_points':    data_points,
        })
    return mapping


def generate_iv_voltage_data(voc, v_min, data_points=0):
    """Generate IV scan voltage array (U16, 0.1V units, ascending v_min->voc)."""
    step = (voc - v_min) / max(data_points - 1, 1)
    return [int((v_min + step * i) * 10) & 0xFFFF for i in range(data_points)]


def generate_iv_current_data(isc, voc, v_min, data_points=0):
    """Generate IV scan current array (U16, 0.01A units) using IV curve approximation."""
    step = (voc - v_min) / max(data_points - 1, 1)
    regs = []
    for i in range(data_points):
        v = v_min + step * i
        ratio = v / voc if voc > 0 else 0
        current = max(0.0, isc * (1.0 - ratio ** 20))
        regs.append(int(current * 100) & 0xFFFF)
    return regs



DATA_TYPES = {
    'DEVICE_MODEL_PDF': 'TEXT',
    'ILLEGAL_FUNCTION': 'U16',
    'ILLEGAL_DATA_VALUE': 'U16',
    'SLAVE_DEVICE_ERROR': 'U16',
    'MODBUS_PHYSICAL_LAYER': 'U16',
    'THE_AC_OUTPUT_CURRENTEXCEEDS_THE_INVERTERSPROTECTION_LIMIT': 'U16',
    'TRANSIENT_AC_OVER_CURRENT': 'U16',
    'TERMINATION_RESISTOR': 'U16',
    'COMMUNICATION_PARAMETERS': 'U16',
    'GR_L': 'U16',
    'THE_DC_COMPONENT_OF_THE_ACCURRENT_EXCEEDS_THE_INVERTERSLIMIT': 'U16',
    'MODBUS_LOGICAL_LAYER': 'U16',
    'ERROR_CHECK_FIELD_CHECKSUM': 'U16',
    'L3_VOLTAGE': 'U16',
    'FUNCTION_43_DEVICE_DISCOVERY': 'U16',
    'BROADCASTS': 'U16',
    'HIGH_DC_BUS_VOLTAGE': 'U16',
    'SOFTWARE_PART_NUMBER_FOR_PROCESSOR_A': 'U16',
    'SOFTWARE_PART_NUMBER_FOR_PROCESSOR_B': 'U16',
    'SOFTWARE_PART_NUMBER_FOR_PROCESSOR_C': 'U16',
    'CUMULATIVE_ENERGY': 'U32',
    'DAILY_ENERGY': 'U32',
    'ENERGY_TODAY_1_DAYEARLIER': 'U32',
    'ENERGY_TODAY_2_DAYSEARLIER': 'U32',
    'ENERGY_TODAY_3_DAYSEARLIER': 'U32',
    'ENERGY_TODAY_4_DAYSEARLIER': 'U32',
    'ENERGY_TODAY_5_DAYSEARLIER': 'U32',
    'ENERGY_TODAY_6_DAYSEARLIER': 'U32',
    'OPERATING_HOURS': 'U32',
    'OPERATIONAL_MODE_STATE': 'U16',
    'TEMPERATURE_1_NTC_ONCONTROL_BOARD': 'S16',
    'TEMPERATURE_2_BOOSTMODULE_1': 'S16',
    'TEMPERATURE_3_BOOSTMODULE_2': 'S16',
    'TEMPERATURE_4_INVERTERMODULE': 'S16',
    'APPARENT_POWER': 'U16',
    'REACTIVE_POWER': 'S16',
    'INVERTER_VAB': 'S16',
    'INVERTER_VBC': 'S16',
    'INVERTER_VCA': 'S16',
    'L1_CURRENT': 'S16',
    'L2_CURRENT': 'S16',
    'L3_CURRENT': 'S16',
    'REAL_POWER_TOTAL': 'S16',
    'PV1_VOLTAGE': 'S16',
    'PV1_CURRENT': 'S16',
    'PV1_POWER': 'S16',
    'DC_VOLTAGE': 'U16',
    'PHASE_A_FREQUENCY': 'U16',
    'PHASE_B_FREQUENCY': 'U16',
    'PHASE_C_FREQUENCY': 'U16',
    'PHASE_A_REAL_POWER': 'S16',
    'PHASE_B_REAL_POWER': 'S16',
    'PHASE_C_REAL_POWER': 'S16',
    'FAULT_CODE': 'U16',
    'PV2_VOLTAGE': 'S16',
    'PV2_CURRENT': 'S16',
    'PV2_POWERA': 'S16',
    'TIMESTAMP_LOW': 'U16',
    'TIMESTAMP_MS': 'U16',
    'EVENT_1': 'U16',
    'EVENT_2': 'U16',
    'EVENT_3': 'U16',
    'EVENT_4': 'U16',
    'USER_REACTIVE_POWER': 'S16',
    'REACTIVE_POWER_MODE_SELECTA': 'U16',
    'COS_WITH_POWERA_UPPER_LIMIT': 'S16',
    'COS_WITH_POWERA_LOWER_LIMIT': 'S16',
}

FLOAT32_FIELDS: set = set()


# String 전류 모니터링 지원 여부
# True: String별 전류 레지스터 있음 (Solarize, Senergy, Kstar 등)
# False: String 전류 레지스터 없음 (Huawei 등 — PV 전류만 제공)
STRING_CURRENT_MONITOR = False
